### ISSUE TITLE
Rotate voting rights (revoke, grant)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#10134]
## What is the Problem Being Solved?

BLD stakers lack a feasible mechanism to elect a different EC membership. 
Voting and proposing rights need to be revoked / granted.
This issue is about granting and revoking voting rights (rights to participate in the `committee.js` contract), and about priority.

## Description of the Design

a core eval script based on gov-replace-committee.js

## Security Considerations

_TBD_

## Scaling Considerations

not much.

## Test Plan

bootstrap test to replace 6 members of the committee with 3 continuing members. Test that:

- [x] 2 continuing members can change a parameter such as a PSM debt limit.
- [x] 2 Outgoing members cannot change parameters
- [x] A combination of 1 continuing and 2 outgoing members fails
- [x] A combination of 2 continuing and 1 outgoing members succeeds
- [x] outgoing members are no longer in the high priority senders list. _look in vstorage_

## Upgrade Considerations

none; #10137 main involve an upgrade of `committee.js`, but it's out of scope of this issue.

**Comment by otoole-brendan** [comment]
@frazarshad and @rabi-siddique could you please estimate this ticket?

**Comment by rabi-siddique** [comment]
The core eval script is ready and working fine. 

Work for the bootstrap test remains.

**Comment by dckc** [comment]
Use `E(highPrioritySendersManager).remove(description, addr)`

**Comment by dckc** [comment]
I saw some questions...

> ... currently our experimentation is located in `packages/inter-protocol/test/psm/gov-replace-committee.js`. Should we consider moving this script to the `packages/inter-protocol/src/proposals` folder,

yes.

Keep in mind that there are existing tests that refer to it. If the tests can point to the `.../src/...` location, then moving it is very well. Otherwise, we might want to leave the version in `/test/` alone and put the new work under `.../src/...`.

> or is there a more appropriate directory where we organize our core eval scripts? How do we typically structure and organize core eval scripts?

Along with the core eval code in `gov-replace-committee.js`, you need a builder script that calls `writeCoreProposal`, as discussed in [agoric run supports bundling proposal modules with writeCoreProposal](https://github.com/Agoric/agoric-sdk/discussions/8087#discussioncomment-6534378)

One example that has those pieces plus a contract started by the core eval code is
 - https://github.com/Agoric/agoric-sdk/pull/9679
   - `init-basic-flows.js` is the builder script
   - `start-basic-flows.js` is the core eval code
