### ISSUE TITLE
CLI for Fast USDC transfer

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10339]
## What is the Problem Being Solved?

We need a way to validate that a web app like Noble Express can be used with the rest of Fast USDC to achieve the user's aims. In particular, what the UI has to do to get the transaction onto the Ethereum ledger such that Noble x/forwarding will work.

We'll validate it by building a real (but unpolished) CLI for initiating a fast transfer.

## Description of the Design

CLI version of the Fast USDC end user workflow.

Add a `transfer` command to [fast-usdc cli](https://github.com/Agoric/agoric-sdk/blob/master/packages/fast-usdc/src/cli.js)

- user can request a transfer of USDC to their EUD (always use FU)
- app prints progress until the EUD has received the funds
- app reports time taken

Operation to calculate Noble address
- From vstorage fetch the address of the LCA that Fast USDC uses for staging transfers
- Get <dest> address from user (e.g. dydx1blablah)
- Supplement LCA address with destination address to create a routing virtual address: agoric1<lca>+<dest>
- Use (unreleased) Noble x/forwarding ability to predetermine the noble1 forwarding address for the agoric1 address
- Ask user to sign a transfer to that noble1 address, with the above assurances

It can be used in CI, either by CLI or be importing the modules that power the CLI.
- Assume CI will have reachable instances of RPC for Ethereum, Noble, Agoric, EUD chain

## Security Considerations
n/a, testing

## Scaling Considerations
n/a, testing

## Upgrade Considerations

**Comment by samsiegart** [comment]
@turadg I talked with @LuqiPan about this. We are thinking the "app prints progress until the EUD has received the funds" part needn't be too granular, because we're probably just going to show a rough time estimate until it completes in the actual UI. The CLI already sends the transfer (https://github.com/Agoric/agoric-sdk/pull/10437), but doesn't track anything. I think at minimum though, it should report when the EUD receives the funds. Does that sound like reasonable acceptance criteria? I anticipate this feature will need to be updated after https://github.com/Agoric/agoric-sdk/issues/10614 as well.
