### ISSUE TITLE
Failed calls to `readFully` method of `client-utils` package

### ISSUE THREAD

**Issue by Jorge-Lopes** [Agoric/Agoric#10563]
## Describe the bug
When using the `readFully` method from the agoric `client-utils` package, the following error occurs:
`TypeError: Cannot read properties of undefined (reading 'readAt').`
This issue originates from the code [here](https://github.com/Agoric/agoric-sdk/blob/master/packages/client-utils/src/vstorage-kit.js#L101-L106).

The same issue also affects other methods in the `makeVStorage` function of the `vstorage-kit` module. The problem stems from the usage of the `this` keyword, causing instance method invocations to fail.

## To Reproduce
1. Go to Draft PR #10555
2. Re-run the CI action `test-docker-build`
3. See error message

## Expected behavior
The `readFully` method should correctly return the values stored in a specific node, recorded after a given block height.

## Platform Environment
OS: macOS Sequoia v15.0.1
Node.js: v20.9.0
Agoric-SDK: agoric-upgrade-16av-1130-g753242866

## Screenshots

Relevant CI Logs:
```

  Rejected promise returned by test. Reason:

  TypeError {
    message: 'Cannot read properties of undefined (reading \'readAt\')',
  }

  TypeError: Cannot read properties of undefined (reading 'readAt')
      at readFully (file:///usr/src/agoric-sdk/packages/client-utils/src/vstorage-kit.js:102:49)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async getGovernanceProposalsHistory (file:///usr/src/proposals/z:acceptance/test-lib/governance.js:228:22)
      at async file:///usr/src/proposals/z:acceptance/governance.test.js:184:19

```

**Comment by Jorge-Lopes** [comment]
cc: @Chris-Hibbert

**Comment by turadg** [comment]
This is not a bug. Your diagnosis is correct that it's missing `this`, but that's because you're using an instance method as a naked function. Instead, pass the `vstorage` object. 

If you want to be able to pass the functions without their instance object that's a feature request. ~I don't think we need it but if you really do you can update the body and labels and re-open this.~ Second thought, it would be easier to support this than document it as a limitation
