### ISSUE TITLE
reduce complexity by dropping `setReferences` and start using `privateArgs` instead in `provisionPool`

### ISSUE THREAD

**Issue by anilhelvaci** [Agoric/Agoric#10564]
## What is the Problem Being Solved?
Currently the `setReferences` method  is used to pass `bankManager`, `walletFactory` and `namesByAddressAdmin` into the `provisionPool`. This creates complexity when trying to instantiate `exo` objects that depend on these powers.

The problem occurs during an upgrade. SwingSet expects all `exo` objects defined in the previous incarnation to be instantiated during the start up. If there's an `exo` object that depends on state that is set after the startup, like calling `setReferences` after the start up is complete, the work around causes code get more complex.

## Description of the Design
Move `bankManager`, `walletFactory` and `namesByAddressAdmin` into `privateArgs`

**Comment by Jorge-Lopes** [comment]
cc: @Chris-Hibbert

**Comment by Chris-Hibbert** [comment]
> SwingSet expects all exo objects defined in the previous incarnation to be instantiated during the start up.

This isn't quite right.
SwingSet requires that all Exo types defined in the previous incarnation receive new definitions during startup. SwingSet will later use those new definitions and the stored state of the durable objects to create new instances when those objects are needed.

That triple of objects (defined by the type `ProvisionPoolKitReferences` in `provisionPoolKit.js`) is known to the `ProvisionPoolKit`, but their values are not defined at initial creation.

An important design constraint on this code is that it continue to be possible to start up a new chain from scratch. The startup order currently has the walletFactory created later than the provisionPool, so it doesn't exist when the provisionPool is created.

So provisionPool needs to continue to have `setReferences`, and to start up without those values. But that's not an issue for upgrade, since every instance has those values stored in baggage, and the type definition doesn't depend on the values.

The new Exo object to replace `Far('provisioningHandler', ...)` gets the values of the `ProvisionPoolKitReferences` passed in at creation time, which allows it to be instantiated on demand.

`makeBridgeProvisionTool()` returns a maker that takes `({ bankManager, namesByAddressAdmin, walletFactory })` as its parameters, and it should create an Exo from them. That [innerMaker is used by `makeHandler`](https://github.com/Agoric/agoric-sdk/blob/5b09631443011562de0c2077e46652d282012515/packages/inter-protocol/src/provisionPoolKit.js#L220).

I think you want to use `prepareExoClass`, since it supports initializing instance state, and has a single facet.  [`AmountWatcher`](https://github.com/Agoric/agoric-sdk/blob/5b09631443011562de0c2077e46652d282012515/packages/smart-wallet/src/smartWallet.js#L312) is a relatively simple example. The fourth parameter describes the initializer, which takes arguments and returns the state object. The fifth parameter is the behavior, which, in this case, will be a copy of the `provisioningHandler`'s behavior, with minor modifications to access the values from state. 

`AmountWatcher` accesses the state by using `const { helper, purse } = this.state;` as the first line, and can then refer to `helper` and `purse` as local variables.  `provisioningHandler` would have `const { bankManager, namesByAddressAdmin, walletFactory } = this.state;`

Let me know if you want advice on constructing the guard for the third parameter. Everything else should be straigthforward.

**Comment by anilhelvaci** [comment]
> SwingSet requires that all Exo types defined in the previous incarnation receive new definitions during startup.

Hmm 🤔 I remember SwingSet complaining when I tried to do something like
```js
const makeBridgeHandler = prepareBridgeHandlerTool(zone);
const handler = makeBridgeHandler(); // This throws
```

Above code threw when executed in the start up if the previous incarnation already introduced the object with an error message like `object with "xxxx" interface name already defined`. I worked my around this using `provide`.

> An important design constraint on this code is that it continue to be possible to start up a new chain from scratch. The startup order currently has the walletFactory created later than the provisionPool, so it doesn't exist when the provisionPool is created.

So you say the cost of fixing all the code run during the start from scratch is too high, correct? I am asking because I think `walletFactory` does not depend `provisionPool` so technically we can switch the order right?


> I think you want to use prepareExoClass, since it supports initializing instance state, and has a single facet.

Yep, I tired to call the maker returned from `prepareExoClass` inside `makeHandler` and during a null upgrade I faced an issue like;

```
error during vat dispatch() of startVat,[object Object] (Error#1)
Error#1: defineDurableKind not called for tags: [ZDEFAULT brand,ZDEFAULT payment,ZDEFAULT Purse,ZDEFAULT issuer,ZDEFAULT mint,FeeMint,Zoe Invitation brand,Zoe Invitation payment,Zoe Invitation Purse,Zoe Invitation issuer,Zoe Invitation mint,InstanceAdmin,BundleIDInstallation,BundleInstallation,InstallationStorage,ZoeMint,InstanceStorageManager,InstanceRecord,ZoeStorageManager,InstanceHandle,zoe Seat publisher,ZoeSeatKit,SeatHandle,instanceAdmin,zoeInstanceAdmin,emptyCreatorFacet,emptyPublicFacet,adminFacet,ZoeService]
```

Above error message if from https://github.com/Agoric/agoric-sdk/issues/7651

Here's my workaround https://github.com/Agoric/agoric-sdk/commit/1e8f8d0657fecf6b581832f1ef372a9948a77928, please let me know what you think @Chris-Hibbert

**Comment by Chris-Hibbert** [comment]
```
const makeBridgeHandler = prepareBridgeHandlerTool(zone);
const handler = makeBridgeHandler(); // This throws
```

If `makeBridgeHandler` is defined the way I expect, you'd have to call it with `makeBridgeHandler(bankManager, namesByAddressAdmin, walletFactory)`.

> I worked my around this using provide.

Yes, that's correct. Each Exo type has to be defined exactly once during startup, and provide is the standard way to do that.

> `walletFactory` does not depend on `provisionPool` so technically we can switch the order right?

Umm. technically, yeah, but carrying that out would need to touch many delicate things inside bootstrap. I don't think we need to do that in order to make provisionPool upgrade cleanly. 

> I tired to call the maker returned from prepareExoClass inside makeHandler and during a null upgrade I faced an issue like;

By "null upgrade" we mean upgrade without changing the code. In order to define the new Exo, there has to be new code, so this wasn't a null upgrade.

> Error#1: defineDurableKind not called for tags: [...]

`zone.exo()` defines a single Exo object. I think we want `zone.exoClass()` to define a class; it returns a maker. If the fourth arg (`init`) to `exoClass()` looks like `(bankManager, namesByAddressAdmin, walletFactory) => ({ bankManager, namesByAddressAdmin, walletFactory })`, then the maker it returns will take those three parameters.

**Comment by anilhelvaci** [comment]
The approach discussed here has its final version in https://github.com/Agoric/agoric-sdk/pull/10419.
