### ISSUE TITLE
Save some facets to enable admin of replaced contracts and vats

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#10669]
## What is the Problem Being Solved?

When we add a new auction or priceFeed, the `adminFacet`s saved in bootstrap space are overwritten by the newer contract. The old contractKit remains, since that was indexed by instance. It would be easier to manage (upgrade, terminate, change governed parameters) the old contracts if we saved their instance.

## Description of the Design

Make a new map in bootstrap space (`retiredContracts` is my proposed name) which is indexed by strings. As we replace various contracts, save the instance there.

## Security Considerations

bootstrap space is tightly controlled. This doesn't add risk.

## Scaling Considerations

As the chain evolves, we'll have more old vats and contracts to manage.

## Test Plan

Make sure the names appear in the bootstrap promise space.

## Upgrade Considerations

It's all upgrade.

**Comment by warner** [comment]
We've made a couple spins for the upgrade18 branch in the last few days, we tested rc4 this afternoon, and will test an rc5 next.

* The auctioneer proposal was not using the same "stash something indexed by `instance`" that contracts did. We didn't realize that, so rc4 fails to stash the old auctioneer kit in the map where we stash contract instances. This will be fixed in rc5 (#10694)
