### ISSUE TITLE
multiple facets for each virtual object

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#3834]
## What is the Problem Being Solved?

In the kernel meeting last week (8-sep-2021), @dtribble raised the idea of adding swingset support for multiple facets on virtual objects. A common case is for a single object to have both an "exchange" facet (allowing you to change ownership) and a "use" facet (allowing you to do something other-than / subordinate-to ownership). For example, you might put the exchange facet into an Offer (which gets escrowed by Zoe), but you can continue to exercise the use facet until Zoe transfers ownership upon contract completion.

This pattern can be implemented by contract code, but it might be easier and more efficient if swingset (and the virtual object manager) could help out. Basically we've got a single bundle of state, and multiple forms of behavior to wrap around it. Given an existing virtual object, it might be interesting to define a new object (with new behavior) that gets to modify the same original state. Both the old and new virtual objects (facets) would have ephemeral Representatives, and the VOM would know how to recreate either facet upon demand, so everything else about them could be removed from RAM when not in use.

It is also quite common for one facet to get revoked once the other is created: exercising the exchange facet (to transfer ownership) must revoke the previous use facet. So low-level support for revoking facets might help.

## Description of the Design

To approach this, `makeKind()` would probably need to return an extra object for use in a rights-amplification pattern. Later, if you invoke this extra object and give it a Representative (facet-1), you can create a related facet-2 Representative, which gets its own vref.

`makeKind()` might also return a third object for use in revocation. One open question is whether revocation should be implemented with an interposed revocable forwarder on the outside of the target object (so nobody can invoke its methods), or inside (so the revoked facet's behavior methods cannot reach the state), or both.

This is entangled with upgrade and #3062: one way to change/fix/improve the behavior of a class of objects would be to create new facets on the old state. 

## Security Considerations

The authority to create a new facet around old data is equivalent to that of modifying the old data, so it must be carefully managed. Merely having access to facet-1 is certainly not sufficient to create facet-2.

The ability to change the behavior of previously-defined facets (upgrade) needs to be clearly marked as well. The ability to create the class of objects in the first place is not sufficient: while the provider of the kind constructor can obviously make the objects/facets behave in any way they desire, that does not give them the ability to retroactively modify that behavior in ways that could not be deduced from a reading the original code. So out upgrade story needs to include some additional control object.

**Comment by zarutian** [comment]
Hmm... facets are often made as an composition pattern over varSlots (E term) or other such state bearing things. State bearing thing might be an VO which is only accessible via reference in a captured environment inside a closure.
I think I am seeing an object graph pattern here that might be working against the intent behind VOs and their supporting mechanism by only allowing the VOs to be 'paged out'. Perhaps we need a better way to make ephimerability of VO Representitives accessible, perhaps marked-boundary-transivitly, to both support the usual easy faceting pattern above and 'page out'-ability of seldom visited state&objects.

**Comment by katelynsills** [comment]
A few things to keep in mind for further discussion of this topic:

### Definition of "use facets"

"Use facets" are about access control. Specifically, Alice desires to give Bob access to something, but only if Bob can prove that Bob is the current owner of particular ERTP assets. For example, the pixel demo had NFTs which represented particular pixels on a webpage using `x,y` coordinates. Bob might have a purse with an `amount.value` of `[{ x:0, y:1}, {x:3, y:7}]`. In the pixel demo, Alice wanted to only allow the current owner of an ERTP asset pixel, say `{x:0,y:1}`, to be able to change the color of the pixel.

### ERTP assets are abstract concepts

ERTP assets are abstract concepts, and are not reified directly in Javascript objects. In the above example where Bob owns two pixels which are stored in a purse, the ability to change the color of the pixels needs to follow the pixels, not the purse. Payments are even more ephemeral. So for example, if Bob has a payment containing his two pixels, and colors these pixels, he needs to maintain the ability to color them even if he `claims` his payment (thus producing a new payment object with the same ERTP assets and killing the old payment). Same thing if he splits up his payment into a payment per pixel or combines his payment with another one. The bottom line is, payments and purses will come and go, and the use facet needs to track the ERTP assets, not the JavaScript objects that are said to "hold" the abstract ERTP assets.

### The implementation of ERTP assets

The "balance" of an ERTP purse is an amount stored as state within a hardened purse object. The "balance" of a payment is stored in the `paymentLedger`, a weakStore which maps payment objects to amounts. We cannot change payments to store the balance within the payment objects like purses do, because the user must not be able to get the balance from the payment object itself. (Payments are often sent by other users and should not be trusted to report their own balance. It'd be a major foot-gun usability issue if users could get the balance of a payment by asking the payment.) We should keep this in mind when thinking about virtual objects, because for payments, use facets need to track information stored outside the object.

### Use Facets are Bundles of Rights

When figuring out how to implement use facets, we need to think about the economic/property rights implications as well. For example, when Alice wants to give Bob the ability to change the color of a pixel but only if he's the owner of the pixel, did Alice create the pixel NFT? Or is she creating a new property right associated with the NFT, which the original creator had not even imagined? Importantly, if Alice isn't the original creator, the original creator has no say over this new usage of the NFT they minted. It's up to Bob and the other owners of the ERTP assets whether they want to engage with Alice's use facet or not. 

If we want to encourage economic activity on chain, we may want to encourage innovation in "use facets" for already existing NFTs. In order to do this, the technical implementation should allow use facets to be created after the ERTP assets exist, and moreover the use facet should be able to be created by someone who did not create the associated ERTP assets.

This also benefits creators of assets who only realize that they want to create use facets after the ERTP assets are minted.

### Why escrow of the ERTP assets is often necessary 

Importantly, because ERTP assets are transferrable, it is not enough that Bob proves at single point in time that Bob has ownership. Bob must prove that he is the owner for the entirety of the time in which Bob wants to use Alice's resource. Otherwise, Bob can provide the "proof" to Alice, transfer the ERTP assets to Carol, and Carol can potentially do the same. If the assets are fungible, there's no way that Alice would know that Carol has used the same tokens as Bob. Thus, unless ERTP assets are escrowed, there's a potential attack in which both Bob and Carol both use the same resources against Alice's wishes. 

As a concrete example, imagine that the ERTP asset is a fungible ticket for a football game, and Alice wants to hold a pre-game event but only for people who have access to the football game. The attack would allow Bob to enter Alice's event, then transfer his ticket to Carol, who also gets to enter Alice's event, even though they only have one ticket between them. 

### The benefits of "use facet" contracts

I wrote up an example (https://github.com/Agoric/agoric-sdk/blob/master/packages/zoe/test/unitTests/contracts/useObjExample.js) which shows how to achieve "use facets" with a contract on Zoe. Writing this as a contract has a number of benefits:

1. By using Zoe's escrow mechanism, it's easy to ensure that the use facet is only granted to the owner of the assets (i.e. the person who made the offer which escrows them). No additional mechanism of proof of ownership is necessary.
2. The use facet is only good for as long as the assets are escrowed, preventing the pre-game event attack mentioned above. 
3. No revocation of the use facet is necessary.
2. The use facet is not tied to a particular payment or purse, but rather the assets escrowed with an offer, which makes the association of the use facet with the abstract ERTP assets clearer than it might be otherwise.
3. Anyone can add a use facet for an already existing NFT. There is no need to create the use facet at the same time as the NFT.

The con is, and this is a big one:
1. Contracts are expensive in terms of data storage and execution, and we need to figure out how to improve.

There was a con that was mentioned in the Sept 8 Kernel meeting which I don't agree is a con: the contract code needing to check that the assets are still escrowed and the seat has not exited. We can easily write helpers or components for adding use facets so that those sorts of checks are under the hood.

**Comment by katelynsills** [comment]
If I understand correctly, this discussion of use facets is being driven by a desire to make vaults transferrable (issue here: https://github.com/Agoric/agoric-sdk/issues/3864). I'm not sure if we've decided what the company priority is for this task, but as far as I can tell, it's not necessary for Mainnet 1, 2 or 3.

**Comment by warner** [comment]
In today's meeting, we talked about:

We frequently want to create two facets that share state:

```js
function makeKit() {
  let counter = 0;
  const incrementer = Far('incrementer', {
    increment() { counter += 1; },
  });
  const decrementer = Far('decrementer', {
    decrement() { counter -= 1; },
  });
  return harden({incrementer, decrementer});
}
```

To virtualize this with our current virtual-object `makeKind` API requires *three* virtual objects: `A`, `B`, and a hidden inner object that holds all the power. In normal ocap terms, it would look like:

```js
function makeKit() {
  function makeInner() {
    let counter = 0;
    return Far('inner', {
      increment() { counter += 1; },
      decrement() { counter -= 1; },
    });
  }

  function makeIncrementer(inner) {
    return Far('incrementer', {
      increment() { inner.increment(); },
    });
  }

  function makeDecrementer(inner) {
    return Far('decrementer', {
      decrement() { inner.decrement(); },
    });
  }

  const inner = makeInner();
  const incrementer = makeIncrementer(inner);
  const decrementer = makeDecrementer(inner);

  return harden({incrementer, decrementer});
}
```

The actual `makeKind` code would look more like:
```js
const makeInner = makeKind('inner',
                           () => ({ counter: 0 }),
                           state => {
                             increment: () => { state.counter += 1; },
                             decrement: () => { state.counter -= 1; },
                           });
const makeIncrementer = makeKind('incrementer',
                                 inner => ({ inner }),
                                 state => {
                                   increment: () => { inner.increment(); },
                                 });
const makeDecrementer = makeKind('decrementer',
                                 inner => ({ inner }),
                                 state => {
                                   decrement: () => { inner.decrement(); },
                                 });
function makeKit() {
  const inner = makeInner();
  const incrementer = makeIncrementer(inner);
  const decrementer = makeDecrementer(inner);
  return harden({incrementer, decrementer});
}
```

We're calling this the "three-body solution" (thanks to @FUDCo).

It would be much nicer if the kind could define both facets at the same time, sharing the same state:
```js
const makeKit = makeKind('counter',
                           () => ({ counter: 0 }),
                           state => {
                             const incrementer = {
                               increment: () => { state.counter += 1; },
                             };
                             const decrementer = {
                               decrement: () => { state.counter -= 1; },
                             };
                             return { incrementer, decrementer };
                           });
```

Depending upon how we implement it, this might also help dodge a current (tricky) limitation of the virtual object GC code: it cannot collect cycles in virtualized data #4665. The three-body solution doesn't suffer from this, but another common pattern (with only two objects) would.

## Description of the Design

TBD. We know each facet is a separate Representative, created only as a group, closing over the same state.

Each facet needs a distinct vref, but maybe they can be related (share a prefix, plus a facet ID). The state needs an identifier (perhaps the prefix). GC might be easier if we declare that the sibling Representatives all reference each other (@erights suggested the VOM holds a WeakMap from each Representative to the set of their siblings). I think it's important that we either have all available in RAM, or none.

The finalizers will run at all sorts of interesting times, separately for each Representative (even if we know/hope that they'll all eventually fire once userspace drops it), which will be interesting.

## Security Considerations

should consider GC consequences, the main concern is preventing userspace from learning about GC

## Test Plan

tricky unit tests

**Comment by erights** [comment]
(Could you change the appropriate `harden`s above into `Far`s? Thanks.)

**Comment by erights** [comment]
If we have a weakmap from each representative to their common kit, then we only need to detect finalization on the kit. We wouldn't need any further instrumentation per representative.

To prevent mischief, this could be to a copy of the kit record that we make up front, ensuring a fresh identity.

**Comment by FUDCo** [comment]
> If we have a weakmap from each representative to their common kit, then we only need to detect finalization on the kit. We wouldn't need any further instrumentation per representative.
> 
> To prevent mischief, this could be to a copy of the kit record that we make up front, ensuring a fresh identity.

That is where my thoughts were going as well.  I'm leaning towards thinking that implementing this API would actually be pretty simple (not as simple as adding the finisher function was, but few things are). Of course, this is pending deeper discussion among ourselves of all the different ways we could get into trouble, the evasion of which problems might complicate things.

**Comment by warner** [comment]
Ok @FUDCo and I think this is doable. @erights please proceed with the "three-body" approach for now, since that should be straightforward to transform into this multiple-facet approach.

Design questions:
* we currently capture the set of `state` properties during `initialize()` separately for each virtual object (instance 1 could have `.foo, .bar`, but instance two might have just `.foo`, which is flexibility that would e.g. make creating a real DB schema difficult. To prohibit this, we'd need to either require the user to provide the list of properties to the `makeKind` call, or wait until the first instance was created and then remember the set of properties it created (which would force a real DB schema to wait until the first instance, ugh).
* Similarly, should we allow different invocations of `actualize` to return different sets of facets? If not, we need to do the same sort of wait-for-first-instance thing. I'm not inclined to allow different facets per instance, but I'd change my mind if it made the implementation difficult.
* @FUDCo mentioned that it would be good if one facet could conveniently get access to the other facets, to avoid encouraging user code from e.g. building the facets separately and capturing references to each other. Any time a facet exists as a named object within `actualize`, there will be a temptation to do something with it, and these facets are not yet serializable, so we want to reduce that temptation.
  * we might define `actualize(state, getFacet)` and ask authors to use `getFacet(facetName)` from within the methods of `otherFacetName`
  * we could make `getFacet` ambient, and have them do `getFacet(state, facetName)`
  * or we could put some magic property on `state` to avoid colliding with user-provided data, e.g. `state[Symbol.for('getFacet')]`

Internally:
* `actualize` will return either a single Representative (single-facet) or a cohort of named Representatives (multi-facet)
  * named, rather than an array of Representatives, because that makes things self-documenting and less likely to e.g. accidentally swap the powerful and less-powerful objects
* define a "cohort record" as an array or record with all the Representatives that share common state
  * the goal is for all members of the cohort to live and die at the same time
  * either we populate a WeakMap (a real WeakMap, not our vref-aware replacement) to map from Representative to cohort record, or we make the `state` object capture the cohort record (which must then be mutable until `actualize` returns and the cohort can be populated)
* we'll add another layer to the vref hierarchy
  * normal ("precious" / `Far()`-created) objects get `o+NN`
  * existing virtual objects get `o+NN/AA`, where NN is the kind ID, and AA is the instance
  * the new multi-facet virtual objects will get `o+NN/AA/BB`, where AA is the cohort ID and BB is the facet ID
    * BB might be numerical, which keeps the vrefs shorter, but requires a table somewhere, and if each cohort can have a different set of facets, that table must be kept on disk
    * BB might be a string (identical to the facet property names in the record returned by `actualize`), which makes vrefs longer and to be safe requires some limitations on facet names
* `valToSlot` continues to be a WeakMap from each individual facet Representative to the `o+NN/AA/BB` vref
* `slotToVal`, currently a Map from vref to a WeakRef to the Representative, changes
  * for multi-facet vrefs, the WeakRef target is the cohort record, not the individual Representative
  * `convertSlotToVal` is changed to examine the type of vref going in. Most types continue to use `slotToVal.get(vref).deref()`. But multi-facet vrefs use `slotToVal.get(`o+NN/AA`).deref()[BB]`: fetch the whole cohort, then pull out the specific facet
  * if `slotToVal` has a miss, or the WeakRef is empty, call `actualize` to create a brand new cohort, populate `slotToVal`, then pull out the specific facet
* GC for multi-facet virtual objects needs to be performed at the cohort level, not the representative
  * when adding a facet into some other virtual object, the `state` setter currently uses the full vref to indicate the refcount to be incremented, causing a `vatstoreSet('vom.rc.${vref}')`
  * this needs to change, for a multi-facet vref `o+NN/AA/BB`, we want to touch `vom.rc.o+NN/AA`
  * we need to handle the surjective mapping from full vref to cohort ID properly: if a single virtual object property references two facets of a cohort, does it count as two separate refcounts, or just one? Whichever we pick is fine, but it must be handled the same way on both increment and decrement.
  * #4667 self-reference cycle pruning needs to be aware of this mapping

**Comment by mhofman** [comment]
> It would be much nicer if the kind could define both facets at the same time, sharing the same state:
> 
> ```js
> const makeKit = makeKind('counter',
>                            () => ({ counter: 0 }),
>                            state => {
>                              const incrementer = {
>                                increment: () => { state.counter += 1; },
>                              };
>                              const decrementer = {
>                                decrement: () => { state.counter -= 1; },
>                              };
>                              return { incrementer, decrementer };
>                            });
> ```

I am wondering what the impact of this approach is on garbage collection.

First in this example, how does `makeKind` know that `incrementer` and `decrementer` would be the virtual objects?

In this example, neither object has a reference to the other one. Let's assume we have instead `foo` and `bar`, and that `foo` has a `getBar()` method which returns `bar`. Now assume that `foo` is exported, that the contract doesn't hold the local representative for `foo`, but that it hold the local representative for `bar`. What should happen when `foo` is re-imported, and the contract calls `foo.getBar()`?

I think we could avoid those complications, and steer the contract code to only entangle objects through the state object, if the paired objects were defined independently. For example, maybe we could have an independent `makeKindInit`, and pass the return value to `defineKind`'s `init`. That would require some logic so that `defineKind` cannot be called to associate new objects to a state after an instance has been created.

```js
const counterInit = makeKindInit("counter", () => ({ counter: 0 }));

const makeIncrementer = defineKind("incrementer", counterInit, (state) => ({
  increment: () => {
    state.counter += 1;
  },
}));

const makeDecrementer = defineKind("decrementer", counterInit, (state) => ({
  decrement: () => {
    state.counter -= 1;
  },
}));
```

So that objects can access each other, we could imagine a second argument besides `state` or maybe a way to access the other object through the `state`?

**Comment by FUDCo** [comment]
> First in this example, how does makeKind know that incrementer and decrementer would be the virtual objects?

The virtual objects are whatever was returned by the actualizer function.

> So that objects can access each other, we could imagine a second argument besides state or maybe a way to access the other object through the state?

Yes, this is already on the agenda to discuss.  Reread @warner's comment above.

**Comment by warner** [comment]
> > It would be much nicer if the kind could define both facets at the same time, sharing the same state:
> > ```js
> > const makeKit = makeKind('counter',
> >                            () => ({ counter: 0 }),
> >                            state => {
> >                              const incrementer = {
> >                                increment: () => { state.counter += 1; },
> >                              };
> >                              const decrementer = {
> >                                decrement: () => { state.counter -= 1; },
> >                              };
> >                              return { incrementer, decrementer };
> >                            });
> > ```
> 
> I am wondering what the impact of this approach is on garbage collection.
> 
> First in this example, how does `makeKind` know that `incrementer` and `decrementer` would be the virtual objects?

Every property of the `actualize(state)` return value is a separate facet, and gets a separate (but related) vref, and a distinct Representative.

> In this example, neither object has a reference to the other one. Let's assume we have instead `foo` and `bar`, and that `foo` has a `getBar()` method which returns `bar`. Now assume that `foo` is exported, that the contract doesn't hold the local representative for `foo`, but that it hold the local representative for `bar`. What should happen when `foo` is re-imported, and the contract calls `foo.getBar()`?

Right, that's what the "@FUDCo mentioned that it would be good if one facet could conveniently get access to the other facets" comment was about. The "cohort object" I wrote up makes sure that all the related Representatives are in RAM, or none of them are, and if any one of them is exported, then all the vrefs are kept alive. The refcount is on the cohort, not the individual vrefs.

So if `foo` is exported but userspace drops all references to `bar`, liveslots still knows about the Representative (there's a slot-to-val-to-cohort-to-facet path by which liveslots can reach it). We need a way for the `foo` code to follow that path, of course. But it could either be the games we want to discourage, or a specific function that we offer to foo and bar to get each other when they need it.

> 
> I think we could avoid those complications, and steer the contract code to only entangle objects through the state object, if the paired objects were defined independently. For example, maybe we could have an independent `makeKindInit`, and pass the return value to `defineKind`'s `init`. That would require some logic so that `defineKind` cannot be called to associate new objects to a state after an instance has been created.

That might work, I'd have to think about it more. But I'm worried about GC: if the different facets can be GCed independently, then I think things are going to get complicated. The VOM really needs to know that the 

> ```js
> const counterInit = makeKindInit("counter", () => ({ counter: 0 }));
> 
> const makeIncrementer = defineKind("incrementer", counterInit, (state) => ({
>   increment: () => {
>     state.counter += 1;
>   },
> }));
> 
> const makeDecrementer = defineKind("decrementer", counterInit, (state) => ({
>   decrement: () => {
>     state.counter -= 1;
>   },
> }));
> ```

It feels like there's a spectrum from the three-body solution, to degenerating the "inner" object to become all state and no behavior, to defining both state (`initialize()`) and behavior (`actualize()`) at the same time. Your example is slightly closer to the three-body end.
 
> So that objects can access each other, we could imagine a second argument besides `state` or maybe a way to access the other object through the `state`?

Yeah, I think that would wind up looking a lot like the cohort design I wrote up above.

**Comment by mhofman** [comment]
> Reread @warner's comment above.

> Yeah, I think that would wind up looking a lot like the cohort design I wrote up above.

Sorry I had missed the part about how to get references to other facets.

What I'm still confused about is why would users go for that explicit mechanism instead of using direct references in their code if the pattern we're offering already has the objects in scope in the actualizer. Basically, in what cases do we actually need that mechanism?

> But I'm worried about GC: if the different facets can be GCed independently, then I think things are going to get complicated

Right, I think I had originally missed that each representative would keep each other alive through a WeakMap, which prevents resurrection problems. I guess that's an alternative approach that simplifies the lifecycle of representatives.

> It feels like there's a spectrum from the three-body solution

I guess the tension for me is that I'm still struggling with the object as closure pattern for high cardinality things, and I keep thinking in terms of internal state with "pure" behavior interface attached. So my intuition was to define the state separately from the facets and link them together.

**Comment by FUDCo** [comment]
> What I'm still confused about is why would users go for that explicit mechanism instead of using direct references in their code if the pattern we're offering already has the objects in scope in the actualizer.

Yes, this is a concern I've had as well.  If there's both a safe way to do something and a dangerous way to do the same thing, and both appear equally available, that's probably a bad place to be.

**Comment by warner** [comment]
>     * @FUDCo mentioned that it would be good if one facet could conveniently get access to the other facets, to avoid encouraging user code from e.g. building the facets separately and capturing references to each other. Any time a facet exists as a named object within `actualize`, there will be a temptation to do something with it, and these facets are not yet serializable, so we want to reduce that temptation.

@erights @FUDCo and I decided that we don't need this mechanism. Because all the facets of a cohort share a lifetime, and because we retain the identity of the objects returned by `actualize()` through to the return value of `makeFoo()`, the behavior code in `actualize` can give a name to those objects before returning them, and capture that name in their behavior:

```js
function actualize(state) {
  const facets = {
    incrementer: { increment() { state.count += 1; } },
    decrementer: { decrement() { state.count -= 1; } },
    both: {
      getIncrementer() { return facets.incrementer; },
      getDecrementer() { return facets.decrementer; },
    };
    return facets;
}
```

The cohort of Representatives will then hold strong references to each other (`both` captures `facets`, which points to `incrementer`, and there's nothing preventing `incrementer` from also capturing `facets`, causing a reference cycle, but it's in RAM so the JS engine can deal with it). These strong references augment whatever the VOM prepares to make sure the cohort lives and dies as a group.

We decided there isn't a major risk to encouraging authors to use this pattern; the concern was that by naming `facets` and `facets.incrementer`, authors would be tempted to e.g. pass this proto-Representative to someone else before the VOM saw it and was able to register it in `valToSlot`. We figured out this part earlier: nobody else can serialize the proto-Representative because it isn't hardened (the VOM does the `Far`/`harden` call itself, after `actualize` returns) and serialization requires hardening. If either the author of `actualize` or someone they prematurely share the proto-Representative hardens it, the VOM will throw as it attempts to perform a duplicate `Far`, and the Representative won't be assigned a vref (assuming this was building the initial representatives).

(Of course, the VOM must call `Far` on the proto-representative every time it calls `actualize`, regardless of whether it intends to use those representatives or throw them out).
