### ISSUE TITLE
Interest rate changes should affect existing vaults

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#4182]
## What is the Problem Being Solved?

When governance changes an interest rate, is that supposed to apply to existing vaults? current code says no.
@rowgraus suggests market expectation is yes.
@dtribble notes fixed interest rates facilitates some optimizations (O(1) interest calculation, read-only optimizations, ...)

## Description of the Design

not clear

## Security Considerations

?

## Test Plan

?

**Comment by Chris-Hibbert** [comment]
We'll eventually want vault customers to think of the rates as variable, since having consistent rates across all vaults makes it possible to have O(1) updates and simplifies having read-only (i.e. off-chain) requests for the current debt.   It will be easier to make that change before there are any customers, we should do this soon.
