### ISSUE TITLE
Set Up Automated Dapp Testing

### ISSUE THREAD

**Issue by samsiegart** [Agoric/Agoric#4241]
## What is the Problem Being Solved?

We currently have a manual dapp testing [process](https://github.com/Agoric/agoric-sdk/blob/master/.github/ISSUE_TEMPLATE/manual_dapp_testing.md). This leaves significant risk that changes to the sdk break dapps unknowingly, and increases the time required to catch those breakages.

## Description of the Design

Webdriver tests should be set up to do the following for each dapp:
- Start up a local agoric instance
- Deploy the dapp contracts to the local instance
- Launch the dapp ui in a headless browser (puppeteer/headless-chrome should likely suffice for this)
- Launch the wallet ui in a headless browser
- Automatically test the user journeys specified in https://github.com/Agoric/agoric-sdk/blob/master/.github/ISSUE_TEMPLATE/manual_dapp_testing.md

## Test Plan

TBD: Whether these tests should be run from within the sdk / as part of CI

**Comment by mhofman** [comment]
We already have 2 components which automatically test a dapp deployment: the loadgen runner (since the loadgen is currently built as a dapp), and `agoric-cli`'s `getting-started` integration test. Neither of those test any UI however. It might be good to think about what it'd take to avoid yet another runner implementation which coordinates launching and monitoring multiple services.
