### ISSUE TITLE
TimerService device stores repeaters in an ever-growing array

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4286]
## Describe the bug

The [TimerService stores repeaters](https://github.com/Agoric/agoric-sdk/blob/f5995854229921788d94caa97107360130085e61/packages/SwingSet/src/devices/timer-src.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L211) in an array that grows without bound. When repeaters are deleted, they are replaced in the array with null, so that indexing is preserved.

## Vulnerability

Clients can create repeaters at low cost (particularly if they delete them quickly), but this causes the timer to grow the repeaters array to an arbitrary size.

This an issue for Zoe and other core services that rely on timers.

## Expected behavior

Memory use shouldn't grow like that.

## Additional context

Identified during the Zoe Purple team exercise

**Comment by zarutian** [comment]
/me thinks about if and how #3612 would fare in this context. Perhaps it would only be the same issues that Notifiers and Subscriptions have?

I think this is mainly an implementation spefic issue.

**Comment by warner** [comment]
With the closing of #5668, the timer *device* still suffers from this problem, but users no longer get access to it. The new timer *vat* [stores Repeaters as virtual objects](https://github.com/Agoric/agoric-sdk/blob/130feae4b0341bd8ea17569837376481dfa82f1b/packages/SwingSet/src/vats/timer/vat-timer.js#L699-L703) so they no longer consume RAM, only DB, and they should be deleted automatically when unreferenced and unscheduled.

I'll close this ticket now, because the core problem is resolved, and our next step will be to replace the timer device with a stripped down version that has no Repeaters at all, only a single wakeup that vat-timer uses to implement everything else.
