### ISSUE TITLE
Remove `waived` exit type

### ISSUE THREAD

**Issue by dtribble** [Agoric/Agoric#4288]
## What is the Problem Being Solved?

The `waived` exit strategy is not actually used anywhere. It's easily subsumed and explained using simply a long deadline.  And supporting it will require additional implementation.  Consider removing support for it.

## Description of the Design

Remove the option in Zoe's `offer`.

## Security Considerations

This should simplify key areas of the system.

## Test Plan

Remove any relevant tests.

**Comment by erights** [comment]
On reflection, I'm uncomfortable with this, so assigned myself for now.

**Comment by erights** [comment]
> easily subsumed and explained using simply a long deadline
But deadlines are always relative to a designated timer. Waiving should not require one to provide access to a timer. We could introduce the `neverTimer` that never goes off. But is this simpler than simply keeping waived?

The reason we're uncomfortable with waived is, if escrowing gets stuck because of an unresponsive issuer, we don't want the assets from the remaining issuers to remain inaccessible. One thought (which I no longer like) is that deadline-based proposals stay stuck until the deadline expires. But that wouldn't help waived-exit proposals. But it would also not help infinite-dealine proposals, so removing waived doesn't solve anything anyway.

The current plan is to honor `tryExit` during the escrowing phase, if the signal is received before escrowing completes.

**Comment by erights** [comment]
> The current plan is to honor `tryExit` during the escrowing phase, if the signal is received before escrowing completes.

That doesn't make sense in our current system, since the offerer doesn't get a seat until escrowing completes, and therefore cannot try to exit within the current API before escrow completes. The real concern that would try to address is the payout liveness explained at https://github.com/Agoric/agoric-sdk/issues/1271 . So closing this issue as subsumed by that one.
