### ISSUE TITLE
Chain halt: `E(agoric.chainTimerService).setWakeup(0, "banana")`

### ISSUE THREAD

**Issue by b4d2** [Agoric/Agoric#4297]
## Describe the bug
Calling `E(agoric.chainTimerService).setWakeup(0, "banana")` results in a chain halt

## To Reproduce
1. start chain: `agoric start local-chain --reset`
2. start solo: `agoric start local-solo --reset`
2. open repl: `open -a "Google Chrome" $(agoric open --repl --no-browser | grep http)`
3. wait for chain to boot
4. Issue `E(agoric.chainTimerService).setWakeup(0, "banana")`
5. The chain will stop due to the following stack

```
2022-01-14T00:22:57.821Z block-manager: BEGIN_BLOCK error: (Error#1)
Error#1: error in devicePollFunction: (Error#2)

  at Object.poll (packages/SwingSet/src/devices/timer.js:28:14)
  at beginBlock (packages/cosmic-swingset/src/launch-chain.js:291:32)
  at kernelPerformAction (packages/cosmic-swingset/src/block-manager.js:48:13)
  at blockManager (packages/cosmic-swingset/src/block-manager.js:225:19)
  at toSwingSet (packages/cosmic-swingset/src/chain-main.js:307:12)
  at portHandlers.<computed> (packages/cosmic-swingset/src/chain-main.js:121:22)
  at Object.fromGo (packages/cosmic-swingset/src/chain-main.js:138:31)

Nested error under Error#1
  Error#2: SO(x) must be called on a Presence, not undefined
  
    at SO (.../swingset-vat/src/kernel/deviceSlots.js:136:5)
    at eval (.../swingset-vat/src/devices/timer-src.js:189:11)
    at Array.forEach (<anonymous>)
    at poll (.../swingset-vat/src/devices/timer-src.js:178:19)
    at poll (.../swingset-vat/src/devices/timer-src.js:256:12)
    at Object.poll (packages/SwingSet/src/devices/timer.js:26:22)
    at beginBlock (packages/cosmic-swingset/src/launch-chain.js:291:32)
    at kernelPerformAction (packages/cosmic-swingset/src/block-manager.js:48:13)
    at blockManager (packages/cosmic-swingset/src/block-manager.js:225:19)
    at toSwingSet (packages/cosmic-swingset/src/chain-main.js:307:12)
    at portHandlers.<computed> (packages/cosmic-swingset/src/chain-main.js:121:22)
    at Object.fromGo (packages/cosmic-swingset/src/chain-main.js:138:31)
  
portHandler threw (Error#1)

4:22PM ERR CONSENSUS FAILURE!!! 
```
## Expected behavior
Calling setWakeup with invalid arguments should not result in a chain halt

## Platform Environment
 - what OS are you using? what version of Node.js?
 macOS 12.1, node v16.13.1
 - is there anything special/unusual about your platform?
 I only have 16gb of ram
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
`72cc8d6bcf428596653593708959446fb0a29596`

ref #4264

**Comment by warner** [comment]
Looks like the timer device doesn't (perhaps has no means to) validate that the callback object it received was really a Presence, and not a string. And the wrapper vat didn't perform the validation either.

So far, each device is paired with a vat, and we've made the vat responsible for protecting the device against unexpected usage. I'm guessing `agoric.chainTimerService` points at the wrapper vat, but this `setWakeup` pathway delegates to the device's `setWakeup` method.

The actual error happened during `beginBlock`, when cosmic-swingset tells the timer device that time has passed. This happens between cranks, outside any vat-sourced message delivery. So while the bananas client vat was the root cause, and the timer wrapper vat could have caught the invalid callback object earlier, the actual crash is not directly correlated to any particular vat. The mailbox device has a similar point, where it accepts messages from the outside world and pushes run-queue events to notify vattp about them.

In this case, I think crashing the kernel and halting the chain is probably the right thing to do. The alternative would be to catch and log (and thus effectively ignore) errors happening in the device that aren't within the context of some vat invoking it. Doing that would cause some number of chain inputs to get ignored, probably persistently, which would leave the chain in a half-functioning state. The symptoms would be that timed events didn't happen, or (for the mailbox device) some subset of inbound messages get ignored. Plus a log message that probably wouldn't be very visible.

The fixes I can think to make are:
* the wrapper vat should validate enough about the argument it receives to make sure the device invocations it makes (or the subsequent non-invocation-context work, like beginBlock) won't ever cause an error: signal the error as early as possible
* maybe catch+log errors in externally-driven device calls, at the risk of concealing errors that really ought to be addressed

Thinking about chain upgrade/repair options, once the timer vat gets into this situation, it's kinda sticky. If we wanted to fix this without completely restarting the chain, we'd want to restart the kernel with a different device implementation, one which quietly deletes wakeups when they get an error doing the `sendOnly` to the callback object.

**Comment by Tartuffo** [comment]
@michaelfig assigned this to you, per @FUDCo's suggestion.

**Comment by michaelfig** [comment]
I punt to @Chris-Hibbert who implemented the TimerService.

**Comment by Chris-Hibbert** [comment]
@warner is there a function the timer device could call that would tell it whether a handler is a presence? [device-timer.js](https://github.com/Agoric/agoric-sdk/blob/4ce04cd1faa59f922ff3a204cd4c1001c9a9ed87/packages/SwingSet/src/devices/timer/device-timer.js#L172) calls `SO(handler).wake(time)`, and [SO](https://github.com/Agoric/agoric-sdk/blob/dda33c031cdf1c0f685ce9ecd3c9de8a36ea49ee/packages/SwingSet/src/kernel/deviceSlots.js#L135) says "SO(x) must be given a presence, not a promise that might resolve to a presence."

Throwing or returning an error from the timer device or the timer vat would be better than failing an assert in the kernel.

**Comment by warner** [comment]
stealing this one, I have half a fix in a branch
