### ISSUE TITLE
Implement linear fee structure (free for small / getRUN)

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4402]
## What is the Problem Being Solved?

@dtribble points out that we need folks to have RUN before they can do anything at all, how do they get started?

**Comment by JimLarson** [comment]
Some previous ideas:

For people transferring in assets: make available on exchanges on the other side of our IBC links - anyone who transfers assets in can also buy some RUN to transfer in as well.

For those with BLD from the public sale: send us a signed txn requesting RUN via getRUN and we'll transfer some minimal RUN into your account and submit the txn on your behalf. We keep a record - you only get one donation.

**Comment by mhofman** [comment]
@erights just suggested that an option to allow charging fees in RUN while not requiring run for simple operations (what would be needed to get started), yet still protect against abuses, is to have non linear fees and make sure the initial activity triggers 0 fees somehow. Did I get that right?

**Comment by Tartuffo** [comment]
@rowgraus @dtribble Thoughts on who this should be assigned to?

**Comment by dckc** [comment]
@rowgraus @Tartuffo @Chris-Hibbert @dtribble @michaelfig @JimLarson @turadg @warner I'll start with the following proposal (that includes 2 or 3 design options):

## 1. Start with no fees?

> @dtribble points out that we need folks to have RUN before they can do anything at all ...

Do we? I think he has at other times pointed out that other zones (osmosis?) have gone for quite some time with zero fees.

Our prices are subject to cosmos governance; we could start them at 0.

**cost:**
 - ~0 if we're already confident that the current design works end-to-end. Change all the default values to 0.
 - 1 to 2 chunks to manually test changing the parameters by cosmos governance once
 - 3 to 5 chunks to add an automated integration test

### Test migration from 0 fees to >0 fees

If we go with 1, we should be confident that when we need it, we can change the fee multiplier to something >0

## 2.a 0 fee for small / ordinary transactions, >0 for large

Just to re-iterate the suggestion above https://github.com/Agoric/agoric-sdk/issues/4402#issuecomment-1022747241 , we could take the size * K formulas from #3935 and tweak them slightly to max(0, size * K + b) where b < 0, so that small / ordinary transactions don't require any RUN. This way, we would not need a governance decision to make it expensive to send unreasonably large messages.

**cost**: 2 chunks (un-interrupted 1/2 days) to
 1. gather info to decide what b should be in each case
 2. add `+ b` to the relevant parts of the go code

This assumes b need not be subject to governance change. If it does, then add another 1/2 day chunk for JS coordination.

### 2.b Non-linear fees

The suggestion above actually says "non-linear", so the formula would be could like max(0, size ** K + b).

**cost:** 2-3 chunks to do 2.a plus convert the linear factors into exponentials and to figure out how to do the relevant exponentiation with integers.

### Background: Docs for current design?

I'm struggling to find a concise statement of our current design. I think it comes from #3935, though that doesn't include a summary, nor does the issue it comes from, #3752. I'm basing my understanding mostly on...

https://github.com/Agoric/agoric-sdk/blob/27271cd98859900e102a1c7b083218571c16a146/packages/cosmic-swingset/src/sim-params.js#L37-L40

**Comment by Tartuffo** [comment]
Decision: Implement with a linear fee structure for MN-1, where b is negative so that getRUN messages are free.

**Comment by dckc** [comment]
@michaelfig mentioned that the relevant code is in golang, so I suppose he and/or @JimLarson are the ones to take this on.

**Comment by Tartuffo** [comment]
@michaelfig @JimLarson Which one of you should be the primary assignee on this ticket?  Or should we have two tickets, one for each of your parts of the work?

**Comment by Tartuffo** [comment]
@JimLarson Changed the scope of this to implementing the linear fee structure at the Cosmos level, and assigned to you.

**Comment by Tartuffo** [comment]
We decided we will turn on admission fees in ag0 before launch, payable in multiple currencies (uBLD, uIST, uATOM).  Therefore, we will move this ticket to MN-1.1.

**Comment by dckc** [comment]
@Tartuffo help me find the issue for turning on admission fees? IIRC, some code changes are needed. @michaelfig gave @JimLarson some clues about which ones.

**Comment by Tartuffo** [comment]
Deferring this issue in favor of #5817.  FYI @dckc.

**Comment by dckc** [comment]
we went with an alternative:

 - #6157
