### ISSUE TITLE
`yarn lint` in agoric-sdk failing with mysterious error

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#4440]
Doing a `yarn lint` at the top, I got

![image](https://user-images.githubusercontent.com/273868/152250971-871155ad-e1d0-4703-bd84-bc5593df2bf6.png)

The only mention of "lint:format" seems to be https://github.com/Agoric/agoric-sdk/blob/f5be67f6e5c0d5a01aca66256502e2c453e128ae/package.json#L85

It isn't referenced from any other rule, and I didn't invoke it. The wallet-connection is the last item mentioned in "workspaces" and it seemed to succeed, so the overall `yarn lint` should have succeeded.

**Comment by erights** [comment]
On latest master:

![image](https://user-images.githubusercontent.com/273868/152420743-0ce216b5-3814-418f-a5df-2389e477af00.png)

**Comment by mhofman** [comment]
@turadg looks like prettier is not excluding `code_coverage`. I think we really need a `.prettierignore` file.

**Comment by turadg** [comment]
> I think we really need a .prettierignore file.

Agree! That's why we have one at  https://github.com/Agoric/agoric-sdk/blob/master/.prettierignore ;-)

It has a "build artifacts" section and I didn't know about `lcov-reports` when I listed them. PR to add https://github.com/Agoric/agoric-sdk/pull/4445

**Comment by turadg** [comment]
After merging #4445 I wondered why the check failed above but not in CI. I added an exclusion for `lcov-report` because I thought we might have a directory called `coverage` but I see in `.gitignore` it's blocked. Same for `bundle-*` that shows up above.

I'm going to merge https://github.com/Agoric/agoric-sdk/pull/4330 today and I'll add exclusions for those to match .gitignore. No sense in prettying what doesn't go into the repo.

**Comment by mhofman** [comment]
Probably because @erights at some point ran coverage locally, and since it's in `.gitignore` it's laying around unnoticed. I regularly deep clean my local repo, so never run into such issues. CI doesn't either because those tests likely use different runners.

That said +1 for `.prettierignore` being a superset of `.gitignore`
