### ISSUE TITLE
walletFactory uses virtual objects

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#4489]
## What is the Problem Being Solved?

Wallet manager and individual wallet backends need to be scalable.

## Description of the Design

Do the wholesale migration of the wallet backends to collections of virtual objects.

**Comment by Tartuffo** [comment]
@michaelfig Do you want this to be under the #3995 (as it is currently) or #4511 (which is the epic for all of the other virtual objects / collection work)?

**Comment by Tartuffo** [comment]
This work might get subsumed fully or partially by #4484, or at least much lest work.

**Comment by Tartuffo** [comment]
Wallet Manager is deprecated, so do we still need to do this?

**Comment by warner** [comment]
We need to measure the slope: RAM used per provisioned account, and also GC time (because that scales with the size of the object graph, hence RAM). Then we can compare that against the 2GiB per-vat limit (#5953) to estimate how many users can be added before the worker would be killed by the memory limit, and then since it is (supposed to be) a `criticalVat`, the kernel panics and the chain halts.
