### ISSUE TITLE
Make `amm.addPool` require initial assets

### ISSUE THREAD

**Issue by dtribble** [Agoric/Agoric#4643]
## What is the Problem Being Solved?

Manage production of AMM pools. There needs to be a cost to it to prevent spamming and to ensure initial collateral.

## Description of the Design

* Move `addPool` to a separate contract invitation that charges a fee and requires minimum initial collateral to create the pool
* The cost may be initial liquidity, which gets added to the Reserve.
* The initial cost and minimum liquidity need to be governance parameters.

## Security Considerations

Right now it's too easy and cheap to create pools.

**Comment by dtribble** [comment]
The initial cost and minimum liquidity need to be governance paramters.

**Comment by Tartuffo** [comment]
Should only happen when adding a new pool to the AMM.  addPool() should require, for example at least 1,000 RUN and some additional collateral. 

Some % (controlled by Gov) of the Liquidity Tokens should be held (by the Reserve) so the pool can't be completely drained to spam pools.  These LTs are an "minimum initial contribution"

**Comment by dckc** [comment]
## catch-22? How to initialize a new interchain asset?

The status quo is:
  1. Someone sets up an IBC channel and brings over some tokens; this fixes a cosmos level denom of the form `ibc/...long-hex-hash...`.
  2. The BLDer DAO authorizes the following:
      1. use `E(bankManager).addAsset(denom, ...)` (aka VBANK) to create an ERTP issuer (and make it widely known)
      2. `addPool` in the AMM using this issuer
      3. `addIssuer` in the reserve
      4. `addVaultType` in the vault manager, with a debtLimit of 0
   3. once the AMM pool has sufficient liquidity, the econ committee raises the debtLimit

The straightforward approach in #5377 requires funds at the `addPool` step. We tried taking that step out, but then `addIssuer` in the reserve fails, because the reserve turns around and asks the AMM for the relevant liquidity issuer.

Possible solutions include:

  - Separate what the BLDer DAO authorizes into 2 parts: (a) `E(bankManager).addAsset(denom, ...)` and (b) reserve `addIssuer` and the rest. Let market participants fund the AMM pool in between
    - **drawback**: 2 BLDer DAO votes
  - Allow `addPool` without funds as a privileged operation (on the AMM creator facet)
    - **drawback**: window for abuse between the time the pool is created and when the econ committee raises the debt limit? @rowgraus how much of a problem is that?
  - Move the constraint on minimum funds from pool creation time to the 1st time someone tries to add liquidity
     - **drawback**: development re-work
     - **drawback**: does not prevent creation of empty junk pools

### for reference

https://github.com/Agoric/agoric-sdk/runs/6481133158?check_suite_focus=true shows the failure.

We can also see it with...

```
yarn test test/test-gov-collateral.js -m 'assets are in AMM, Vaults'
...
Error#1: secondaryBrand not found: Object [Alleged: IbcATOM brand]...
  at getPool (.../run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js:152:45)
  at Alleged: publicFacet.getLiquidityIssuer (.../run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js:170:35)

Nested 2 errors under Error#1
    at Alleged: governedContract creator facet.addIssuer (.../run-protocol/src/reserve/assetReserve.js:49:41)
```
