### ISSUE TITLE
Expose key AMM economic data via subscription

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4648]
This data can be used in Blockchain Explorers and via sites like The Graph for the community to get key information about the state of the RUN Protocol components.

From [our meeting on Feb 22](https://docs.google.com/document/d/1HkNLG8Kmm9DV6XGxvZEGVWUtHli2OfkR5ph7Q77x3QE/edit#), here is the data we want to expose from the AMM:

1. All trading pairs, the algo for them
2. The pool amounts (X, Y, LP)
3. Trades as they occur
4. Liquidity change events (add, remove)
5. Governance parameters, contract terms, fees

**Comment by Chris-Hibbert** [comment]
AIUI, our theory is to publish states rather than events. My interpretation of that is that we'll have a separate stream of updates for each pool. It will publish the central and secondary balances in the pool and the amount of liquidity outstanding. These will be updated on every trade and liquidity event. A watcher can infer from this stream whether it's a response to a trade or liquidity change. 

We could also publish the fee balances, but since that isn't mentioned above, I'll leave it out for now.

I'll add a symbol for the algorithm, which will always be XY=K for now, and may eventually include "STABLE".

**Comment by dckc** [comment]
Should this stay open until the data are available via RPC?

If not, which issue represents the work to make the AMM data available via RPC?

**Comment by dckc** [comment]
Is it #5386 ? or #4331? should those be on the econ stress test release?

**Comment by turadg** [comment]
> Should this stay open until the data are available via RPC?

I think we agreed to decouple reading and writing, trusting in the Subscriptions abstraction. So the tickets for pushing the data to a subscription on the public facet aren't concerned with how it gets read.

> If not, which issue represents the work to make the AMM data available via RPC?
> Is it https://github.com/Agoric/agoric-sdk/issues/5386 ? or https://github.com/Agoric/agoric-sdk/issues/4331? should those be on the econ stress test release?

I don't know yet how the econ testers will get the data. However it is, yes it should be included as a release dependency. cc @Tartuffo

**Comment by Tartuffo** [comment]
Dan is working on a dashboard in a spreadsheet.

**Comment by dckc** [comment]
> So the tickets for pushing the data to a subscription on the public facet aren't concerned with how it gets read.

Well, the title of this issue says "via RPC" in so many words. If that's no longer the scope, let's change it.
