### ISSUE TITLE
[Governance]Using enum values as keys is incompatible with Jessie

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#4784]
## What is the Problem Being Solved?

We'd like our contracts to be written in Jessie. Jessie doesn't support using arbitrary computed property names. Parameter governance documentation encourages this with ` getLoanParams()[INTEREST_RATE_KEY]`.

## Description of the Design

The value of the enum is a constant string. If we turned them into keywords, Jessie could know enough to accept them as "not arbitrary".

We could maybe get TypeScript to carry the fact that they're keywords around, and this might help.

There are efforts to change the standard way we declare enums. If these turned the ENUM values into something that satisfied Jessie, that would also be a win. @turadg 

Governance could change the way that parameters are made available to sidestep the issue. I think having a method that took the enum value and returned a single governed param value would take care of this. I haven't investigated whether there were other considerations that drove the design here.

## Security Considerations

Maintain governance guarantees.

## Test Plan

Yes, test it thoroughly.

**Comment by turadg** [comment]
For governed params specifically, returning each value instead of the map would work.

For the more general case we could have an accessor function but that would introduce runtime overhead. @erights will Jessie fail if an object is indexed with a non-keyword key?  (i.e. a string where the leading character isn't uppercase). If so, we could rely on that and use a linter to give early feedback to the developer of what will happen at runtime.

**Comment by dckc** [comment]
This is fixed in #4806 , yes?

**Comment by Chris-Hibbert** [comment]
Yes.
