### ISSUE TITLE
decrementBy should precede incrementBy as a general safety habit

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4798]
We should search all of our code, and whenever incrementBy and DecrementBy are being used together, that it be in the correct order: xyz.incrementBy(seat.decrementBy(...)); 

MarkM can explain why this is important for offer safety.

What if instead we replace them with a transferBetweenSeats() ?

**Comment by erights** [comment]
Hi @Tartuffo the safety issue here isn't offer safety, and as I stated, is not any actual vulnerability for this code specifically. Rather the issue is to reenforce general safety habits rather than diminish them by habituating exceptions. To take your example, let's compare the increment-first pattern (which I don't like)
```js
seat.decrementBy(xyz.incrementBy(...));
```
with the decrement-first pattern (which I do like)
```js
xyz.incrementBy(seat.decrementBy(...));
```
Some reasons I like the decrement-first pattern better:

Say the decrement would cause the allocation to go negative. In the increment-first pattern, the increment gets staged before the decrement throws. This should not be an actual safety issue, as any code containing several incrementBy/decrementBy statements need to be prepared for later ones to fail after earlier ones caused stagings anyway. But it is a general hygiene issue. Other things being equal, better to fail before causing yet more side effects that need to be unwound.

Linearity is appealing in programming languages that support it, because it reflects physical intuitions about conservation of matter. In the decrement-first pattern, where are assets that have been removed by the decrementBy but not yet added to the incrementBy? They're in transit on the stack, on their way from the decremented seat to the incremented seat. After the incrementBy, there are no longer any such assets in transit.

I cannot form a similar physical intuition for where the conserved assets are between the incrementBy and decrementBy, except by introducing something like electron-hole pairs, which are hardly intuitive.

Were we ever to have lint tooling around linearity to catch mistakes, we could bring the decrement-first pattern under its watchful eye, but would need to exempt the increment-first pattern.

Finally, and most importantly, where the issue is habit formation comes rather than actual safety for this code:

In general, if I'm going to update some record in one place (`xyz`) the it has acquired more rights, and another place (`seat`) that it has lost the right that went to `xyz`, I will do these two operations in some order, but within some kind of atomicity framework ensuring that either both or neither happen. What if that atomicity framework fails after the first was done and before the second fails?

In the decrement-first pattern, assets disappeared, which usually causes only pain and benefits no one. In the increment-first pattern, assets appeared out of nowhere, forming a money pump, which immediately benefits one party, who would then be strongly motivated to induce this failure.

**Comment by Chris-Hibbert** [comment]
[`addLiquidity`](https://github.com/Agoric/agoric-sdk/blob/f3744012338f7362516098d72bfb7191acb2f3a7/packages/run-protocol/src/vpool-xyk-amm/addLiquidity.js#L147) in the AMM does a group of reallocations that are not paired, so it's not precisely the linearity case above, but as MarkM said above, "the decrement [might] cause the allocation to go negative." For general hygiene, this should group all the decrements before all the increments.

```
    const transferForTrade = (prices, incrementKey, decrementKey) => {
      seat.decrementBy(harden({ [incrementKey]: prices.swapperGives }));
      seat.incrementBy(harden({ [decrementKey]: prices.swapperGets }));
      feeSeat.incrementBy(harden({ RUN: prices.protocolFee }));
      poolSeat.incrementBy(harden({ [incrementKey]: prices.xIncrement }));
      poolSeat.decrementBy(harden({ [decrementKey]: prices.yDecrement }));
    };
```

The same kind of thing happens in `doublePool.js` and `singlePool.js`

**Comment by Tartuffo** [comment]
In yesterday's Zoe/ERTP meeting, @dtribble  proposed we add this convenience function: 
  `transfer(from, to, amount, keyword, secondKeyword)`
