### ISSUE TITLE
A user shouldn’t be able to unstake liened BLD, but can redelegate

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#4817]
A user shouldn’t be able to unstake liened BLD, but can redelegate

1. Mostly mitigated by 
2. And can’t borrow more until it’s redelegated

**Comment by JimLarson** [comment]
Mostly mitigated by ... the fact that the unstaked tokens are still encumbered and can't be transferred out of the account. The user is only hurting themselves by not staking.

**Comment by JimLarson** [comment]
The primary objection to this is the current `cosmos-sdk` limitation that after one redelegation, funds cannot be further redelegated until an unbonding period (around 3 weeks, I think) has passed. Normally, after having redelegated from validator A to validator B, unbonding is the only way to cease giving staking power to B and to avoid impact from B's future misbehavior.

Prohibiting unbonding then has two bad impacts: 1) the user is unwillingly vulnerable to future misbehavior from B for 3 weeks, and 2) since delegator choice in backing validators is the foundation of the security of the chain, removing that choice - hence giving a feckless validator temporary unrevocable power - undermines the overall chain security.

This is ameliorated by the fact that the user can choose to repay part of the loan and lower the liened collateral amount enough to be able to unstake  from the troublesome validator in question. Furthermore, a properly diversified account should spread its delegation across many validators, so the funds involved in a single validator should be limitated, making that repayment option more feasible. Lastly, we'd expect that redelegations would be directed towards more trusted validators, so the scenario of wanting to evacuate right after redelegation seems like a rare occurrence.

Nevertheless, I don't this this should be done, for the reasons above. Additionally, it would require new intrusions into `cosmos-sdk` that are unlikely to be upstreamed (for reasons above), and hence would be an ongoing maintenance burden for us. This guides my estimate for the work.

**Comment by JimLarson** [comment]
Previously resolved this with @rowgraus, who may wish to comment.

**Comment by rowgraus** [comment]
@JimLarson @Tartuffo yes this was resolved. The lien on BLD remains even if a user unstakes.

Per discussion in Token Economy meeting this issue should be deprioritized or removed.  Looks like it was

**Comment by Tartuffo** [comment]
This won't be an issue unless we allow unrestricted redelegation.

**Comment by btulloh** [comment]
This issue should be kept open as a post mainnet 1 issue. We need to have a design that avoids a situation where someone has an open loan but is not earning staking rewards.

**Comment by Tartuffo** [comment]
@btulloh Okay I re-opened it and put it in the Product Backlog.

**Comment by aj-agoric** [comment]
Closing as discussed. Will revisit as needed.
