### ISSUE TITLE
liveslots double-retires an import, causing vat-fatal error

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#4978]
While working on vat-upgrade, I discovered a bug in liveslots that can cause a vat-fatal error.

If a target vat has a method which takes an import and wraps it in a virtual object like this:
```js
const makeVir = defineKind('vir', arg => ({ arg }), ({state}) => {})); // holds state but no behavior
function acceptImport(presence) { // import is o-50
  const vir = makeVir(presence); // gets o+10/1
  // drop vir and presence, returning nothing
}
```

What happens is that we drop both the Presence (for the import) and the Representative (for the virtual object) at the same time. The two finalizers run and present both `o-50` and `o+10/1` to `deadSet` in the same `scanForDeadObjects` loop. The virtual object `o+10/1` is processed first, we find that the export and vdata pillars are gone too, and it is deleted. While deleting its data, we decref the import, causing `o-50` to be pushed onto `possiblyDeadSet`, and setting `gcAgain` (because we might also have released some in-RAM objects). Then the loop moves on to `o-50`, finds that it is not referenced, and schedules it for drop+retire by adding it to `importsToDrop`/`importsToRetire`.

We reach the end of the loop and find `doMore` is set (because of `gcAgain`), so we start the loop again. This time `deadSet` has `o-50` (again), which is still just as dead as before, and it gets re-pushed onto `importsToDrop`/`importsToRetire`.

Because these are Arrays and not Sets, we try to do `syscall.dropImports(['o-50', 'o-50'])` (which works for some reason), and then `syscall.retireImports(['o-50', 'o-50'])`, where the first copy deletes the c-list entry and the second copy fails translation. The translation failure is a vat-fatal error, and the vat dies.

In practice, I have to create two virtual objects, each with their own import. I found that if I make N virtual objects, the last Representative created sticks around, and only the first N-1 of them get finalized. There must be some other bug causing the last one to stick around.

The fix is probably to make `importsToDrop` and `importsToRetire` into a Set, and then linearize and sort them before making the syscalls.

I've got a failing test, I'll make a PR to see if that fix actually works.

cc @FUDCo

**Comment by FUDCo** [comment]
> I found that if I make N virtual objects, the last Representative created sticks around, and only the first N-1 of them get finalized. There must be some other bug causing the last one to stick around.

I don't think this is a bug.  I think it's just an artifact of how the VO cache works, which regardless of what size you set the cache to, it always holds onto one more object than that (N objects in the cache plus one held in the cache's internal machinery).

**Comment by warner** [comment]
Can we fix that? It's confusing for debugging (I spent half a day tearing my hair out before realizing my vatstore writes were being delayed by the cache and remembering to set the size to zero, then a second half day trying to understand why that one object wasn't getting GCed), and delays GC for an unknown-maybe-indefinite time.

**Comment by FUDCo** [comment]
I suppose it's possible, but it would be tricky and complicated.  Basically, the operation that throws things out of the cache (based on the configured size limit) is invoked at the point when you want to insert something into the cache, which is the point at which it needs to ask if there are too many entries in the cache. So when you set the cache size to 0 it means you throw away everything before inserting a new entry.  But then that new entry is immediately inserted into the cache.  The VOM is always holding onto at least 1 object.  To change this would require completely rearranging how the thing works.  In this case the issue was not so much that it did this but that you didn't know that it did this.  My first though was "oh, you should have asked me about that", but of course a key problem with not knowing something is that you don't know it. 
 Certainly the cache behavior could have been explained in a warning comment in the VOM code.  The behavior that tripped you up hasn't done that to me because I already knew how it worked and was expecting it.
