### ISSUE TITLE
odd crank times while running a devnet 

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#5139]
## Describe the bug
While running a devnet with 3 validators, and 50 ag-solos performing repetetive tasks, the chain ultimately failed to produce blocks around height ~9000.  In addition, I noticed long block times (e.g,  block 899 took 93900ms (a minute and a half)).

Some crank numbers in question:
crank 268197
crank 268201 - deliver of bringOutYourDead
crank 268203 - deliver result of bringOutOurDead

debug dump of primary-validator-0: https://drive.google.com/file/d/12b-BQTUoCi6eeL-bhrfFwPGPdauyWcAN/view?usp=sharing

```
2022-04-17T03:52:03.735Z block-manager: wrote SwingSet checkpoint [run=171734ms, chainSave=1ms, kernelSave=7ms]
```

on the other validator, I also noticed abnormal times when the chain ultimately halted.  Unfortunately I only have debug dumps of the primary validator

```
2022-04-17T03:47:23.172Z block-manager: wrote SwingSet checkpoint [run=62331ms, chainSave=0ms, kernelSave=2ms]
2022-04-17T03:47:55.137Z block-manager: wrote SwingSet checkpoint [run=4621ms, chainSave=0ms, kernelSave=6ms]
2022-04-17T03:48:25.582Z block-manager: wrote SwingSet checkpoint [run=28468ms, chainSave=0ms, kernelSave=3ms]
2022-04-17T03:48:25.909Z block-manager: wrote SwingSet checkpoint [run=1ms, chainSave=0ms, kernelSave=2ms]
2022-04-17T03:49:06.900Z block-manager: wrote SwingSet checkpoint [run=4179ms, chainSave=4ms, kernelSave=12ms]
2022-04-17T03:52:03.735Z block-manager: wrote SwingSet checkpoint [run=171734ms, chainSave=1ms, kernelSave=7ms]
```

**Comment by warner** [comment]
This smells to me like the kernel process going out to lunch, so the worker sends a message to the kernel (either `syscall` or `deliver-result`), and the kernel is too busy thrashing or something to notice for 30-60s.

In state/slogfile_1650045977.json I counted 863 lines whose timestamps were more than 10s after the previous line.
* 730 saw the pause happen between `cosmic-swingset-end-block-finish` and `cosmic-swingset-begin-block`: i.e. outside of swingset entirely
  * this could be our validator waiting for the block proposer to make a proposal, or something in the cosmos layer taking a long time
* 123 were just before a `deliver-result`, which could be the worker stalling, or could be the kernel process
* 8 were before a `syscall`, so the worker, same possibilities
* 1 happened between `dispatch.bringOutYourDead` and a syscall
* 1 happened between `cosmic-swingset-end-block-start` and the routing crank, before any worker was involved (line 6503410-6503411), this delay was 30.7s
* 1 happened between a `syscall` and its `syscall-result`, which happens entirely on the kernel side (line 12635608-12635609). this delay was 30.1s

The 730 in the first category could not be caused by the worker stalling, because no worker is running at that point (in fact no part of swingset is running), but they might still be caused by some cosmos thing, or by some other node (the block proposer) being slow. The last two delays in that list are happening in swingset (not in cosmos) but are outside of the worker, so they're more concrete evidence that the kernel process is stalling somehow.

**Comment by warner** [comment]
There's a bit of `xsnap.c` instrumentation I've had in mind to prove/disprove this theory: basically I want `xsnap` to record a timestamp of every message receipt and send, and then include this array of timestamps in the metering results at `deliver-result` time. The kernel would include these in the slog, but otherwise ignore them. Our post-mortem slog-processing tools could then correlate when e.g. a `syscall` was sent by the worker, with the kernel's receipt (which is the timestamp we currently log). Note that both kernel and worker are on the same computer, so we don't need to worry about clock skew.

That would let us distinguish between the worker sending the syscall late, or the kernel receiving it late. It would also give us a pretty good idea of the cross-process latency. The value would include some amount of serialization/deserialization time on each side, but that wouldn't be enough to interfere with the evidence.

I've opened #5152 for this work.

**Comment by warner** [comment]
The number of pauses that are `k * 30s +/- 1s` is highly suspicious, so @michaelfig did a search through the codebase for 30s timers. One that we're investigating is a 30s repeater that's used to convince Node.js that the program is still running (so it doesn't terminate the event loop early, even though there's a bunch of Go code waiting to run in a different thread). My (weak) hypothesis is an event-loop bug in which inbound IO isn't processed until the timer fires. @arirubinstein is starting up a new test run (with more logging too) that changes this timer to 40s, to see if we get a suspicious bunch of `k*40s` delays.

**Comment by arirubinstein** [comment]
Thanks for all of the investigation into this.  I'm reliably unable to reproduce this in GKE, so I this must be a VM Hypervisor issue with the M1 vmware preview.  Here is a heatmap of twice the load of ag-solos (100) on the test cluster performing as expected

<img width="1037" alt="Screen Shot 2022-04-21 at 3 45 04 PM" src="https://user-images.githubusercontent.com/22369/164563433-c721ec1b-f1ba-4d49-936b-cc7f61050302.png">
