### ISSUE TITLE
Support JSON as a governance param type

### ISSUE THREAD

**Issue by dtribble** [Agoric/Agoric#5184]
## What is the Problem Being Solved?

Liquidation needs a dynamic set of arguments provided via governance, depending on the specific liquidation installation used

## Description of the Design

Add `ParamTypes.JSON` to the set of supported param types

## Security Considerations

N/A

## Test Plan

Extend current param tests for the new type

**Comment by erights** [comment]
Why JSON rather than one of
   * any passable value, 
   * any passable key,
   * any passable pure data

?

**Comment by dckc** [comment]
How does this figure into the RUN Protocol preview? the preview contracts went out without this, no?

**Comment by Chris-Hibbert** [comment]
> How does this figure into the RUN Protocol preview? the preview contracts went out without this, no?

The requirement was written in the context of the preview. The code that was written used the `UNKNOWN` escape hatch. It turned out that the parameter it used was actually a passable, which I'm doing as a separate PR.

> Why JSON rather than one of

I'm doing PASSABLE next. (Which I presumed would most usefully be a passable record.) What would be the use case for governing just a passable key? Would there be value in distinct types (and type checks) for passable pure data and passable values generically?

**Comment by Chris-Hibbert** [comment]
@erights  was convincing that JSON doesn't meet our needs. We'll do something with [passable records](https://github.com/Agoric/agoric-sdk/pull/5273) to serve this particular need, and queue up some design on governing passables accompanied by a pattern in case that becomes a useful option.
