### ISSUE TITLE
Notifier observers to discriminate between vat failure and upgrade

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5185]
## What is the Problem Being Solved?

We need a mechanism for notifier observers to discern a failure caused by a vat termination (which should result in a permanent failure), and a failure caused by a vat upgrade (which should result in a retry).

By happen-chance right now we're been using an error instance for the former, and an error string for the latter. This is however very brittle, and a drive-by change (almost?) made the string an error: https://github.com/Agoric/agoric-sdk/pull/5130/files#r854732408

## Description of the Design

Some more stable and documented way to discern the cause of failure, and whether a retry should be attempted.

## Test Plan

There must be tests and documentation for this behavior.

**Comment by warner** [comment]
This overlaps with SwingSet because that's where vat failure-vs-upgrade originates. But the protocol definition and implementation is squarely in `packages/notifier`. We'll change swingset to emit whatever seems most useful for Notifier.

**Comment by warner** [comment]
What I just heard from @FUDCo is that @erights agreed to use `reject('vat upgraded')` as the very specific signal that the notifier's observe should re-try the `getUpdateSince`, and that any other rejection should be considered a non-retryable failure. This means that the specific `vat upgraded` string is now part of the swingset API.

**Comment by mhofman** [comment]
I'm ok with that as long as it's documented somewhere, preferably including at the place where the string is thrown.

As I mentioned in the PR, I believe we should have a single const where the special string is defined, with a comment explaining why it's so, and that it must not change without an update to code relying on notifiers.

**Comment by mhofman** [comment]
I also would prefer if notifiers used a helper like `isUpgradeError` so that we don't need to track down everywhere such test may happen.

**Comment by FUDCo** [comment]
> I also would prefer if notifiers used a helper like `isUpgradeError` so that we don't need to track down everywhere such test may happen.

Something like that would be good, but not with that name.  As @erights points out, the reason for not using an Error is that it's not an error.

**Comment by FUDCo** [comment]
Also, if we had used `Error`, you'd still have the same issue because you'd need to look at the message inside the error to see if the rejection was caused by an upgrade.

**Comment by warner** [comment]
@gibson042 to modify the two client-side helper functions in `packages/notifier` to understand this protocol ("rejected with `vat upgraded`").

@dtribble says: if the first request to this notifier rejects with the "vat upgraded", that's probably a deeper error, and we should stop. @erights says what? @dtribble says: if you didn't get the promise yourself...

* I ask for a notifier
* I get a promise that (hopefully) resolves to the notifier
* I hand that promise to the iterator

But: if the promise actually gets rejected (with `vat upgraded`), that will cause a loop. So we need to distinguish between whether we successfully got a notifier or not.

@erights says: rejected promise contagion can confuse. Maybe getting a rejection reason through contagion is an error.

**Comment by erights** [comment]
The rest of the post below is of historical interest only. While writing it up, I realized that it is fatally flawed, which I'll explain in the next message.

<blockquote>

I suggest that the normal promise rejection contagion guarantee that the propagated rejection reason always be an error independent of whether the original rejection reason is an error.

consider:

```js
const notifierP = //...whatever returns an unresolved remote promise
const recordP = E(notifierP).getUpdateSince(....);
```

If `recordP` rejects with the string `'vat upgraded'`, we want to treat that as a non-erroneous signal that the notifier client should adapt to the notifier's vat being upgraded. However, if `notifierP` rejects with the string `'vat upgraded'`, then the normal rejection reason contagion would also reject `recordP` with the string `'vat upgraded'`. However, the state of `recordP` should actually be diagnostic of something erroneous happening. And the purpose of rejection reason contagion is to propagate error diagnostic.

So, I suggest the correct solution is at a low abstraction level: That the rejection reason contagion mechanism should guarantee that the derived rejection always be an error, because any derived rejection itself should be considered erroneous.

</blockquote>

The rest of the post above is of historical interest only. While writing it up, I realized that it is fatally flawed, which I'll explain in the next message.

**Comment by erights** [comment]
The fatal problem is that blind rejection reason contagion is too deeply a part of existing standard JavaScript semantics that we absolutely cannot change. Consider `.then`, `await`, and `Promise.all`. These propagate whatever the rejection reason is, and our `E` semantics has to work intimately and consistently with it.

**Comment by mhofman** [comment]
First, I thought that when sending a message to an errored promise, the resulting error was already a new error generated either by Swingset or liveslots/HandledPromise?

Second, I thought @dtribble's point was that the update result of `getUpdateSince` from the producer side may itself be a promise rejected with the string `'vat upgraded'`. I suppose that becomes a question of how the notifier API handles rejected promises as values. Are they wrapped as a success result (like a sync iterator yielding a `{done, value}` record), or is a promise value somehow unwrapped like in the case of `async-from-sync-iterator` ?

Edit: sorry I am wholly unfamiliar with our notifiers.

**Comment by dtribble** [comment]
From my perspective, this is the promise transitioning to a "disconnected" state. But that's not worth trying to make a distinct state in the promise. Instead, make the rejection distinct: make a unique Disconnection object that represents this disconnection event, or have it be a record with a unique value. Then, a client that makes a retry can tell if that retry fails as a result of the same disconnection event. This is pretty simple, easy to understand, and solves the retry problem. If you can use object identity here, then it doesn't require any unique data. Otherwise, it might require a kernel-provided data value.

**Comment by mhofman** [comment]
Ah so mint a brand new object with identity and reject promises of that specific upgrade with that. If the client tries twice and gets that unique object twice as rejection in a row, consider that the notifier is permanently borked?

For identification purposes, we could wrap the unique object in copy data, e.g. `{upgraded: uniqueUpgradeToken}`

**Comment by dtribble** [comment]
> First, I thought that when sending a message to an errored promise, the resulting error was already a new error generated either by Swingset or liveslots/HandledPromise?

When you send/then to a rejected promise, the result is a promise rejected with exactly the same rejection value, not a newly generated thing.

> Second, I thought @dtribble's point was that the update result of `getUpdateSince` from the producer side may itself be a promise rejected with the string `'vat upgraded'`.

The result of `getUpdateSince` is the long-lived promise that will get disconnected. So in this scenario, it does get rejected with `'vat upgraded`'. The problem is what if the notifier itself is a rejected promise. I've seen code that created a notifier as the result of requesting a notifier from somewhere else (e.g., a regular quote notifier just wraps an underlying timer notifier). Thus it is possible to have the promise for the source notifier become rejected with `vat upgraded`, or of course an attacker could do it. In that case, every call to `gettUpdateSince` would get rejected with `vat upgrade`, causing a simple handler to recursively call `getUpdateSince` on the "notifier", which get rejected,....

> I suppose that becomes a question of how the notifier API handles rejected promises as values. 

So this is not about the notifier value at all. The result of `getUpdateSince` is a record provided by the notifier with `{ updateCount: n value: v}` where the value sent is in the `value` field. So clients cannot induce this behavior.

**Comment by dtribble** [comment]
> Ah so mint a brand new object with identity and reject promises of that specific upgrade with that. If the client tries twice and gets that unique object twice as rejection in a row, consider that the notifier is permanently borked?
> 
> For identification purposes, we could wrap the unique object in copy data, e.g. `{upgraded: uniqueUpgradeToken}`

Yep. Unless of course the object identity doesn't propagate usefully across boundaries. I had long ago propose an extension for that, but having it be a presence for the upgrade event would work. Or unique data.

**Comment by erights** [comment]
I do *not* like the idea that `disconnected` is an unforgeable state. Whether it is a string, or an forgeable object that is testably different than a normal error, or even a special error that is testably different than a normal error is still an open question. If so, we should still ask, what does it do under contagion?

**Comment by mhofman** [comment]
I actually hadn't noticed this contagion through `send`~~/`then`~~. Any reason for the contagion to exist in the first place?

**Comment by erights** [comment]
OMG contagion is critical and pervasive across our kind of promises. It is one of the main things that make them usable. In any case, JS's `.then`, `await`, and `Promise.all` already implement literal contagion, which is why I withdrew my original suggestion. If we introduced a special value representing disconnection, `.then`, `await`, and `Promise.all` would all implement literal contagion, so we must as well. I forgot this when I wrote the "If so, we should still ask". Our hand is forced. In this case, I don't mind having this decision be forced in this direction. I think net, it is more right than any alternative.

**Comment by mhofman** [comment]
Sorry I shouldn't have included `then`, but I am confused about `send` contagion.

The same way I do not expect `undefined.foo()` to result in `undefined`, I wouldn't expect `Promise.reject('err')~.foo()` to result in an `'err'` rejection, but in a `TypeError: cannot send 'foo' to rejected promise` with a property `cause: 'err'` on that new error.

**Comment by erights** [comment]
The analogy of `reject` is not `return`, it is `throw`. The analogy of contagion is unhindered propagation of a thrown value through non-interfering intermediaries.

The semantics of `await` depend on this analogy.

**Comment by erights** [comment]
```js
> async function foo() { "use strict"; (await Promise.reject('err')).foo(); }
undefined
> foo()
Promise {
  <pending>,
}
> Uncaught 'err'
```
It does result in an `'err'` rejection.

**Comment by mhofman** [comment]
I really don't understand. When the user does `E(resultP)` they make the assumption that the eventual resolution of `resultP` will be a remotable. If they perform `E(resultP).foo()` and their assumption breaks down, they should be told that their assumption broke (new error), and why it broke (the initial rejection of `resultP` as cause).

We have an opportunity with eventual send to not propagate the `await` contagion blindly.

In the case of remotable result, awaiting the result promise will in most cases not yield you a local object, but only a remote presence, on which you need to use eventual send anyway.

**Comment by mhofman** [comment]
Today if a user does `const t = Promise.resolve(harden({someData: 42})); E(t).foo()`, an error is generated, right? Why not similarly generate an error in the case where `t = Promise.reject(harden({someData: 42}))` ?

**Comment by erights** [comment]
@michaelfig and I have discussed raising the abstraction level of `E` to be more marshal-aware. This question is undecided. We'll likely leave it at the eventual-send level of abstraction, where it is now. It does 
```js
return harden((...args) => HandledPromise.applyMethod(x, p, args));
```
which uses only concepts from SES (`harden`) and from the eventual-send proposal (currently spelled `HandledPromise.applyMethod`).

You can thus `E` any JS value.

**Comment by erights** [comment]
```js
E(t).foo()
```
does not generate an error because `harden({someData: 42})` is not remotable. It generates an error only later, when it tries to call its `foo` method.

@michaelfig please correct me if I'm not properly representing the semantics or plans for `E`.

**Comment by mhofman** [comment]
SwingSet does blindly propagate the rejection, but I maintain this a decision in the design of eventual-send, and not one which I'm convinced about right now.

https://github.com/Agoric/agoric-sdk/blob/4d464ac8cbf6c2f10db6c21b4b6ed5259ad00e55/packages/SwingSet/src/kernel/kernel.js#L774-L781

**Comment by erights** [comment]
Because `harden({someData: 42})` is local, the semantics of `E(t).foo()` is identical to
```js
Promise.resolve(t).then(r => r.foo());
```
is identical to
```js
(await t).foo()
```

**Comment by erights** [comment]
Yes, it is a SwingSet choice whether to implement a semantics consistent with the local JS semantics, or to implement distributed semantics which differs from local semantics in hard to explain ways. I just don't like the second choice ;) .

**Comment by mhofman** [comment]
But it is the proposed eventual-send semantics to propagate a rejection of `x` in the case of `HandledPromise.applyMethod(x, p, args)` instead of raising a new `TypeError` with cause which I'm suggesting. I still don't see why pure JS semantics are allegedly involved here.

**Comment by erights** [comment]
The proposed eventual-send semantics were designed to produce the above equivalences when `t` is anything other than a handled promise (or a promise forwarded to a handled promise). If I saw such a proposal that did not preserve this semantics for the local case, I would likely reject it. I don't believe any other choice for the eventual-send proposal is reasonable.

It is then a choice, only of the provider of the handler of a handled promise. In this case, liveSlots, whether to implement a similar semantics. I've already acked that this is a SwingSet choice. I just think that SwingSet should preserve the semantics. But we can argue about that.

**Comment by mhofman** [comment]
> If I saw such a proposal that did not preserve this semantics for the local case, I would likely reject it.

Given that the language now has a native concept of error `cause` I believe we should consider when an operation is complex enough and has a clear boundary that it does not blindly bubble underlying errors but instead creates its own errors and chains them appropriately (aka catch and throw with cause). I believe eventual-send is such a case where chaining is appropriate instead of pass-through for the target.

**Comment by erights** [comment]
One constraint on the eventual-send proposal that I should emphasize: It motivates handled promises from the use-case of distributed objects, enabling a great variety of distributed object systems *such as ours* to be built. If we made the proposal too specific to our choices of distributed object semantics, I would likely object. For the proposal to be accepted into the language, it should have broad applicability, enabling the creation of many different systems.

**Comment by erights** [comment]
That's a good point! I can imagine that handled promise operations add a new outer layer to the `cause` chain even if `.then`, `await`, and `Promise.all` do not. You got me on the fence with this observation. 

What stack would you associate with this auto-generated outer error? (The answer I'd love is, sadly, probably too expensive to get most engine makers to agree to.)

@michaelfig , eventual-send is our proposal. What do you think of adding such automatic error wrapping?

**Comment by mhofman** [comment]
> What stack would you associate with this auto-generated outer error?

I would expect the stack at the point where `applyMethod` is called, but I feel this may be a trick question ;)

**Comment by mhofman** [comment]
I have moved the conversation about rejection contagion in eventual-send to https://github.com/endojs/endo/issues/1176

**Comment by dtribble** [comment]
> What do you think of adding such automatic error wrapping

Requiring that precludes tail recursion optimization because each layer must be prepared to wrap a failure with more information.

**Comment by mhofman** [comment]
@dtribble is that comment related to notifiers, or to the broader question of rejection contagion?

**Comment by erights** [comment]
It certainly is a valid counterargument against wrapping during rejection contagion. Good catch!

**Comment by mhofman** [comment]
I'd prefer discussing the rejection contagion in https://github.com/endojs/endo/issues/1176, but I don't see how tail recursion causes any issue. You can always redirect the result promise of the delivery to the result promise of the tail send. We're only talking about wrapping an error in the resolution of the send target, not the whole send.

Equivalent userland code, which can be tail-optimized in the kernel:

```js
const applyMethod = async (x, p, args) =>
  E.when(
    x, 
    (r) => r[p](...args),
    (e) => Promise.reject(new Error(`Cannot call ${p} on rejection`, { cause: e })),
  );
```

**Comment by erights** [comment]
I believe @dtribble doesn't mean literal tail recursion, but rather the accumulation of storage proportional to the depth of the recursion. If Alice says 
```js
const p = E(bob).foo(carol);
```
invoking Bob's `foo` method, which reads
```js
   foo: carol => E(carol).bar();
```
then currently, the promise for the result of `foo` is forwarded to the promise for the result of `bar`. *If* promise forwarding chains are collapsed by the implementation (admittedly a big ask), then the `foo` call has contributed no non-garbage to the bookkeeping for the return result. "Tail recursion for the heap".

@dtribble am I representing your concern accurately?

**Comment by mhofman** [comment]
@dtribble @erights answered at https://github.com/endojs/endo/issues/1176#issuecomment-1113912324

**Comment by warner** [comment]
Please coordinate with #5649 , which will change the upgrade-provoked rejection value to be a distinctive object (not an Error).

**Comment by gibson042** [comment]
Some interesting questions are being raised by the current state of #7401:
1. When retrying after getting a vatUpgraded rejection results in a new rejection, how much information can we provide? I'm currently adding a ``` X`Attempting to recover from disconnection: ${initialDisconnection}` ``` note to the new rejection [as suggested by @mhofman](https://github.com/Agoric/agoric-sdk/pull/7401#issuecomment-1506096886), which seems to be the best that can be done because AFAICT it is not possible to detect a "splat" that we'd want to replace with the original vatUpgrade rejection (_which is actually a similar problem to detecting vatUpgraded in the first place, where rejection is a `{name: 'vatUpgraded', upgradeMessage: string, incarnationNumber: number}` object rather than an Error instance in order to convey structured failure information across vat boundaries_).
2. What should be done about gap-free subscribers such as `subscribeEach` iterators? It is not possible to uphold the gap-free guarantee in every case, but would be possible to _detect_ the absence of a gap before a non-failure publication record (and presumably allow the subscriber to remain active) if we commit to `publishCount` starting at 1n and always incrementing by 1n.

**Comment by michaelfig** [comment]
Number 1 looks good.  ISTR the `reason` in `assert.note(reason, X...)` must be an Error, but I could be wrong.  (I have not yet looked to see if your code is tolerant of that constraint, or unit tests somewhere prove that it isn't a constraint.)

As far as 2, I like your suggestion: we can and should "commit to `publishCount`" semantics that you described there.
