### ISSUE TITLE
Smart wallets can get balances with zero transactions (for small # of users)

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#5356]
Epic milestone to https://github.com/Agoric/agoric-sdk/issues/3995

## Acceptance criteria

- When using the wallet, Keplr is not brought up until there is a transfer of value
- UI can show wallet balances
- Subscriptions publish to Cosmos events

**Comment by turadg** [comment]
@samsiegart what's a good ticket for "chain selection/signing frontend" ?

@dckc what's a good ticket for "Add cosmjs client to wallet dapp" ?

@gibson042 what's a good ticket for tracking that "backend subscriptions can reach frontend notifiers" ?

**Comment by samsiegart** [comment]
> @samsiegart what's a good ticket for "chain selection/signing frontend" ?

I think this was it https://github.com/Agoric/agoric-sdk/issues/4421. That allows us to select the chain and get a cosmjs signer

**Comment by turadg** [comment]
@samsiegart cool. is there any other frontend work needed for this story? let's try to have it all as part of this epic

**Comment by dckc** [comment]
> Acceptance criteria
> Users can load wallet UI using on-chain wallet

I'm not sure I understand that. How can a user tell whether they're using the on-chain wallet or not?

I suspect an acceptance test will involve looking at the network traffic and / or block explorer to verify that we didn't add any cosmos transactions to get our balance. Another place to look might be the IST balance, since sending a swingset message costs (a little bit of) IST.

p.s. I was using #3756 to track pretty much the same thing. I wonder whether having two separate epics is cost-effective. I don't have much experience using epics, though. In my experience, enhancement (or bug) tickets with blockers is necessary and sufficient.

**Comment by samsiegart** [comment]
> I'm not sure I understand that. How can a user tell whether they're using the on-chain wallet or not?

They'll know when they connect to keplr in the wallet UI, or more concretely, if everything works and they don't have an ag-solo running.

**Comment by samsiegart** [comment]
> @samsiegart cool. is there any other frontend work needed for this story? let's try to have it all as part of this epic

Yes but I'm not sure what it looks like yet. We have to sign some sort of message to get the wallet bridge, all the purse balances, etc. in the UI.

**Comment by dckc** [comment]
> @dckc what's a good ticket for "Add cosmjs client to wallet dapp" ?

#4398 and #4421 seem to cover it.
