### ISSUE TITLE
Why is `harden` not recognized as a global in vat-data/src/index.js ?

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#5417]
See https://github.com/Agoric/agoric-sdk/runs/6534777821?check_suite_focus=true#step:4:121

I don't understand how we tell eslint what our globals are. But I do see `"harden"` in eslint-config.json , and I do see 
```js
  "eslintConfig": {
    "extends": [
      "@agoric"
    ]
  },
```
in vat-data/package.json , so I'm flummoxed.

**Comment by turadg** [comment]
This is a set of questions, not a bug. I'd suggest posing it on the PR it was encountered or asking in chat for greater visibility. Though I'll answer here to respect the request.

In ESLint [globals are defined in source or config files](https://eslint.org/docs/user-guide/configuring/language-options#specifying-globals). We only use the former (`/* global something */`) and not the latter. There's also a method of [specifying an Environment](https://eslint.org/docs/user-guide/configuring/language-options#specifying-environments) which implies a set of globals. @kriskowal has considered making a SES one but I don't know of a ticket.

However the error you saw was not from Eslint. Our "lint" script runs per package and then within the package runs every `lint:*` script.
```
lerna info run Ran npm script 'lint' in '@agoric/vat-data' in 7.6s:

> @agoric/vat-data@0.3.0 lint /home/runner/work/agoric-sdk/agoric-sdk/packages/vat-data
> run-s --continue-on-error lint:*


> @agoric/vat-data@0.3.0 lint:eslint /home/runner/work/agoric-sdk/agoric-sdk/packages/vat-data
> eslint --ext .js,.ts .


> @agoric/vat-data@0.3.0 lint:types /home/runner/work/agoric-sdk/agoric-sdk/packages/vat-data
> tsc

Error: src/index.js(75,1): error TS2304: Cannot find name 'harden'.
Error: src/index.js(88,1): error TS2304: Cannot find name 'harden'.
Error: src/index.js([108](https://github.com/Agoric/agoric-sdk/runs/6534777821?check_suite_focus=true#step:4:109),1): error TS2304: Cannot find name 'harden'.
Error: src/index.js(128,1): error TS2304: Cannot find name 'harden'.
Error: src/index.js(134,1): error TS2304: Cannot find name 'harden'.
```
`lint:eslint` passed but `lint:types` did not. I've advocated for not using "lint" as the umbrella term as it can be confused with eslint (evidenced here). I've also advocated for moving Prettier, Eslint and Typescript to be SDK-level instead of package level to reduce complexity and make the SDK development experience more consistent. But that's blocked on some tech debt and far from worth the churn before MN-1.

In this package, Typescript doesn't know about `harden()`. I think that's because it doesn't import other packages which define it ambiently. A [solution](https://github.com/endojs/endo/issues/777#issuecomment-861896779) is to add this to `src/index.js`:
```
/// <reference types="ses"/>
```
In the long term, maybe a `@types/ses` package https://github.com/DefinitelyTyped/DefinitelyTyped (e.g. as a dependency of `@agoric/vat-data`) would be a cleaner convention.
