### ISSUE TITLE
kernel: ##### KERNEL PANIC: unable to re-create vat v4 ##### (truncated .gz file)

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#5419]
On a test network, a few validator nodes dropped, and were unable to recover from a reboot with the following error.

```
{"level":"info","time":"2022-05-21T19:55:22Z","message":"starting ABCI with Tendermint"}
{"level":"info","args":["ag-chain-cosmos","--home","/root/.agoric","start","--home=/state/agoriloadtest-8","--log_format=json"],"time":"2022-05-21T19:55:22Z","message":"Start chain delegating to JS executable"}
{"level":"info","time":"2022-05-21T19:55:23Z","message":"starting ABCI with Tendermint"}
{"level":"info","module":"proxy","impl":"multiAppConn","time":"2022-05-21T19:55:24Z","message":"Starting multiAppConn service"}
{"level":"info","module":"proxy","connection":"query","module":"abci-client","impl":"committingClient","time":"2022-05-21T19:55:24Z","message":"Starting committingClient service"}
{"level":"info","module":"proxy","connection":"snapshot","module":"abci-client","impl":"committingClient","time":"2022-05-21T19:55:24Z","message":"Starting committingClient service"}
{"level":"info","module":"proxy","connection":"mempool","module":"abci-client","impl":"committingClient","time":"2022-05-21T19:55:24Z","message":"Starting committingClient service"}
{"level":"info","module":"proxy","connection":"consensus","module":"abci-client","impl":"committingClient","time":"2022-05-21T19:55:24Z","message":"Starting committingClient service"}
{"level":"info","module":"events","impl":"EventBus","time":"2022-05-21T19:55:24Z","message":"Starting EventBus service"}
{"level":"info","module":"events","module":"pubsub","impl":"PubSub","time":"2022-05-21T19:55:24Z","message":"Starting PubSub service"}
{"level":"info","module":"txindex","impl":"IndexerService","time":"2022-05-21T19:55:24Z","message":"Starting IndexerService service"}
{"level":"info","module":"consensus","hash":"\u000b&m\ufffd\ufffd\ufffd\ufffddOZ\ufffd~o\ufffd\u000fR7K\ufffd\ufffd\ufffd\ufffd\u0019\ufffd[\ufffdL\ufffd(Nq\ufffd","height":10889,"protocol-version":0,"software-version":"0.29.0","time":"2022-05-21T19:55:24Z","message":"ABCI Handshake App Info"}
{"level":"info","module":"consensus","appHeight":10889,"stateHeight":10893,"storeHeight":10893,"time":"2022-05-21T19:55:24Z","message":"ABCI Replay Blocks"}
{"level":"info","module":"consensus","height":10890,"time":"2022-05-21T19:55:24Z","message":"Applying block"}
Loading makeSlogSender from @agoric/telemetry/src/otel-trace.js
Prometheus scrape endpoint: http://0.0.0.0:26661/metrics
Enabling OTLP Traces Exporter to http://localhost:4318/v1/traces
2022-05-21T19:55:25.408Z launch-chain: Launching SwingSet kernel
2022-05-21T19:55:25.427Z launch-chain: buildSwingset
SwingSet xs-worker tracing: {
  XSNAP_TEST_RECORD: '/state/agoriloadtest-8/xs_test_record_1653162921'
}
2022-05-21T19:55:27.491Z SwingSet: ls: v1: Logging sent error stack (Error#1203)
2022-05-21T19:55:27.493Z SwingSet: ls: v1: Error#1203: cannot grab 1295000000urun coins: 154181338urun is smaller than 1295000000urun: insufficient funds [agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.4/x/bank/keeper/send.go:187]
2022-05-21T19:55:27.496Z SwingSet: ls: v1: Error: cannot grab 1295000000urun coins: 154181338urun is smaller than 1295000000urun: insufficient funds [agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.4/x/bank/keeper/send.go:187]
 at apply ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5941)
 at callOutbound (.../vats/src/bridge.js:63)
 at apply ()
 at apply ()
 at dispatchToHandler (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8729)
 at (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8362)
 at win (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9072)
 at ()

2022-05-21T19:55:27.497Z SwingSet: ls: v1: Error#1203 ERROR_NOTE: Thrown from: (Error#1204) : 8986 . 0
2022-05-21T19:55:27.498Z SwingSet: ls: v1: Error#1203 ERROR_NOTE: Sent as error:liveSlots:v1#70602
2022-05-21T19:55:27.500Z SwingSet: ls: v1: Error#1204: Event: 8985.1
2022-05-21T19:55:27.501Z SwingSet: ls: v1: Error: Event: 8985.1
 at construct ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5943)
 at trackTurns (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8346)
 at handle (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9063)
 at deliver (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15803)
 at dispatchToUserspace (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:16113)
 at runWithoutMetering (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:16566)
 at ()

2022-05-21T19:55:28.100Z SwingSet: ls: v1: Logging sent error stack (Error#1205)
2022-05-21T19:55:28.101Z SwingSet: ls: v1: Error#1205: cannot grab 1050000000urun coins: 153981338urun is smaller than 1050000000urun: insufficient funds [agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.4/x/bank/keeper/send.go:187]
2022-05-21T19:55:28.102Z SwingSet: ls: v1: Error: cannot grab 1050000000urun coins: 153981338urun is smaller than 1050000000urun: insufficient funds [agoric-labs/cosmos-sdk@v0.45.1-alpha.agoric.4/x/bank/keeper/send.go:187]
 at apply ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5941)
 at callOutbound (.../vats/src/bridge.js:63)
 at apply ()
 at apply ()
 at dispatchToHandler (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8729)
 at (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8362)
 at win (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9072)
 at ()

2022-05-21T19:55:28.104Z SwingSet: ls: v1: Error#1205 ERROR_NOTE: Thrown from: (Error#1206) : 8998 . 0
2022-05-21T19:55:28.105Z SwingSet: ls: v1: Error#1205 ERROR_NOTE: Sent as error:liveSlots:v1#70603
2022-05-21T19:55:28.106Z SwingSet: ls: v1: Error#1206: Event: 8997.1
2022-05-21T19:55:28.107Z SwingSet: ls: v1: Error: Event: 8997.1
 at construct ()
 at Error (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:5943)
 at trackTurns (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:8346)
 at handle (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js:9063)
 at deliver (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:15803)
 at dispatchToUserspace (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:16113)
 at runWithoutMetering (/usr/src/agoric-sdk/packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js:16566)
 at ()

2022-05-21T19:55:30.859Z SwingSet: kernel: ##### KERNEL PANIC: unable to re-create vat v4 #####
portHandler threw (Error#1)
Error#1: unexpected end of file

  at Zlib.zlibOnError [as onerror] (zlib.js:187:17)

Cannot initialize Controller Error: unexpected end of file
{"level":"info","time":"2022-05-21T19:55:37Z","message":"starting ABCI with Tendermint"}
```

I suspect either the process is not exiting cleanly when signaled

Here are the debug files from the a working node, and two misbehaving nodes: https://drive.google.com/drive/folders/1mzAelIl13RqzFGVbPj5CouBsByngTAqW?usp=sharing

Revision: 922d4c0bd566d8e8a3918fc9c6696031e130637e

**Comment by warner** [comment]
@arirubinstein and I did more analysis. We're seeing zero-byte compressed heap snapshot files (a file named like `0123abcdetc.gz` is zero bytes long). We also saw that the Kubernetes pod that was hosting the validator was restarted about ten seconds after that file was written (to be migrated to a different host). The migrate/restart process does the usual Unix thing of sending SIGTERM to all processes, waiting 10 seconds, then sending SIGKILL. The Tendermint docs state that it responds to SIGTERM by "cleaning up and exiting cleanly", and the source code shows that it does catch SIGTERM in order to do an `exit(0)` instead of exiting with some more-scary-looking exit code.

Our hypothesis is that the way we're compressing this snapshot file (via a Node.js stream filtering library of some sort) is shelling out to `/usr/bin/gzip` in a subprocess, and that the subprocess has opened the output file but not written anything to it yet. Then SIGTERM comes along and kills `gzip`, but allows `agd` to keep running (because the Tendermint library code within `agd` installed a signal handler). Or at least the Node.js thread within `agd` is still running. That thread observes the pipe to `gzip` close (since `gzip` terminated) and doesn't look carefully enough at the exit status, so it thinks the compression has succeeded, when in fact the output file is empty. Then the thread proceeds far enough to commit the snapshot ID to the kvStore, and then to LMDB, before the Go/Tendermint side gets to the `exit(0)` point, and the overall process exits. We probably didn't make it to the IAVL commit point.

That would leave the LMDB state pointing at the new snapshot file, but that file is corrupt (zero bytes). So the next time that `agd` starts, swingset tries to load an `xsnap` from the lame snapshot and fails, causing the observed kernel panic.

This hypothesis might explain the observations, but @mhofman pointed me at the code (https://github.com/Agoric/agoric-sdk/blob/87a9e628315948fa75e78bf5294178f65bc34b56/packages/swing-store/src/snapStore.js#L128) and we aren't seeing any obvious smoking guns. The gzip functionality is coming from the Node.js standard library `import { createGzip } from 'zlib'` (which might be shelling out to `/usr/bin/gzip` but more likely is using `/usr/lib/libzlib`, which shouldn't be vulnerable to this sort of confusion). The code that wraps that call is sending the compressed output to a tempfile and only renaming it (atomically) if the compression claims to have succeeded. So the only way our hypothesis could fit is if the signal tricked the Node.js standard `zlib` library into returning "success" when in fact it failed.

One other datapoint, in case it's relevant. The validator had xsnap tracing turned on, which writes a small file for each netstring command sent to the worker process (and another for certain replies that came back). We saw about ten zero-byte `.reply` files on the disk from the last minute of the kernel process' life. I don't have a good theory on how these could wind up being zero bytes long. *One* zero-byte file could be explained by the process being terminated in the middle of the `.put()` call (`xsnap/src/replay.js`), so in the middle of `writeFileSync`, after opening the file but before writing any data to it. But I can't imagine what could cause that to happen to multiple files at once.

**Comment by warner** [comment]
We're disinclined to believe in a k8s or filesystem bug, since it's so widely used, but a bug in which the container's kernel got stopped abruptly (equivalent to a real computer suddenly losing power, and not having time to flush page buffers) could account for the symptoms. Something like every file that had been written to recently, closed without error, but the kernel didn't happen to write out the page buffers (and nothing in userspace requested an `fflush()`), winding up with the directory information (filename) but not contents (truncated to zero bytes).

We're similarly disinclined to believe in a bug in our `snapStore.js` compression/renaming pipeline, because 1: we've reviewed the code at least once without seeing obvious problems, 2: we observe truncated files both for `HASH.gz snapshot files *and* for the xsnap trace record files, which are written by entirely different functions. But, Node streams are weird, and we have two separate runtimes (Golang and Node) in the same process, and there are signals flying around, and who knows how many threads. So it's hard to rule out.

One next step: @kriskowal and @mhofman will make another pass through the `snapStore.js` pipeline, with a specific eye towards "what happens if a `write()` or `close()` syscall returns an error". They may also `strace` a sample program to make sure we fully understand what Node.js is doing under the hood. We aren't prepared to rule out our code doing something wrong until we see an `strace` record of the compressed data being written and closed without error.

@arirubinstein pointed out that, whatever the problem is, this way of using Kubernetes is super common, and we need our code to work correctly on top of it. So even if somehow k8s is at fault here, we need to characterize it well enough to either come up with a userspace workaround that we can incorporate into `agd`, or explain exactly how to configure k8s to our validator community so they can avoid the problem.

Thinking at a higher level: one rule that I was taught for doing application development "right" is to store *all* your state in a real database (even just SQLite): rely upon it for atomic commits of coherent state, and think about version upgrades in terms of DB schema upgrades. In cosmic-swingset, we're storing some pieces of our state in a real DB (in fact in three of them: IAVL on the host app, LMDB for `kvStore`, SQLite for the transcript/`streamStore`), but 1: the snapshot files are kept in an ad-hoc DB-like thing made out of directories and files, and 2: the lack of a single shared DB means our `commit()` is weirdly spread out among multiple places and not transactional. We've put a lot of thought into make-before-break change sequencing to avoid problems with the latter. For snapshot files, we believe we're doing the right thing w.r.t. `write()`/`close()` errors, and not doing the atomic rename until everything is safely written, but this approach does assume that the underlying kernel will commit changes to disk in the usual order, and that assumption depends upon the kernel not being abruptly terminated. We don't know if that's what's happening here or not, but if it *were*, we would not be surprised to see at least a few of the symptoms we've observed.

The nice thing about using a real DB is that they all attempt to protect you against things like the kernel being abruptly terminated. They'll do an `fflush()` upon commit, and use data structures that stand a much better chance of remaining coherent even if the kernel is unable to provide the normal "clean kernel shutdown" level of guarantees.

So it's a problem that our snapshot files are held on disk, and that we aren't doing an `fflush()` somewhere. It's not entirely obvious *where* one or more `fflush()` ought to go (we should probably do one before the atomic rename, so we know that we aren't renaming a corrupted/empty file, but should we do one *after* the rename too?). And that's because we aren't DB designers, and really we should find a way to lean on a real DB for this part.

So maybe part of the answer is to move the snapstore into the SQLite instance we're using for transcripts (the `streamStore`). The `xsnap` snapshot load/save protocol requires real files on disk, but maybe the process should be:
* ask `xsnap` to write a snapshot to a kernel-selected tempfile, wait for it to complete
* hash the tempfile to learn the snapshot ID
* compress the tempfile, hold the compressed form in RAM
* perform a SQLite operation to store the compressed bytes into the DB: `CREATE TABLE snapshots ( id STRING , data BLOB )`
* commit the SQLite transaction

and on the way back out, read the compressed bytes into RAM, decompress into a tempfile, launch `xsnap` from the tempfile, delete the tempfile.

If any of this process got interrupted, we wouldn't make it to the DB commit. The tempfiles might make it to disk (and then they'd be corrupted/truncated when we look at them after a reboot), but since the write/compress step and the read-to-RAM step both happen within the same kernel lifetime, we should either get uncorrupted data in the DB, or nothing.

**Comment by mhofman** [comment]
> So maybe part of the answer is to move the snapstore into the SQLite instance we're using for transcripts

I've always heard that DB are not the right place to store large blobs of data.

Also I'm not convinced this will solve the issue. We'd still have 3 DBs with possibly different flushing mechanics. What guarantees that the streamStore will be committed and flushed properly before the swingStore is?

**Comment by warner** [comment]
Eh, I think they're better at large blobs than they used to be. SQLite is pretty versatile.

We've got a protocol (not necessarily completely solid, but we put a decent amount of time into it) between streamStore and kvStore to synchronize the commits. We do the SQLite commit to streamStore first ("write transcript item 5"), then we update the item number in kvStore ("vat 2 transcript length has changed from 4 to 5"), then we commit kvStore (LMDB). So if we get interrupted between the two, the next reboot will see "4" in kvStore and ignore (and eventually overwrite) transcript entry 5. So if the DB technology that backs streamStore is sound, and the DB that backs kvStore is sound, then there should be no way to observe a kvStore entry that references a missing streamStore transcript entry.

**Comment by mhofman** [comment]
> So if we get interrupted between the two, the next reboot will see "4" in kvStore and ignore (and eventually overwrite) transcript entry 5.

That's assuming the files for the streamStore are flushed before the files for swingStore. Given the kind of errors we're seeing, I wouldn't be so confident we can rely on this.

**Comment by mhofman** [comment]
I have been running the loadgen with 5 minute restarts cycles (SIGTERM) for the past 2 days and have not experienced any similar issue. I really believe the host shut down the filesystem without committing its caches (equivalent to power failure).

That said I've parsed through the node.js code and read about Unix fs syscalls, and I now understand that an `fclose` of a file does not guarantee that the OS will flush the data to the actual device, and Node does not implicitly call `fsync` anywhere. I'm ready to bet that both LMDB and SQLite both perform an fsync. What probably happen is that the write of the snapshots by the snapStore succeeded from the kernel process point of view, but wasn't synced to disk, unlike the writes for the swingStore and streamStore, which were explicitly synced.

We can transform our snapStore node code to create file handles from file names and work with those, which would allow us to perform an explicit fsync after write. I'll get working on a PR with that change.
