### ISSUE TITLE
Simple dashboard of econ data for Economic Stress Test

### ISSUE THREAD

**Issue by Tartuffo** [Agoric/Agoric#5421]
- [x] ag-solo plugin for Google Sheets
 - [x] deploy script to report econ data (#4639)
   - [x] issuers (from wallet)
   - [x] amm (https://github.com/Agoric/agoric-sdk/issues/4648)
     - [x] pools
     - [x] swaps
    - [x] vaults #4649
    - [x] liquidation #4650

Let's come back to these after we have RPC working:
    - reserve #4651
    - PSM #4968
    - BLD Boost #4653
    - Oracle / price authority #4652
    - goverance? (#5268)

**Comment by dckc** [comment]
Good news: [deploy-ist-monitor.js](https://github.com/dckc/ag-admin/blob/ist-dashboard-sheet/api/deploy-ist-monitor.js) script gets an event for each pool and for each trade.

~~Bad news: the Central, Secondary, and Liquidity values don't seem to change after the initial liquidity is added~~:
https://github.com/Agoric/agoric-sdk/pull/5420/files#r879991457
_p.s. that was because there was not much liquidity and hence more slippage than the tolerance._

**Comment by dckc** [comment]
## AMM Tick Data Spreadsheet

In the **swaps** tab of the [ag-solo play worksheet](https://docs.google.com/spreadsheets/d/17JySI8vImHU7EKbjW-_ZXmhbBZ8U9iF-yBdBOhLyXG4/edit?usp=sharing), we get a new row for each swap or liquidity transaction:

![image](https://user-images.githubusercontent.com/150986/170104790-f82a7bf8-88c9-483b-a67b-0450a032be1d.png)

Notes:
  - Row 2 shows is update 2 of the IbcATOM pool, at which point it's empty
  - Row 2 shows is update 2 of the AUSD pool, at which point it's empty
  - Row 4 shows that liquidity was added to the AUSD pool (50 RUN, 50 AUSD)
  - Rows 5, 6, and 7 show trades that didn't go through because the slippage was too high
  - Row 8 shows a small (0.20 RUN) trade
  - Row 9 shows adding 500 RUN of liquidity
  - Row 10 is another trade that didn't go through
  - Row 11 shows a trade of 3 RUN

In the **pools** tab:

![image](https://user-images.githubusercontent.com/150986/170104849-f372edb1-24b1-4d1b-bef2-a240aaed245f.png)

 - Row 2 shows that as of update 3, there was one pool: IbcATOM
 - Rows 3 and 4 show that as of update 4, there were two pools: IbcATOM and AUSD

The **issuers** tab is from the wallet, not from the AMM. It tells us what the brand names from the other two sheets mean. We get a new update each time we reload the wallet; each update has a list of issuers / assets, which we normalize as a sequence of rows:

![image](https://user-images.githubusercontent.com/150986/170104932-8a933aa4-c9cd-42a4-a1fd-9977ad4c6b26.png)

cc @btulloh @turadg @Chris-Hibbert @dtribble @rowgraus

**Comment by dckc** [comment]
target for tomorrow: AMM, vaults... stretch goal: liquidation

**Comment by dckc** [comment]
### AMM Tick Data Spreadsheet for xnet

it's working:

![image](https://user-images.githubusercontent.com/150986/170617120-f44e5d68-5b4e-4589-9cea-b3969b8afca1.png)

![image](https://user-images.githubusercontent.com/150986/170617136-1d208c69-0ef5-4215-84e7-330e0b75b618.png)

**Comment by dckc** [comment]
### Vault Tick Data

![image](https://user-images.githubusercontent.com/150986/170805982-31640b07-0e93-45d7-9b90-c93bc98fa200.png)

from

![image](https://user-images.githubusercontent.com/150986/170792495-daebca44-0efe-4d05-bcc5-24344200f677.png)

for reference:

ag-admin:
a374922 * dckc/ist-dashboard-sheet feat: monitor vaults (WIP)

**Comment by dckc** [comment]
oops... the spreadsheet is populated with strings. Those should be numbers.

_p.s. Fixed in https://github.com/dckc/ag-admin/commit/d2fb73d693973df4aedf77f50d6253ad201b305b_

**Comment by dckc** [comment]
### updates lagging?

When I paid off some debt, the totalDebt in the `[4,"IbcATOM"]` row didn't change. IOU more detail.

Key | updateCount | collateral | numVaults | totalCollateral | totalDebt
-- | -- | -- | -- | -- | --
[2,"IbcATOM"] | 2 | IbcATOM | 0 | 0 | 0
[3,"IbcATOM"] | 3 | IbcATOM | 1 | 15 | 467.3775
[4,"IbcATOM"] | 4 | IbcATOM | 1 | 15 | 467.3775

**Comment by dckc** [comment]
## How to run the dashboard

 1. copy [the econ data spreadsheet](https://docs.google.com/spreadsheets/d/17JySI8vImHU7EKbjW-_ZXmhbBZ8U9iF-yBdBOhLyXG4/edit#gid=1248729722) to get the right sheet and column names
 2. create a Google service account. _this is where we got hung up. supporting use of an API key would be nice._
 3. clone https://github.com/dckc/ag-admin ; check out the `ist-dashboard-sheet` branch
 4. in the `ag-admin` dir: `agoric start -v --reset testnet 8000 https://xnet.agoric.net/network-config`
 5. `cd api`
 6. set credentials as below.
 7. deploy the sheets plugin: `agoric deploy deploy.js --allow-unsafe-plugins`
 8.  start the IST monitor: `agoric deploy deploy-ist-monitor.js`

```
export GOOGLE_SERVICES_EMAIL=mbox1@....iam.gserviceaccount.com
export GCS_PRIVATE_KEY=`cat ./google-services-private-key.pem`

export GOOGLE_APPLICATION_CREDENTIALS=...e6.json
export SHEET1_ID=17J...
```

**Comment by dckc** [comment]
@kennyrowe , due to the Google service account headache, I'm just going to run this myself for the next little while. When we get the RPC stuff (#5386) working so we can skip the JS layer, let's revisit it.

**Comment by dckc** [comment]
I just met with Nalin, @btulloh , and @rowgraus to go over how the spreadsheet works, how to send tokens around, and a preview of how to run deploy scripts for trading.

**Comment by dckc** [comment]
@kennyrowe cool... so you figured out the Google service account stuff.

**Comment by dckc** [comment]
@kennyrowe was able to reproduce my results. Yay!
