### ISSUE TITLE
Slogger should not be able to cause consensus errors

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5463]
## Describe the bug
https://github.com/Agoric/agoric-sdk/pull/5455 hit a strange deployment integration test failure: https://github.com/Agoric/agoric-sdk/runs/6633516162

The loadgen monitor fell out of consensus with the validators. The reason is that the validators were loading the otel telemetry, which had a bug, and contaminated the execution of a delivery.

## To Reproduce
See artifact from failed run

## Expected behavior
A slogging error should not contaminate execution

## Platform Environment
CI

## Screenshots
Swing store diff:
```diff
--- /dev/fd/63  2022-05-28 03:05:40.411104952 +0000
+++ /dev/fd/62  2022-05-28 03:05:40.411104952 +0000
@@ -33657,2 +33657,2 @@
-set local.v1.lastSnapshot {"snapshotID":"fed245bb264369a0ae25d925996800ac91f8637f7ce8b8e331d3b4fe293fa1fe","startPos":{"itemCount":202}}
-set local.snapshot.fed245bb264369a0ae25d925996800ac91f8637f7ce8b8e331d3b4fe293fa1fe ["v1"]
+set local.v1.lastSnapshot {"snapshotID":"50f2dfe3aaa9a98e47fc273dbf6a698538b03f08b4b5122fb7ec385a6660d5aa","startPos":{"itemCount":202}}
+set local.snapshot.50f2dfe3aaa9a98e47fc273dbf6a698538b03f08b4b5122fb7ec385a6660d5aa ["v1"]
@@ -70665 +70665 @@
-set acceptanceQueue [{"type":"notify","vatID":"v4","kpid":"kp756"}]
+set acceptanceQueue [{"type":"notify","vatID":"v4","kpid":"kp756"},{"type":"send","target":"ko443","msg":{"methargs":{"body":"[\"getAssetKind\",[]]","slots":[]},"result":"kp725"}}]
```

Slog diff:
```
55964,55965c55964,55967
< {"type":"console","source":"vat","state":"delivery","crankNum":4733,"vatID":"v3","deliveryNum":163,"level":"log","args":["WARNING: delivery from remote triggered error:",{"code":"SQLITE_CONSTRAINT_PRIMARYKEY"}]}
< {"type":"console","source":"vat","state":"delivery","crankNum":4733,"vatID":"v3","deliveryNum":163,"level":"log","args":["Error happened while processing \"[\"receive\",[\"87:74:deliver:ro+59:rp+48;[\\\"getAssetKind\\\",[]]\"]]\""]}
---
> {"type":"syscall","crankNum":4733,"vatID":"v3","deliveryNum":163,"syscallNum":24,"replay":false,"ksc":["send","ko443",{"methargs":{"body":"[\"getAssetKind\",[]]","slots":[]},"result":"kp725"}],"vsc":["send","o-92",{"methargs":{"body":"[\"getAssetKind\",[]]","slots":[]},"result":"p-139"}]}
> {"type":"syscall-result","crankNum":4733,"vatID":"v3","deliveryNum":163,"syscallNum":24,"replay":false,"ksr":["ok",null],"vsr":["ok",null]}
> {"type":"syscall","crankNum":4733,"vatID":"v3","deliveryNum":163,"syscallNum":25,"replay":false,"ksc":["subscribe","v3","kp725"],"vsc":["subscribe","p-139"]}
> {"type":"syscall-result","crankNum":4733,"vatID":"v3","deliveryNum":163,"syscallNum":25,"replay":false,"ksr":["ok",null],"vsr":["ok",null]}
```

**Comment by warner** [comment]
I completely agree that slogging should not be allowed to cause an error.. I'm guessing the best way to fully ensure that is to catch+log+ignore any errors that occur within the slog code.

I don't understand how this particular example happened. The comms vat received a message, and somehow experienced a SQLite error while processing that message. The only place we're using SQLite is in the transcript storage, and comms doesn't use a transcript. So nothing should have been calling SQLite during that delivery.

And, the divergence in the slogfiles is a consequence of divergence in behavior: the comms vat performed a syscall (thus appending to the `acceptanceQueue`) in one variant. In the other variant, it experienced an error before it made that syscall. This isn't the slogfile's fault, and I'm not seeing any errors happening slogging.

So the real question is how that SQLite error happened, especially in a transcriptless vat.

The one SQL table we have uses `PRIMARY KEY (streamName, position)`. The `streamName` is just the vatID, I think, and `position` is the transcript entry number (basically `deliveryNum`). We're using SQLite in "auto-commit" mode, which means it does a commit as soon as the statement finishes. The LMDB commit happens significantly later (at the end of the block), and includes the deliveryNum. So if we commit to SQLite, but then crash before performing the LMDB commit, the next time we restart, we'll perform the same SQLite write as before. This was fine back when the streamStore was just a file with a write offset, but if overwrites cause SQLite problems, then we need to fix it.

Tasks:
* modify the way `streamStore` works to allow an overwrite of the same data as before
* figure out what vat's transcript was being written to in this incident (can't be comms, since comms doesn't have one)

**Comment by mhofman** [comment]
> I don't understand how this particular example happened. The comms vat received a message, and somehow experienced a SQLite error while processing that message.

The otel telemetry which handles slog events uses SQLite

**Comment by warner** [comment]
Ah, ok. So yeah, wrapping slog calls to catch+log+ignore errors is the way to go then.
