### ISSUE TITLE
Transcript replay should panic on delivery failure

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#5565]
## Describe the bug
As mentioned in https://github.com/Agoric/agoric-sdk/issues/5557:

> We should also make sure that any errors during replay (non-`ok` VatDeliveryResults) cause a replay failure (and ultimately a kernel panic).

This includes BYOD regardless of whether we do https://github.com/Agoric/agoric-sdk/issues/5564 or not.

## To Reproduce
See #5557

**Comment by warner** [comment]
* in `kernel.js` > `tryProcessMessage`, there's a `return processor(message).finally(() ..);`, does the return value of `finally()` also throw?
* if the processing of a message throws, we should set the `panic` flag, so that all subsequent attempts to call into the kernel will throw, rather than proceeding as if everything is ok
* all kinds of replay delivery errors (mismatched syscalls, missing syscalls, worker just ups and dies) should cause the `ensureVatOnline()` call to throw/reject, which should cause `processor()` to reject, which should set `panic` and reject, causing `controller.run()` to reject
  * the host application should halt if `controller.run()` ever rejects

**Comment by mhofman** [comment]
> * in `kernel.js > `tryProcessMessage`, there's a `return processor(message).finally(() ..);`, does the return value of `finally()` also throw?

Yes, `finally` passes through the exceptions if one happened.
