### ISSUE TITLE
migrate to @endo/errors package

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5672]
## What is the Problem Being Solved?

`assert` is a global in SES. However, IDEs don't know about it or its members. To allow automatic imports we have `@agoric/assert`, but it's useful outside of Agoric.

## Description of the Design

Move most of `@agoric/assert` to use `@endo/errors`. Move `NonNullish` checked cast to `@agoric/internal`.

# Acceptance

No more use of global `assert` in agoric-sdk. This will support getting assertion functions without having set up a SES environment.

**Comment by dckc** [comment]
@erights the little justification I was able to find on this was not sufficient to convince @turadg : https://github.com/Agoric/agoric-sdk/pull/5673#pullrequestreview-1020228726

**Comment by dckc** [comment]
@turadg as we discussed, I added a note to our [Coding Style](https://github.com/Agoric/agoric-sdk/wiki/Coding-Style):

> Note: pending resolution of [#5672](https://github.com/Agoric/agoric-sdk/issues/5672), within agoric-sdk, let's use the SES global rather than importing from `@agoric/assert`.
> That is: use `const { details: X, quote: q} from assert;`.

**Comment by abebeos** [comment]
Few comments from an outsider without full domain-knowledge (judging abstractly here).

* https://www.npmjs.com/package/ses?activeTab=readme vs.
* https://github.com/Agoric/agoric-sdk/tree/master/packages/assert

* SES seems "stronger" than `@agoric/assert`
  * => pick SES/standard
* `@agoric/assert` is an addition to an existent code-construct
  * => pick SES/standard

## code samples

```js
import { quote } from '@agoric/assert';
const { quote } = assert;

=> pick SES/standard


import { assert, details as X, quote as q } from '@agoric/assert';
const { details: X, quote: q } = assert;

=> pick SES/standard (quite clearly)
```

I fail to understand at this point why https://github.com/Agoric/agoric-sdk/pull/5673 is not going through.

The given rationales within https://github.com/Agoric/agoric-sdk/pull/5673#pullrequestreview-1020228726 (optics, IDE autocomplete) are weak in comparison to the above given assessments and to the (let's say) standard-procedure:

- avoid adding convenience-layers to standard (or quasi-standard) libs. Prefer to make a change-suggestion to the standard-lib (here: SES).


## Suggestion

* add a deprecation warning to `@agoric/assert` (without actually starting code conversion), pointing to the issue here.
* point to code examples / conversion examples, with tested search-replace patterns/regex.

**Comment by abebeos** [comment]
Oh, and as this issue is actually a question:

> deprecate @agoric/assert package?

Yes, clearly.

**Comment by abebeos** [comment]
Just saw this:

> An assertion library that keeps sensitive data outside of the Error.

If this is a standard-use-case, then possibly the `@agoric/assert` stuff should be suggested for inclusion into SES.

**Comment by turadg** [comment]
@abebeos can you expand on what your interest is in whether `@agoric/assert` exists? It has no impact on SES or Endo.

**Comment by abebeos** [comment]
@turadg me just looking through different '`technical debt`' issues, trying to identify "things I'd like to analyze/fix". While doing this I sometimes comment.

You wrote within: https://github.com/Agoric/agoric-sdk/pull/5673#pullrequestreview-1020228726
>I'd like to request that  we don't deprecate this package and instead explain why it exists.

May I ask why it exists?

**Comment by erights** [comment]
Hi @abebeos , appreciated. This outstanding question is indeed technical debt we need to resolve. Currently we use both styles:

```js
const { details: X, quote: q } = assert;
```
vs
```js
import { details as X, quote as q } from '@agoric/assert';
```
Aside from history, I don't see any good reason for these to coexist. We should consistently use one or the other. In addition, the `@agoric/assert`, as its name implies, exists at the `agoric-sdk` level, not the `endo` level, making it impossible to adopt it for general use without deeper intervention.

@turadg , do your reasons for keeping `@agoric/assert` still apply to our system after all the work you've done repairing our types? Are these reasons strong enough that you think we should move it to `@endo/assert` and adopt it everywhere? If not, can we repair whatever the remaining reasons are for `@agoric/assert` and then deprecate it, for eventual removal?

FWIW, for new code, I always use the `assert` global rather than the `@agoric/assert` package and have never noticed any resulting pain.

**Comment by erights** [comment]
Now that https://github.com/endojs/endo/pull/1334 and https://github.com/endojs/endo/pull/1350 have been merged, endo has fully moved from the old
```js
assert(cond, X`...`);
```
style to the new
```js
cond || Fail`...`;
```
style. @kriskowal has already started turning the endo release crank, after which `Fail` will be available for use in agoric-sdk as well. Once it is, we can simplify, repair, and complete https://github.com/Agoric/agoric-sdk/pull/6482 , consistently using this style throughout agoric-sdk as well. If we revive and complete #5673 first, then #6482 can be simpler. Otherwise, we'd need #6482 to additionally export `Fail` from the `@agoric/assert` package in the meantime. 

So resolving this issue now is timely. Thanks!

**Comment by abebeos** [comment]
Though I'm loosing it a little bit here, I try one more (very general) comment (again: outsider, with domain-knowledge-free expectations) :

I would expect

```js
const { details: X, quote: q } = assert;
```

and possibly(!) an additional

```js
const { details: X, quote: q } = assert-intra;
```

for an assert with the additional functionality ("An assertion library that keeps sensitive data outside of the Error.").

**Comment by erights** [comment]
Hi @abebeos , the functionality you mention, "An assertion library that keeps sensitive data outside of the Error", is already functionality provided by the `assert` global provided by SES. See https://github.com/endojs/endo/blob/master/packages/ses/src/error/README.md

I don't think there's any reason to introduce a distinct `assert-intra`.

**Comment by abebeos** [comment]
> I don't think there's any reason to introduce a distinct `assert-intra`.

Agree, there isn't.

I was under the impression that this "sensitive data" functionality is exclusive to `@agoric/assert`. As it's not, I just have one more reason to say "yes" to the removal question.

**Comment by turadg** [comment]
>> I'd like to request that we don't deprecate this package and instead explain why it exists.

> May I ask why it exists?

For me, as a developer of agoric-sdk, it was valuable to be able to type as assertion export in my IDE and autocomplete to get the import. That's what I was referring to in the preceding sentence,
> Having that export would let IDEs autocomplete when someone tries to use X as a function

Another advantage of keeping this package is it informs the developer of what to do when `globalThis.assert` isn't defined,
https://github.com/Agoric/agoric-sdk/blob/4425dc44a95d750a4893cf06cc2135b784d496bf/packages/assert/src/assert.js#L28-L34

> If we revive and complete https://github.com/Agoric/agoric-sdk/pull/5673 first, then https://github.com/Agoric/agoric-sdk/pull/6482 can be simpler.

What's simpler about,
```
const { details: X, Fail } = assert;
```
than
```
import { assert, details as X } from '@agoric/assert';
```
? They're both used in the PR. I do think it may be worth consolidating, though I would ask that we consolidate around the import. I'm not clear on the arguments why not to, within this repo.

> Otherwise, we'd need https://github.com/Agoric/agoric-sdk/pull/6482 to additionally export Fail from the @agoric/assert package in the meantime.

Yes, I'm happy to do that. https://github.com/Agoric/agoric-sdk/pull/6566

**Comment by abebeos** [comment]
My understanding is that there are now 2 possible styles for the assertion, the new one being:

> ```js
> cond || Fail`...`;
> ```

This looks a bit "out of the blue" - is this a standard construct?

I would prefer to see `assert` to be able to quickly identify an... assertion!

@turadg 

>What's simpler about,

`const { details: X, Fail } = assert;`

I identify it very(!) clearly as simpler.

`import { assert, details as X } from '@agoric/assert';`

I identify this one even as "strange", and have immediately the urge to "normalize its size down".

But then, it is not always about the simplicity or strangeness or fancy IDE support.

Most importantly:
* what is standard?
* and: is an additional package really necessary?

Additional package means additional maintenance, error sources, and especially deviation from standard behaviour.

There should be heavy reasons to introduce them or to keep them introduced.

(please feel free to ignore this 100% - in the end, what do I know? )

**Comment by turadg** [comment]
@kriskowal has agreed to have an `@endo/assert`, as a ponyfill for the assert shim. I've renamed this issue to be about migrating to that.

The `NonNullish` checked cast isn't on the `assert` global so it won't go along. We'll move it to agoric/internal instead.

**Comment by turadg** [comment]
Reassigning to @erights who's working on it in https://github.com/Agoric/agoric-sdk/pull/8781

**Comment by erights** [comment]
At https://github.com/endojs/endo/pull/2042#issuecomment-1939287596 I suspect that the @endo/errors package may not be successfully exporting the types it should. 

- [ ] I need to figure this out before we switch agoric-sdk to using it.

**Comment by turadg** [comment]
Another problem with expecting the global `assert` is it's only available as a side-effect of Endo being inited. If you import something like `@agoric/ertp`, [you can't use it until Endo is inited](https://github.com/Agoric/agoric-sdk/pull/9481#discussion_r1635601927) but you don't know that and nothing says so.

If `@agoric/ertp` used the exports from `@endo/errors` then there would be no reliance on side-effects and that package would encapsulate shimming as needed.

Shall we move all use of `assert` global to an import? If so shall it be part of this Issue or another?

**Comment by erights** [comment]
> Shall we move all use of assert global to an import? 

Yes, for everything that can depend on @endo/errors without introducing a cyclic dependency. This includes all of the agoric-sdk repo and almost all of the endo repo.

> If so shall it be part of this Issue or another?

This issue seems a like fine place.
