### ISSUE TITLE
ensure agd has ClawbackVestingAccount etc. from ag0

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/Agoric#5690]
Comparing the two branches used for agd vs ag0, there seems to be a delta.  In order to ensure that things function as expected when upgrading from ag0 to agd, agd should support all functionality that exists in ag0 today

 [cosmos-sd diff between Agoric and ag0 branches](https://github.com/agoric-labs/cosmos-sdk/compare/Agoric...agoric-labs:cosmos-sdk:Agoric-ag0?expand=1)

**Comment by JimLarson** [comment]
The diff link above is misleading. It is *not* displaying the differences between the tips of the two branches. With three dots ("...") between the branch names in the URL it displays commits which exist in the target but not in the base. Because the clawback vesting changes were landed on the `Agoric-ag0` branch via cherry-pick, these show up in the diff. When you look at the two dots ("..") URL, it displays both the commits that are only in the target AND commits which are only in the base. When you do this, the clawback vesting differences disappear. This matches direct inspection of the `Agoric` branch where you see the changes. See https://github.com/agoric-labs/cosmos-sdk/compare/Agoric..agoric-labs:cosmos-sdk:Agoric-ag0
