### ISSUE TITLE
ag0 intermittent restart failure due to gas calculation

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#5694]
## Describe the bug

A number of Agoric mainnet0 validators have been jailed unexpectedly, due to failure of nodes to restart. Logs seem to include:

```
... error during handshake: error on replay: wrong Block.Header.LastResultHash.  Expected E6358A...
```

Diagnosis: https://github.com/Agoric/agoric-sdk/issues/5694#issuecomment-1183656553

## To Reproduce

see https://github.com/Agoric/agoric-sdk/issues/5694#issuecomment-1171637226

## Expected behavior

mainnet0 nodes restart reliably, avoiding jailing

## Platform Environment

ag0. (_IOU git hash_)

cc @dtribble @zmanian @jessysaurusrex @arirubinstein 

## Additional Context

see also:
 - #5699

**Comment by 48198880** [comment]
My validator was jailed ,when I try to restore my validator from three snapshot from different source with the same error.
<img width="1040" alt="630225238" src="https://user-images.githubusercontent.com/24585220/176730221-1eeda02f-1fa8-46e2-8f4f-c5a2756e292d.png">

**Comment by 48198880** [comment]
> My validator was jailed ,when I try to restore my validator from three snapshot from different source with the same error. <img alt="630225238" width="1040" src="https://user-images.githubusercontent.com/24585220/176730221-1eeda02f-1fa8-46e2-8f4f-c5a2756e292d.png">

6:26PM INF Starting multiAppConn service impl=multiAppConn module=proxy
6:26PM INF Starting localClient service connection=query impl=localClient module=abci-client
6:26PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
6:26PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
6:26PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
6:26PM INF Starting EventBus service impl=EventBus module=events
6:26PM INF Starting PubSub service impl=PubSub module=pubsub
6:26PM INF Starting IndexerService service impl=IndexerService module=txindex
6:26PM INF ABCI Handshake App Info hash="9���7��ؾ�c�^щi(٢�BK�\b��p���\x0f�" height=5546474 module=consensus protocol-version=0 software-version=HEAD-a2a0dc089ca98b9eae50802d8ed866bf8c209b06
6:26PM INF ABCI Replay Blocks appHeight=5546474 module=consensus stateHeight=5546474 storeHeight=5546475
6:26PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected F8C189FFC0F35CFC198CA4D0AFD19DED88AA1AA8D15AAAB7B27F049BB9E74D00, got FDD7963253007782A34A316A5A3DB3935C932269CC2A33A5FA2DAD72E730F768

**Comment by jessysaurusrex** [comment]
There is a known issue in Tendermint v 0.35 in the p2p layer that has been causing app hash issues on other networks, notably Celestia. As mainnet-0 is using an earlier version of Tendermint (that is expecting an upgrade shortly), we can rule out that this specific known issue is the cause of unexplained jailing.

**Comment by dtribble** [comment]
Current theory is these Tendermint fixes are needed.

https://github.com/tendermint/tendermint/issues/7992

https://github.com/tendermint/tendermint/issues/7994

This will require a software upgrade and chain restart

**Comment by arirubinstein** [comment]
I was able to reproduce this, however only after restarting ag0 and in replay

```
8:10PM INF minted coins from module account amount=7922809ubld from=mint module=x/bank
8:10PM INF executed block height=5549917 module=state num_invalid_txs=0 num_valid_txs=1
8:10PM INF commit synced commit=436F6D6D697449447B5B383720383520323139203820333920343320323720313139203138302034382031353320323420313338203138312037332039302031323020323230203734203837203136302031353920313230203233362033382031363720323920313138203234312032392039322037305D3A3534414635447D
8:10PM INF committed state app_hash=5755DB08272B1B77B43099188AB5495A78DC4A57A09F78EC26A71D76F11D5C46 height=5549917 module=state num_txs=1
8:10PM INF indexed block height=5549917 module=txindex
panic: Failed to process committed block (5549918:1F664E7767B97A83C99EAE565E71FB73867475BD5E5DB5AEEE8B5E7496F19D47): wrong Block.Header.LastResultsHash.  Expected 0508CA168F763035EAA8353B8B7A79DC48369D44072D6A00200EAED3580A74B6, got 093C37FC4838FA09351684B94A973F02C70F0E9613BC905F90A103DC1149F5FC

goroutine 54 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000d51880, 0x0)
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x1605
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x8c

8:12PM INF ABCI Handshake App Info hash="WU�\b'+\x1bw�0�\x18��IZx�JW��x�&�\x1dv�\x1d\\F" height=5549917 module=consensus protocol-version=0 software-version=HEAD-a2a0dc089ca98b9eae50802d8ed866bf8c209b06
8:12PM INF ABCI Replay Blocks appHeight=5549917 module=consensus stateHeight=5549917 storeHeight=5549918
8:12PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 0508CA168F763035EAA8353B8B7A79DC48369D44072D6A00200EAED3580A74B6, got 093C37FC4838FA09351684B94A973F02C70F0E9613BC905F90A103DC1149F5FC
Usage:

```

**Comment by zmanian** [comment]
@arirubinstein Could it be something similar to this

https://github.com/PeggyJV/sommelier/pull/113/files

**Comment by JimLarson** [comment]
Repeating comments I made on Slack, we have *some* of those sommelier changes in app.go on Agoric/ag0, but some differences:

- In begin blockers we're missing ibctransfer, auth, bank, gov, crisis, genutil authz, feegrant, parms, and gravity types.
- In end blockers, we're missing ibchost, ibctransfer, capability, auth, bank distr, slashing, mint, genutil, evidence params, upgrade, gravity, and allocation types. And feegrant and authz are swapped from the sommelier order.

I don't have a sense for what's appropriate for ag0 or necessary to fix the issues.

**Comment by EricBolten** [comment]
Re: what @zmanian was suggesting, does the block before the mismatch contain an IBC message? I believe the issue in the mentioned PR from Somm is that `BeginBlocker` order matters for IBC modules that use capabilities and get sealed. Based on https://github.com/Agoric/ag0/blob/f62283177819d6bba0babe556292c0fb7c0a8239/app/app.go#L273-L276, if it's the same issue, it seems like you'd need both `ibchost` and `ibctransfertypes` to be explicitly set to come after `capabilitytypes` in `SetOrderBeginBlockers`. IIRC though we observed this as an `AppHash` mismatch rather than `LastResultHash`.

**Comment by dtribble** [comment]
There was no IBC txns before it.

**Comment by arirubinstein** [comment]
I can't reproduce in cosmoshub-4

**Comment by arirubinstein** [comment]
To document some findings, for some reason it appears that during replay, DeliverTx consumes less gas for a transaction than it does in a continuously running node.  Additionally it was possible to run into the error for the first time on a running node with a ctrl-c, and also once during an execution where consensus failed however the node stayed alive.

We witnessed this issue persist across transactions of types:
- voting
- send
- undelegate

I wasn't able to reproduce this on cosmoshub-4

**Comment by bananooo-zhang** [comment]
> To document some findings, for some reason it appears that during replay, DeliverTx consumes less gas for a transaction than it does in a continuously running node. Additionally it was possible to run into the error for the first time on a running node with a ctrl-c, and also once during an execution where consensus failed however the node stayed alive.
> 
> We witnessed this issue persist across transactions of types:
> 
> * voting
> * send
> * undelegate
> 
> I wasn't able to reproduce this on cosmoshub-4

and edit moniker

**Comment by ciscohite** [comment]
> I was able to reproduce this, however only after restarting ag0 and in replay
> 
> ```
> 8:10PM INF minted coins from module account amount=7922809ubld from=mint module=x/bank
> 8:10PM INF executed block height=5549917 module=state num_invalid_txs=0 num_valid_txs=1
> 8:10PM INF commit synced commit=436F6D6D697449447B5B383720383520323139203820333920343320323720313139203138302034382031353320323420313338203138312037332039302031323020323230203734203837203136302031353920313230203233362033382031363720323920313138203234312032392039322037305D3A3534414635447D
> 8:10PM INF committed state app_hash=5755DB08272B1B77B43099188AB5495A78DC4A57A09F78EC26A71D76F11D5C46 height=5549917 module=state num_txs=1
> 8:10PM INF indexed block height=5549917 module=txindex
> panic: Failed to process committed block (5549918:1F664E7767B97A83C99EAE565E71FB73867475BD5E5DB5AEEE8B5E7496F19D47): wrong Block.Header.LastResultsHash.  Expected 0508CA168F763035EAA8353B8B7A79DC48369D44072D6A00200EAED3580A74B6, got 093C37FC4838FA09351684B94A973F02C70F0E9613BC905F90A103DC1149F5FC
> 
> goroutine 54 [running]:
> github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000d51880, 0x0)
>         github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x1605
> created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
>         github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x8c
> 
> 8:12PM INF ABCI Handshake App Info hash="WU�\b'+\x1bw�0�\x18��IZx�JW��x�&�\x1dv�\x1d\\F" height=5549917 module=consensus protocol-version=0 software-version=HEAD-a2a0dc089ca98b9eae50802d8ed866bf8c209b06
> 8:12PM INF ABCI Replay Blocks appHeight=5549917 module=consensus stateHeight=5549917 storeHeight=5549918
> 8:12PM INF Replay last block using real app module=consensus
> Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 0508CA168F763035EAA8353B8B7A79DC48369D44072D6A00200EAED3580A74B6, got 093C37FC4838FA09351684B94A973F02C70F0E9613BC905F90A103DC1149F5FC
> Usage:
> ```

It happens every time we restart our node.

**Comment by arirubinstein** [comment]
I'm going to upload some debugging artifacts here:
[select_4_right.log](https://github.com/Agoric/agoric-sdk/files/9067078/select_4_right.log)
[select_4_left.log](https://github.com/Agoric/agoric-sdk/files/9067079/select_4_left.log)
[gasusage_5577904_normal_stripped.log](https://github.com/Agoric/agoric-sdk/files/9067080/gasusage_5577904_normal_stripped.log)
[gasusage_5577904_crash_stripped.log](https://github.com/Agoric/agoric-sdk/files/9067081/gasusage_5577904_crash_stripped.log)
[gasusage_5577904_crash.log](https://github.com/Agoric/agoric-sdk/files/9067082/gasusage_5577904_crash.log)
[gasusage_5577904_normal.log](https://github.com/Agoric/agoric-sdk/files/9067083/gasusage_5577904_normal.log)

**Comment by arirubinstein** [comment]
[gas_newdebug_1.log.zip](https://github.com/Agoric/agoric-sdk/files/9067891/gas_newdebug_1.log.zip)
[gas_newdebug_full.log.zip](https://github.com/Agoric/agoric-sdk/files/9067896/gas_newdebug_full.log.zip)

**Comment by arirubinstein** [comment]
https://gist.github.com/arirubinstein/e6d94ce6aa3e6dd3b921f92e12e80543

**Comment by dckc** [comment]
update: https://commonwealth.im/agoric/discussion/6209-issue-update-possible-state-corruption-after-node-reboot-impacting-agoric-validators

**Comment by ebuchman** [comment]
> https://gist.github.com/arirubinstein/e6d94ce6aa3e6dd3b921f92e12e80543

Based on this, it looks like both the tendermint abci replay handshake and the blockchain reactor are executing the same blocks, which seems like it could potentially explain the issue. But even if we disable the blockchain reactor (`fast_sync = false`), the bug still persists.

**Comment by ebuchman** [comment]
I think the idea of the block being executed twice is a false alarm.

From what I'm seeing in replications, the failure happens in scenarios where we store a block but crash before executing it. As an example of what this looks like on restart (though the block numbers will vary across replications):

```
2:30AM INF ABCI Replay Blocks appHeight=5577933 module=consensus stateHeight=5577933 storeHeight=5577934
```

So we crashed during execution of block 5577934 - it was stored but not fully executed. So during replay on restart, that block is executed, but it seems it's producing the wrong results, since when we then receive the next block in consensus from another peer (ie. 5577935), the LastResultsHash is not what we expect.

To debug further, I think we would want to look at the `types.NewResults(abciResponses.DeliverTxs)` we're producing when executing block 5577934 and compare that with what we'd get from querying the tx results from an online peer for the same block. But I imagine that would just confirm that the difference is in a gas computation, as already reported. It might give more clues though for where to go from there.

**Comment by ebuchman** [comment]
A couple more observations/thoughts:

- it seems this is reproducible even without replay! ive seen an instance where there was no abci replay but the first new block after restart caused the consensus failure
- I was able to reproduce it with v0.34.14 which is the tm version used by sdk v0.44.5 (https://github.com/cosmos/cosmos-sdk/blob/v0.44.5/go.mod#L49)
- it seems like it might be the case that it only happens when the first block after restart contains a tx (hard to confirm this but have a bit of anecdotal evidence so far)

**Comment by ebuchman** [comment]
Looking more closely at the gas traces in https://github.com/Agoric/agoric-sdk/issues/5694#issuecomment-1178186934 it seems the first difference between normal and crashed appears in the `capability` store. So seems like there's some issue there. I think @zmanian was suggesting above it may be an issue there, but maybe for a different reason than proposed (ie. not related to IBC and the wiring order) ?

**Comment by ebuchman** [comment]
Will note I tried adding all the changes from the linked sommelier PR (only difference being the missing somm packages and the authz/feegrant order in endblock) and still no dice.

Also realizing that the gas logs from above are all referencing the InfiniteGasMeter which I don't believe actually impacts the real gas consumed, so it pointing to some different gas consumption in the capability store may be a red herring since it's probably just due to the difference between a normal node running and the crashed node booting and those gas differences aren't part of consensus. So would need those equivalent logs from the correct gas meters.

**Comment by ebuchman** [comment]
Ok I think I might have figured it out!

It seems Agoric's consensus params do not set a max gas. 

The SDK seems to think this is ok, but I think that might actually be a bug!

**Comment by ebuchman** [comment]
Ok I believe @alexanderbez and I confirmed this is the issue. There is a bug in the SDK that makes it so infinite gas does not work across restarts. This will be a state transition breaking change to fix in the SDK, I'll open an issue about it.

For agoric's case, it should be possible to fix it without a hard fork by passing a parameter change proposal to set a finite max gas. 

For clarity, we're talking about the `max_gas` parameter in https://main.rpc.agoric.net/consensus_params. It's set to `-1` which means infinite. It needs to be something positive and finite.

**Comment by jessysaurusrex** [comment]
Thank you for the extra eyes and fire power on this one, @ebuchman and @alexanderbez! Very happy to hear that there's a fix we can apply on our end of things that mitigates the issue moving forward -- automatically applied governance params ftw!

**Comment by ebuchman** [comment]
So in trying to write this up I've realized the situation is a bit more complex and it's not clear anymore that the issue is the max gas setting. 

Trying to understand how the gas computation was wrong (it looked like gas was accumulating across begin block and txs) Bez and I realized that Agoric's AnteHandler may be missing a critical decorator for resetting the GasMeter for each tx, namely the NewSetUpContextDecorator which should be the first one. Compare from simapp: https://github.com/cosmos/cosmos-sdk/blob/33dbf6a795e68c744a2c312b76d41614b3563c01/x/auth/ante/ante.go#L41-L55

Agoric's AnteHandler does not have this:
https://github.com/Agoric/ag0/blob/80bde6a67813af64110de1dbfa4f26c3b1a688e9/app/ante_handler.go#L35-L50

It's hard to confirm a fix without a corresponding testnet to test against but at least trying to explain everything we're learning is surfacing more info about what the actual problem could be 😅 . The fact that this decorator is missing seems to definitely be a bug and should also be corroborated by larger than expected `gas_used` being returned by agoric txs, and gas usage accumulating across txs in a block (believe this is confirmed by eg https://ping.pub/agoric/blocks/5577877) .

Unfortunately if this is indeed the issue it would probably require a hard fork to fix.

**Comment by arirubinstein** [comment]
This appears to be the case, as transactions currently exhibit a rolling total of gas usage:
e.g.
- https://ping.pub/agoric/tx/24A6E714DD855985387A7B38838CECC43DCB5BB005357211EAC7E5CB1166517D
- https://ping.pub/agoric/tx/CB31224DBA99667A3949F0A5165C7C7D1A826A69E0FB4526A524ADE867FD0EFC
- https://ping.pub/agoric/tx/B88021A86343292273BE6444AC022D0A99C05E6D1ABC0E03DE214D0F7AE0F995
- https://ping.pub/agoric/tx/3A3BD0EFDE0ECD472BB483CFAEA04F83772A35FA1911CCC8E7F8ACE72AC44222

**Comment by dckc** [comment]
Note https://github.com/Agoric/ag0/releases/tag/agoric-upgrade-6 31c78ba 

@ari is coordinating testing in [Agoric Discord](https://agoric.com/discord)

**Comment by dckc** [comment]
## Test participants report no failures after hours of regular restarts

> alchemydc: everybody on agoric-upgrade-6 should schedule restarts every 5m or so for the next 24h or so to see if we can trigger the dreaded apphash bug!
...
> polkachu | polkachu.com: Restarted the service >10 times in the past hours with cron job. Everything is fine.
> 0xAN | Nodes.Guru: All ok for now with every 5 min restarts (runs ~8 hours)
> alkadeta: Same. Restarted 26 times with 30 minutes intervals. Missed 1 block in total.

for reference:

Upgrade to agoric-upgrade-6
Voting Time: 2022-07-19 14:11 - 2022-07-19 15:11
https://ollinet.explorer.agoric.net/agoric/gov/2

https://github.com/Agoric/ag0/releases/download/agoric-upgrade-6/ag0-agoric-upgrade-6-linux-amd64?checksum=sha256:12c6bd112e2cde3583739871a3ede6acdcdfe019cdc9dbf707a356be517dccea

### cumulative gas status?

I don't see info on this particular bit:

> alchemydc: we should also verify that the cumulative gas bug is fixed on this testnet now

**Comment by dckc** [comment]
cumulative gas status fix is confirmed:

> alchemydc: yes, when sending TX's on this testnet, we see that the gas does not increase TX over TX, like it does on mainnet0

Note also his summary of testing results:
https://commonwealth.im/agoric/discussion/6256-update-2-root-cause-identified-for-node-restart-issues-next-steps-for-improving-network-stability-etc?comment=26390

and proposal to upgrade the network:
https://ping.pub/agoric/gov/9

[agoric-upgrade-6](https://github.com/Agoric/ag0/releases/tag/agoric-upgrade-6) 31c78ba evidently addresses this issue to the satisfaction of a number of our validators.
