### ISSUE TITLE
need cosmic-swingset to pinVatRoot('bootstrap'), to enable some post-launch upgrades

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5771]
## What is the Problem Being Solved?

#5740 describes a change to the chain's "core bootstrap" code to support future kernel upgrade which introduce new objects (in particular new devices) after the kernel has been initialized. It adds methods to the bootstrap vat's root object, which can be invoked from outside the kernel by calling something like `controller.queueToVatRoot('produceItem', newDeviceNode)`. Once these objects are injected, we can either use the existing `bridgeCoreEval` code to evaluate JS that fetches those objects/devices with `consume`, or we can use a new method (sitting next to the new `produceItem`) that evaluates JS through a different `queueToVatRoot` call.

However for any of this to work, the root object must still be around by the time we do the upgrade. The `bootstrap()` message (enqueued during `initializeSwingset()`) keeps that object around until it gets delivered (run-queue messages hold refcounts on their targets), but after delivery, there may be nothing still referring to the vat-bootstrap root object. If so, the kernel will deliver a `dispatch.dropExport()`, and the vat-bootstrap liveslots will free it. After that point, `queueToVatRoot` will fail, because the target is gone.

To avoid this, and preserve our options for upgrade, we need to change this code:

https://github.com/Agoric/agoric-sdk/blob/1dd584b195212705b1f74a8c89b7f3f121640e41/packages/cosmic-swingset/src/launch-chain.js#L104

to do a `controller.pinVatRoot('bootstrap')` after the `initializeSwingset` call.

I'm not 100% positive that will work.. all the `pinToVatRoot` calls I do in swingset unit tests are done after we've built the controller (`makeSwingsetController`), and before the first call to `await controller.run()`. Those tests only ever launch the kernel once, but the real chain separates initialization from launch (because it will launch every time the kernel process is restarted). So I'll have to double-check that the initialized-but-not-launched state is suitable for `pinVatRoot` to work. I'm pretty sure it will.

## Description of the Design

Add `c.pinVatRoot('bootstrap')`.

## Security Considerations

This causes one extremely high-authority object to stick around longer, however if was previously being collected right away (i.e. if `pinVatRoot` was actually necessary), then nothing in a vat had a reference to it, so the only newly-empowered code is outside the kernel, which is a place with a lot of power anyways.

## Memory Considerations

This might cause objects in other vats to be retained longer than expected, if they were being kept alive by something in the root vat. I think the existing `bridgeCoreEval` callback was keeping the main `produce`/`consume` promise tables alive, and that probably keeps everything else touched during startup alive, so I don't expect this to cause a change to the object graph.

## Test Plan

I really don't know how to unit test this, partially because the only tests we have in cosmic-swingset are coarse integration tests. What I'd love to have is a way to exercise a `controller.queueToVatRoot('produceItem')` somehow in a locally-launched application.

cc @michaelfig 

I think I know how to add this myself, but to write a test I'll need help.

**Comment by FUDCo** [comment]
`controller.pinVatRoot()` is (ultimately) implemented by directly incrementing the kernel DB's refcount for the root object.  Since it's a controller method, you obviously need the controller itself to invoke it, which necessarily means you must call `makeSwingsetController` first (i.e., you can't do it right after `initializeSwingset`).  However, it shouldn't matter if there's a gap between `initializeSwingset` and `makeSwingsetController` nor should it matter much what happens during that gap, since no GC activity will happen prior to `controller.run()` and it's the GC of the bootstrap root that you're trying to prevent. So calling `controller.pinVatRoot()` right after `makeSwingsetController` should have the desired effect of keeping the bootstrap vat alive so its other services can be called upon in the future.

However, a concern I have is what happens if there's a cosmic-swingset restart (that is, a regular host restart with replay, not the vat-specific restart associated with upgrade).  Since `makeSwingsetController` will be called each time, I think there's a risk that if we naively call `pinVatRoot` unconditionally at that point, then we risk having the bootstrap root refcount increment each time.  Although this is ugly, it's not by itself the end of the world.  HOWEVER, since such restarts are an operational activity on behalf of the validator they happen outside consensus, so making permanent modifications to the kernel DB state as part of this could result in consensus breakage if we're not careful.

Off the top of my head I can think of three possible strategies for dealing this: 

1. Modify cosmic-swingset to immediately create a controller after calling `initializeSwingset`, pin the vat root, and then abandon the controller.  I'm not sure how this interacts with the live state of the kernel, however, if there's not an explicit shutdown of some kind as part of abandoning the controller.  If we take this route it will need some thought.
2. Add a configuration flag to the swingset configuration definition so that a vat can be configured to be born in a pinned state.  This seems like a cleaner approach, but it does introduce some engineering ritual (though arguably quite a bit less than what would be required to try to handle this in cosmic-swingset host logic).
3. Introduce a policy that the bootstrap vat is just automatically born pinned.  The bootstrap vat is already special in a couple of other ways, so this would be very simple to implement.  However, doing this would foreclose the possibility of allowing the bootstrap vat to be sloughed off in applications where it is not needed after startup, though I'm not at all sure such use cases loom very large on our current roadmap.

My aesthetic preferences would argue for Option 2, though we might prefer Option 3 in the interest of speed and expediency.

**Comment by warner** [comment]
Yep, I agree with all of that. The application restart problem is why I didn't want to do it after `makeSwingsetController()`, but yeah I forgot that you can't call a controller method without a controller.

Option 1 would be technically possible but it would also cause a whole lot of workers to be spun up for a brief moment, just to make one DB change, so I want to avoid that one. I dislike option 3 for the same reasons.. there's a nice consistency to every object from every vat being kernel GCed in the same way.

A configuration flag is pretty clean, but a 4th option would be an additional exported function (sitting next to `initializeSwingset`) which accepts the same swing-store and a vat name, and it uses the DB to look up the vatID, find the c-list, find the root object's kref, increment its refcount, and return. Basically everything `controller.pinVatRoot()` does except as a standalone function (using a short-lived `kernelKeeper` instance, like how `initializeKernel` is implemented).

Actually, now that I think about it, the configuration flag feels more tidy. `config.vats.bootstrap.pinRoot = true` maybe. There's already code to pin the vat-admin root, inside the "loop through all vats" step:

https://github.com/Agoric/agoric-sdk/blob/7e4b07bad6298b705fc85ec3fc4f535a9331d9e8/packages/SwingSet/src/controller/initializeKernel.js#L104-L110

so it could just be an extension of that.

So, a little more kernel code, but that means we can write a unit test for it, at least on the swingset side.

To test cosmic-swingset side, what I'd do is start a chain kernel (maybe the "sim-chain" mode?) without the config flag, then dump the DB to 1: find the kref for vat-bootstrap's `o+0`, 2: find the refcount for that kref. Then add the config flag, do that again, and confirm that the refcount is one higher.
