### ISSUE TITLE
replaying chain send `get` `actionQueue.tail` resulted in `null`

### ISSUE THREAD

**Issue by michaelfig** [Agoric/Agoric#5911]
## Describe the bug

Error when replaying during deployment test CI https://github.com/Agoric/agoric-sdk/runs/7714655369?check_suite_focus=true#step:10:11261 :

```
stage-1: chain: portHandler threw (Error#1)
stage-1: chain: Error#1: fatal: replaying chain send [1,"{\"key\":\"actionQueue.tail\",\"method\":\"get\"}"] resulted in "null"; expected "2"
stage-1: chain: 
stage-1: chain:   at flushChainSends (packages/cosmic-swingset/src/chain-main.js:299:15)
stage-1: chain:   at blockingSend (packages/cosmic-swingset/src/block-manager.js:218:13)
stage-1: chain:   at toSwingSet (packages/cosmic-swingset/src/chain-main.js:521:12)
stage-1: chain:   at portHandlers.<computed> (packages/cosmic-swingset/src/chain-main.js:232:22)
stage-1: chain:   at Object.fromGo (packages/cosmic-swingset/src/chain-main.js:249:31)
stage-1: chain: 
stage-1: chain: panic: Error: fatal: replaying chain send [1,"{\"key\":\"actionQueue.tail\",\"method\":\"get\"}"] resulted in "null"; expected "2"
stage-1: chain: 
```

## To Reproduce

Run CI.  Sometimes it fails like this.

## Expected behavior
No CI failure.

## Platform Environment
 CI

## Additional context

Discovered in the course of trying to land https://github.com/Agoric/agoric-sdk/pull/5895

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by michaelfig** [comment]
Replaying transactions isn't necessarily deterministic.  This requirement should be loosened.

**Comment by mhofman** [comment]
This error started happening on the benchmark machine between https://github.com/Agoric/agoric-sdk/compare/00d565d7fa87c55f849825aed5c26b43cd9a82d4...7f294a69eeae68235d8b485c529cccb9246b2c70 (I suspect https://github.com/Agoric/agoric-sdk/pull/5892) and got seemingly resolved between https://github.com/Agoric/agoric-sdk/compare/aff48fd1b5c0...a679fa561bb6, however I'm not 100% sure since right after the loadgen test started experiencing another [failure, in XS itself](https://github.com/Agoric/agoric-sdk/issues/5976)

```
0 4700232 daily-perf-914fc4c5a31f 2022-08-08 22:33:27.457786812 +0000 3
2 4338484 daily-perf-e7e652986cb5 2022-08-08 01:33:10.085955968 +0000 3
2 3292188 daily-perf-cf97ba310fb5 2022-08-07 06:35:13.590091804 +0000 3
2 486812 daily-perf-a679fa561bb6 2022-08-06 09:50:07.074302811 +0000 3 // xsMemory failure related SIGABRT
2 514808 daily-perf-aff48fd1b5c0 2022-08-06 07:26:17.261245675 +0000 3 // actionQueue.tail related SIGABRT
2 514356 daily-perf-f5cf38e954ee 2022-08-06 05:02:19.948927865 +0000 3
2 514800 daily-perf-74885306b09d 2022-08-06 02:38:41.157575496 +0000 3
2 512664 daily-perf-7f294a69eeae 2022-08-05 08:28:13.577604859 +0000 3 // actionQueue.tail related SIGABRT
0 4695976 daily-perf-00d565d7fa87 2022-08-05 06:03:56.213017691 +0000 236
```

**Comment by mhofman** [comment]
> Replaying transactions isn't necessarily deterministic. This requirement should be loosened.

Could you clarify what you mean here? Why would this be non-deterministic?

**Comment by mhofman** [comment]
Assigning self as I'm looking at the queue logic now in the context of https://github.com/Agoric/agoric-sdk/issues/5966

**Comment by mhofman** [comment]
The current design of priority processing does not require `actionQueue` changes. I am also still dumbfounded why the result received from go would have diverged here. I think this issue should be reassigned, and likely removed from vaults release.

**Comment by JimLarson** [comment]
Consider a stretch goal for Vaults release, o/w defer to next.

**Comment by mhofman** [comment]
While trying to reproduce #6907, Ari performed a tendermint rollback, which triggered this bug. After thinking about it, the problem is that our hangover consistency consumes the action queue, then replays the chain sends. When doing the latter, the action queue is already empty so replaying the iteration does not produce the expected results.

Solution is to not manually consume the action queue when detecting a hangover.
