### ISSUE TITLE
Loadgen test of PSM

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#6004]
## What is the Problem Being Solved?

We need to add support for PSM in the loadgen to get some performance numbers for the chain when only that contract is running

## Description of the Design

Add PSM loadgen contract (based on agsolo deploy scripts)
Bootstrap chain with a config with PSM enabled and no other contracts (possibly PSM prod config)
Perform loadgen with just PSM load.

**Comment by dckc** [comment]
I got started on a `psm-load.js` script: https://github.com/Agoric/agoric-sdk/pull/6015#issuecomment-1222579957

It's a 1-file script using [zx](https://www.npmjs.com/package/zx). The PSM-only release might not support deploy scripts at all.

**Comment by dckc** [comment]
## A Sample run of 10 trades

elapsed time: 42-60sec
2 didn't get into the list of wallet offers at all, somehow.
_p.s. because a transaction had already been submitted from the account in the same account_

```
instagoric/bases/shared/instagoric-server$ node psm-load.mjs 10 3 >,psm.log 2>&1 &
$ git log --oneline -1
a21a19f (HEAD -> dc-psm-load, origin/dc-psm-load) feat(psm-load): manyTrades
```

Agoric SDK version:
```
agoric-sdk/packages/cosmic-swingset$ git log --oneline -1
afabe7ff1 (HEAD -> dc-boot-psm, origin/dc-boot-psm) chore(vats): startWalletFactory without provisioning mailbox access
```

with psm-tool from fe6caabd4

[,psm.log](https://github.com/Agoric/agoric-sdk/files/9399618/psm.log)

**Comment by dckc** [comment]
## 87 trades in 2 hrs

I ran `node psm-load.mjs 100 5` but it stopped at 87 because I was parsing node's console output as almost-JSON but I didn't account for `...` abbreviation.

The logs are pretty messy. They should be all JSON-lines, and they should make it easier to correlate stuff.
I include the chain log for reference about block numbers and such.


[,psm100.log](https://github.com/Agoric/agoric-sdk/files/9403562/psm100.log)

[,chain.log](https://github.com/Agoric/agoric-sdk/files/9403569/chain.log)

### "not a live payment" distraction in logs

```
2022-08-23T07:43:29.012Z SwingSet: ls: v6: Error#184: Object [Alleged: IST payment] { getAllegedBrand: [Function: method] } was not a live payment for brand Object [Alleged: IST brand] { isMyIssuer: [Function: method], getAllegedName: [Function: method], getDisplayInfo: [Function: method], getAmountSchema: [Function: method] } . It could be a used-up payment, a payment for another brand, or it might not be a payment at all.
```

### Block times: normal

  | height | blockTime
-- | -- | --
  | 634 | 2022-08-23 5:39:15
  | 2092 | 2022-08-23 7:41:04
  |   |  
blocks | 1458 |  
elapsed |   | 2:01:49
avg block time |   | 0:00:05

## TODO: messages from accounts without smart wallets

how much grief do they cause?

**Comment by dckc** [comment]
@arirubinstein is on the frontier of this one now.
