### ISSUE TITLE
snapshot refcount test too picky; replace with unit test?

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6050]
This test failed in ci (@kriskowal where?) ; it reproduces locally:

https://github.com/Agoric/agoric-sdk/blob/ea1bd997a3b916ce2f1574d4e1a906cd58522806/packages/SwingSet/test/xsnap-snapshots/test-xsnap-snapshots.js#L103

It assumes that executing `() => count` in XS does not change the snapshot.

**Comment by warner** [comment]
This test exercises the snapshot manager, which used to have a bug (#5901) that triggered when a vat manages to produce two identical heap snapshots in a row (the snapshot would get unreferenced, and deleted at the next commit, causing the chain to crash later). To exercise it, I wrote a minimal vat and experimentally determined that a read-only userspace method did not appear to change the XS heap snapshot, supplying the necessary conditions to exercise the bugfix.

I should have realized that was a fragile thing, and apparently the new Endo code (perhaps in concert with the XS snapshot-determinism fix from a few weeks ago) touches enough state to make the heap snapshot differ.

I need to find a better way to exercise this, ideally by not using a real vat. The bug was in `vatKeeper` and `vat-manager.js`, so I guess I should create a pair of those but not connect them to anything else.

**Comment by turadg** [comment]
Since this hasn't seen activity in two years I take it the issue is resolved.
