### ISSUE TITLE
PSM governance tool

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6108]
## What is the Problem Being Solved?

The econ committee should be able to
 - pose questions about PSM parameters and pausing
 - vote on those question

## Description of the Design

smart wallet, continuing invitations

most likely a CLI script; see also #5119

## Security Considerations

_IOU_

## Test Plan

a bit of user testing

cc @rowgraus @Chris-Hibbert @Tartuffo @btulloh

**Comment by Tartuffo** [comment]
@dckc and @Chris-Hibbert please decide who is going to do this.

**Comment by Chris-Hibbert** [comment]
Dan and I talked through this without reaching conclusions. 

The point of this ticket is that in order to exercise control over the PSM, the committee members will need some UI (GUI, CLI, or something based on google sheets) that helps them
 * propose a vote on a governed power
 * find from the electorate what questions are open
 * cast a ballot for a particular position on an open question

In addition, we noticed that the charter invitations should be distributed in parallel with the committee voting invitations in `distributeInvitation` (or nearby).  (#6110)

Also, it's rumored that @turadg is working on smart wallet support for committee voting on PSM param changes. This will presumably play into the tool somehow.

**Comment by Chris-Hibbert** [comment]
#6036 will be helpful in accessing the governance state off-chain.

**Comment by dckc** [comment]
getting charter invitations took a bit of work:

a466108fb WIP: skip tryLookup
c092f96d4 WIP: invite committee members
41bb23dcf WIP: PSM config
fa0c6a20d WIP: smartWallet
c524ccb34 fix: depositeFacet
2cac95aa8 WIP: invitePSMCommitteeMembers
aa47c7bc6 WIP: AGORIC_POWERS = SMART_WALLET

cc @turadg

**Comment by dckc** [comment]
@turadg your work on a PSM tool (#5119) is really a smart-wallet front-end, right? It should be able to do this as well, right?

@Chris-Hibbert is making good progress in this area; I hope both pieces of work come together.

**Comment by turadg** [comment]
Great idea, @dckc . So something like,
```
agoric wallet prepare trade # just like #6015
agoric wallet prepare question # new for #6108
agoric wallet prepare vote  # new for #6108
agoric wallet send --from <address>
agoric wallet watch --from <address> [offerId]
```

and each `address` could be a key value looked up in `agd keys list --json` address mapping (if the value isn't bech32).
