### ISSUE TITLE
Full base64 bundle of contract should not be stored in virtual data

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#6826]
## Describe the bug
Since https://github.com/Agoric/agoric-sdk/pull/6726, the slog file of the daily loadgen test has exploded in size (5-10x). I've traced it down to the base64 encode bundle content of apparently the contract being stored in the state of some virtual object, under an `contractBundleCap` property.

Here is a truncated syscall payload where this occurs:
```
["vatstoreSet","v7","vom.o+35/16","{\"adminNode\":{\"body\":\"#\\\"$0.Alleged: adminNode\\\"\",\"slots\":[\"o-205\"]},\"zcfBundleCap\":{\"body\":\"#{\\\"status\\\":\\\"fulfilled\\\",\\\"value\\\":\\\"$0.Alleged: device node\\\"}\",\"slots\":[\"d-70\"]},\"contractBundleCap\":{\"body\":\"#{\\\"endoZipBase64\\\":\\\
```

## To Reproduce
Run loadgen on any version past Zoe durability

## Expected behavior
No heavy data like this in syscalls

## Screenshots
For reference is a cleaned up slog trace of the first 2 inbound messages of the loadgen test before and after the zoe durability PR landed.

[durability-bundle-cap-regression.tgz](https://github.com/Agoric/agoric-sdk/files/10472374/durability-bundle-cap-regression.tgz)

**Comment by warner** [comment]
That sounds like we aren't yet using bundlecaps everywhere. If something is doing `zoe.install` with entire bundles, rather than bundlecaps, then zoe's storage would explode like that.

This is why I really wanted to remove the non-bundlecap `zoe.install` API entirely (#4486). From what I remember (a braindump from @kriskowal a few weeks ago), the blocker was that some dapp deploy-scripts (outside agoric-sdk) still do things the old way, and would break if we removed the full-bundle `zoe.install` API. cc @gibson042 who've I've drafted to figure out some of those issues.

But this sounds like a problem closer to agoric-sdk. Maybe a test would be to apply #4486 and see where the unit tests or the loadgen test fails. We fix that, see if the loadgen storage size goes back to normal, then unapply the 4486 fix until we get the dapps fixed up. (But I really really don't want to ship the bulldozer/vaults release without 4486).

**Comment by mhofman** [comment]
Ok that explains it. Loadgen has a pending [PR to use `publishBundle`](https://github.com/Agoric/testnet-load-generator/pull/85) which was blocked on a race, not being able to know when the bundle got published and was usable.

I'll see if things have gotten better since and try to land that PR. One problem was being able to feature test this as the API was available but behaved broken.

I agree we should land #4486. Maybe I can used a failed `zoe.install` to fallback to publish bundle.

**Comment by mhofman** [comment]
After landing the loadgen changes, I'm still seeing a lot of `createVat` calls for zcf vats with `contractBundleCap` containing `endoZipBase64` instead of `endoZipBase64Sha512`

**Comment by mhofman** [comment]
Dunno if it helps, but here are the relevant `createVat` syscall payload bodies: 
[daily-perf-a7b668f98880-create-vat.log.gz](https://github.com/Agoric/agoric-sdk/files/10541388/daily-perf-a7b668f98880-create-vat.log.gz)

**Comment by warner** [comment]
Assuming that the core-bootstrap `installBootContracts()` function was the only culprit, I've got a branch to address this.

That function was converting bundle names (for the two "boot contracts", named `centralSupply` and `mintHolder`) into bundles, and then doing a `zoe.install()` with the full bundle. That forces Zoe to store the entire bundle in its durable installationStorage table.

The new approach is to have `installBootContracts` convert the name into a BundleID, and then use `zoe.installBundleID()`, which allows Zoe to store a tiny BundleCap in the table. This uses the pattern mentioned (but never landed) in https://github.com/Agoric/agoric-sdk/issues/4374#issuecomment-1212584161 .

PR incoming.

**Comment by mhofman** [comment]
@warner Now that #6898 landed I'll double check if this is solved

**Comment by mhofman** [comment]
Confirmed on a local loadgen run that the only place where the full bundle source shows up is in the `create-vat` slog entry, which is expected.
