### ISSUE TITLE
Integrate golang components with top-level yarn build

### ISSUE THREAD

**Issue by JimLarson** [Agoric/Agoric#7053]
Currently, components under `golang/` are not built by the standard build instructions `yarn && yarn build`. The extra command `(cd packages/cosmic-swingset && make)` is given in some but not all places where it's necessary. Rather than playing a game of whack-a-mole to track down and fix such omissions, it might be better to just integrate this step with the more prevalent process.

Some thought must be given to be sure this is the behavior we want. Dapp developers might not need or want the Cosmos-level components as part of their development process. OTOH, they would need these components to start a fully-faithful test chain.

See also #7052 for making the whole build more hermetic.

**Comment by michaelfig** [comment]
I have opinions.

I did an experiment (#7037) where references to `agd` went through an `agoric-sdk/bin/agd` shell script that lazily builds the requirements then executes.  So, if the user of the SDK is just using it for the JS, they don't build go, but if `agd` is executed and the build products are out of date, it does the build.

The main aim was to provide something compatible with Cosmovisor so that multiple versions of `agd` could be installed in different subdirectories, a goal in common with #7052.

**Comment by JimLarson** [comment]
The `bin/agd` script takes care of the complete build - so much so that if you're invoking `agd` via the script, you cannot forget to build, so #7037 fixes the underlying need.
