### ISSUE TITLE
Adopt XS native `harden` for vats

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#7275]
## What is the Problem Being Solved?
Vaults scenario testing has shown that native XS harden is roughly 20% faster than SES-shim’s harden on XS:

| worker | vaultsOpened | duration (ms) | avgPerVault (ms) | 
| --- | --- | --- | --- |
| local | 100 | 32147.71866607666 | 321.4771866607666 |
| xs-shim | 100 | 90076.88854074478 | 900.7688854074478 |
| xs-native | 100 | 70358.89608383179 | 703.5889608383179 |

generated via `git checkout ari/perf_vaults packages/vats/test/bootstrapTests/test-vaults-perf.js` and ran in different configurations

## Description of the Design
Experiment in [mfig-native-harden](https://github.com/Agoric/agoric-sdk/tree/mfig-native-harden) is the branch
- Change is in SES-shim lockdown under XS. If `globalThis.harden` exists before `lockdown` then use it. Endo tests, swingset tests.

Notes from discussion:
- can we run moddable lockdown after SES shim lockdown without problems?
- Date.now replacement

## Security Considerations
Will need to ensure this implementation of `harden` meets spec to maintain immutability

## Scaling Considerations
Need to re-run testing to ensure CPU impact is as expected & memory usage isn't off

**Comment by mhofman** [comment]
The main problem is the requirement that native `lockdown` be called before native `harden` and the conflict that the SES shim's own `lockdown` would create (lockdown cannot run on pre-frozen intrinsics). Since we are not ready to adopt native `lockdown` yet, the experiment disabled the native lockdown check, which would require maintaining a branch of the Moddable SDK. We should look if there is a way to satisfy the lockdown check, aka run the [2 following lines](https://github.com/Moddable-OpenSource/moddable/blob/c43982fa35e18495350a357441221298b3dee32c/xs/sources/xsLockdown.c#L68-L70) independently of calling native `lockdown()`:

```c
	if (mxProgram.value.reference->flag & XS_DONT_MARSHALL_FLAG)
		mxTypeError("lockdown already called");
	mxProgram.value.reference->flag |= XS_DONT_MARSHALL_FLAG;
```



One possibility would be for `xsnap-worker` to expose a new global `lockdownStub()` that is called and removed by the SES shim. Or simply for the `xsnap-worker` to set that flag when initializing the VM based on a command line flag.

**Comment by ivanlei** [comment]
In update from Moddable we've heard that native `lockdown` no longer needs to be called before native `harden`.[https://app.zenhub.com/files/219012610/2f9de812-4e0e-4084-832d-9e702627a0da/download](https://app.zenhub.com/files/219012610/2f9de812-4e0e-4084-832d-9e702627a0da/download)

**Comment by warner** [comment]
cc @FUDCo
