### ISSUE TITLE
Perform snapshots only after BOYD

### ISSUE THREAD

**Issue by mhofman** [Agoric/Agoric#7504]
## What is the Problem Being Solved?

Moddable added a feature to only clean out WeakRef during organic gc to mitigate our known issue where liveslots exposes its sensitivity to gc in syscalls (#6784).

However one case where a forced full gc is performed is during a snapshot. The problem is that if we perform an XS upgrade that has a difference in allocation behavior, it may cause different syscalls when replaying the transcript to get the vat online if some representatives or presences were released by the program between the last BOYD and the time the snapshot was taken after.

## Description of the Design

Remove snapshot scheduling, only perform snapshot after delivering a bringOutYourDead.

Possibly force a bringOutYourDead immediately after vat start to create a snapshot of the initialized vat like we have today.

## Security Considerations

None

## Scaling Considerations

None

## Test Plan

TBD

**Comment by mhofman** [comment]
Extracted from https://github.com/Agoric/agoric-sdk/issues/6786

**Comment by warner** [comment]
I've implemented a form of this, but I changed the causality. Instead of inhibiting snapshots to *only* happen after BOYD, I change the snapshot logic to *always* perform a BOYD first. So snapshots will happen according to the usual `snapshotInitial`/`snapshotInterval` schedule, but we'll get an extra BOYD just before each. That seemed cleaner, and I think we still want BOYD to happen more frequently than snapshots.

The limitations of my PR:
* we don't report the extra BOYD to the `runPolicy`, so blocks with snapshots may run longer than expected
  * (we report normal BOYDs computrons to it, just not these extra snapshot-related ones)
  * no userspace code can run during a BOYD, so we've never metered BOYDs (`decrementMeterID`-style)
* if the BOYD fails somehow, or (for some unknown reason) calls `syscall.exit()`, we won't process that in the usual "maybe unwind the crank" portion of `processDeliveryMessage`
  * that might mean that vat-admin is not notified about the problem during that crank (but it might notice on the next delivery to that vat, I'm not sure)
* the extra BOYD does not interact with the existing `vatKeeper.countdownToReap()`, which means some occasional cycle-alignments might cause a double-BOYD
  * wasteful, but not damaging
