### ISSUE TITLE
Bid failed to be filled despite outstanding IST debt and liquidated collateral available

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7679]
## Describe the bug
While testing the happy path (https://docs.google.com/spreadsheets/d/16OZh7zSfwvVF777peK8NLhDeGjqHV3R9L3ZOYto28e0/edit?usp=sharing) , 2 out of the 3 placed bids were successfully filled however the 3rd did not (discount of 15% for 150IST). Expectation was this 3rd bid should have filled as there was still outstanding IST debt and liquidated ATOM collateral available.

Furthermore - we placed another bid (at price of 8 while the auction was running) and it too was ignored. The auction ended with these two opens bids unfilled

The auction should have picked up this 4th bid but instead it did not and ended.

brendanotoole@brendans-MacBook-Pro agoric-cli % inter bid list --from agoric1u00uwvh7jtsmvpuyv0lp8dmfzupmfwyyl8m2w9                
{"id":"bid-1683743600176","discount":15,"give":{"Bid":"150 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}
{"id":"bid-1683745445593","price":"8 IST/ATOM","give":{"Bid":"150 IST"},"maxBuy":"1000000 ATOM","result":"Your bid has been accepted"}

## To Reproduce
1. Create vaults per:
 ![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/a7d6576f-0077-426e-9298-93e2d0985134)
2. Place bids per:
 ![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/705ea16c-1291-4476-ad2c-589f82550d38)
3. Change price from 12.5 to 9.99 to trigger liquidation
4. Observe auction tick forward and the bids being filled/not being filled

## Expected behavior
3rd bid should have filled because IST debt outstanding and ATOM collateral available

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by Chris-Hibbert** [comment]
After adding the two vaults, the auction's targeted debt to raise isn't simply the sum of the two debts. Since the vaults deposited the same amount _(corrected)_ of collateral, they will get the same payout from the proceeds of the auction. If the target raise in this case were 206.025, then when paying them out evenly (because they both contributed 15 collateral to the auction), they would both get half of the 206.025, and only one would be satisfied.

So we have to prorate the required liquidity, and we end up needing to raise 211.05 rather than the 206.025 the spreadsheet shows.

In my repro, All three buyers succeed with a purchase. The first two exhaust their IST, so their seats are exited automatically. The third does not exhaust her IST, since the target IST raise is reached. If she specifies `exitAfterBuy`, her seat should exit automatically. I didn't specify `exitAfterBuy`, so I had to call `tryExit` manually to see that she also received a payout.

**Comment by Chris-Hibbert** [comment]
@otoole-brendan, I think this issue can be closed. The Happy Path scenario now succeeds, and the third bid is processed. A fourth bid would as well. As I wrote above

> The third does not exhaust her IST, since the target IST raise is reached. If she specifies exitAfterBuy, her seat should exit automatically.

I think this explains the fact that you didn't see the third (and fourth) bidder getting their auction purchase back.

**Comment by otoole-brendan** [comment]
Thanks @Chris-Hibbert I concur. This has since been tested and works as expected.
