### ISSUE TITLE
does `console.error(assert.error(e));` throw?

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#7759]
## What is the Problem Being Solved?

I asked for a way to log an error from production code that was unlikely to get lost in production. (My concern may have been misplaced because sometimes logs are not visible when I'm testing. People assure me that regular logging is reliable, and we can add alerts on log messages.) 

MarkM had suggested `console.error(assert.error(e));`, which we had used [in scheduler.js](https://github.com/Agoric/agoric-sdk/blob/f078d4221812788c19ac3df9febe5f7c1b11cb48/packages/inter-protocol/src/auction/scheduler.js#L64).  While @turadg and I were debugging, we saw that 
```
 try {
    return computeRoundTiming(params, baseTime);
  } catch (e) {
    console.error('No Next Auction', assert.error(e));
    return null;
  }
```
didn't seem to be catching errors we thought were being thrown in `computeRoundTiming()`. When we changed that line to `console.error('🚨 No Next Auction', e);`, it worked fine, and the catch clause worked the way we expected.

## The Question

Is there some reason the assert in `console.error('No Next Auction', assert.error(e));` would misbehave here, or were we confused? @erights seems convinced that it should have worked.

**Comment by erights** [comment]
I think we have a misunderstanding of what the argument was in `console.log(assert.error(...))`. Glad to see the full report above because I see the misunderstanding. The argument to `assert.error` should be a details object, such as an 
```js
X`...`
```
expression. It returns an error. `console.log` logs errors well. And for errors made with 
```js
assert.error(X`...`)
```
it logs them especially well, including all the redacted info omitted from the thrown error's message.

Above, the `e` is already an error, so `assert.error(e)` is not appropriate. `console.error('🚨 No Next Auction', e);` is indeed perfectly appropriate.

So I think everything is working as expected. I'm closing. If I misunderstood anything, please reopen.
