### ISSUE TITLE
Vaults Manager should publish lockedPrice to vstorage

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#7799]
## Background / Context
The lockedPrice captured by the Vault Manager determines which vaults get liquidated and is an important element of how the vaults system operates.

This price is captured by the Vault Manager but not currently reported out to vstorage metrics, which means that is not available to be shown to users in the UI or via the CLI.  This ticket is focused on making the contract changes necessary to report it to vstorage such that various clients can be upgraded to make use of it (in separate efforts).

## Describe the bug

Bug has been updated to focus on publishing the lockedPrice to vstorage rather than the secondary work to plumb it through to the UI correctly.

* VaultManager should publish lockedPrice to metrics when a new lockedPrice is taken (i.e., the start of the priceLockPeriod)
* VaultManager should clear the lockedPrice after it has completed using it to make liquidation decisions (i.e.,prior to or at the time of auction start). This clearing activity should ensure that it is not clearing a new lockedPrice in the case where priceLockPeriod and startDelay are close together.
* When there is no lockedPrice, the value should read as null (however null is typically represented in metrics)

## Expected behavior
The vstorage metrics include the lockedPrice when it exists.  When no lockedPrice exists, the value is null

**Comment by Chris-Hibbert** [comment]
See [the answer](https://github.com/Agoric/agoric-sdk/pull/7803#issuecomment-1554851384) to @samsiegart's question on another PR for more details on where this info could be made available.

**Comment by rowgraus** [comment]
I have updated the title to focus on publishing the lockedPrice to vstorage rather than the secondary work to plumb it through to the UI correctly.  I have also edited the ticket body to accompany this.

* VaultManager should publish lockedPrice to metrics when a new lockedPrice is taken (i.e., the start of the priceLockPeriod)
* VaultManager should clear the lockedPrice after it has completed using it to make liquidation decisions (i.e.,prior to or at the time of auction start). This clearing activity should ensure that it is not clearing the *new* lockedPrice.
* When there is no lockedPrice, the value should read as null (however null is typically represented in metrics)
