### ISSUE TITLE
ATOM assets missing following liquidation and reconstitution

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#7806]
## Describe the bug
In validation testing the second half of #7784 - impact to reserve metrics, two issues were observed:
1. Total amounts distributed were less than what is going in (assets missing) - 14.99 (returned to vault) + 14.99 (returned to vault) + 10.01 (bid payout) + 3.575 (bid payout) + 1.107 (ATOM in reserve) vs 45 ATOM
2. vaults seem to have too much and no longer match expectations (each reconstituted vault was expected to receive 14.889 ATOM / 100.5 IST and 14.896 ATOM / 103.51 IST back after reconstitution but had 14.99 ATOM /100.5IST and 14.99 ATOM/ 103.51 IST respectively) 

## To Reproduce
1. Using 12.34 price set up vaults per Flow 2b/reconstitution and 2x bid per https://docs.google.com/document/d/1bXnQ_o3wwfnu-uhX2KSb6ZXB0dU6CsAsGBWm1DXgmE0/edit?usp=sharing 
4. trigger liquidaion with 9.99 pushPrice
5. Check reserve metrics before auction starts
6. Observe liquidation and auction take place
7. Review reconstituted vault information, bid payouts and post-auction reserve metrics

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Additional context
Reserve metrics before auction:

root@3ac654d9e579:/usr/src/agoric-sdk# agoric follow -lF :published.reserve.metrics
{
  allocations: {},
  shortfallBalance: {
    brand: slotToVal("board0257","Alleged: IST brand"),
    value: 0n,
  },
  totalFeeBurned: {
    brand: slotToVal("board0257"),
    value: 0n,
  },
  totalFeeMinted: {
    brand: slotToVal("board0257"),
    value: 0n,

Reserve metrics after:

Reserve after:

  allocations: {
    ATOM: {
      brand: slotToVal("board05557","Alleged: ATOM brand"),
      value: 1107181n, (1.107 IST)
    },
    Fee: {
      brand: slotToVal("board0257","Alleged: IST brand"),
      value: 2135000n, (2.1 IST)
    },
  },
  shortfallBalance: {
    brand: slotToVal("board0257"),
    value: 5525000n, (5.525)
  },
  totalFeeBurned: {
    brand: slotToVal("board0257"),
    value: 0n,
  },
  totalFeeMinted: {
    brand: slotToVal("board0257"),
    value: 0n,

## Screenshots
<img width="1264" alt="Pasted Graphic 10" src="https://github.com/Agoric/agoric-sdk/assets/93355546/df06d5a3-337f-4b26-86e4-ba1d8022e6af">
<img width="1261" alt="Pasted Graphic 11" src="https://github.com/Agoric/agoric-sdk/assets/93355546/b347e5ad-81d3-41e1-be27-e09d640ae525">

**Comment by Chris-Hibbert** [comment]
In the unit test that replicates [this scenario](https://github.com/Agoric/agoric-sdk/blob/bf164a05f425460ad357841b537b8dbc044357a2/packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js#L2625), the  numbers have a little more resolution. Because of rounding, they don't  match the spreadsheet. The UI does some truncation, so it doesn't display all the low-order bits.

The [two vaults get 14.998 Atom](https://github.com/Agoric/agoric-sdk/blob/bf164a05f425460ad357841b537b8dbc044357a2/packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js#L2801) each. [The amount sent to the reserve is 1.109](https://github.com/Agoric/agoric-sdk/blob/bf164a05f425460ad357841b537b8dbc044357a2/packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js#L2821). There's .310 of penalty that doesn't seem to be transferred anywhere. The bidders got 13.585. (I have a correction for the test that shows this.)

45 = 13.585 + .310 + 2 * 14.998 + 1.109.

Early on, `distributeProceeds` subtracts out the penalty, and doesn't add it back before sending what should be all the leftovers to the reserve. That leaks the penalty (.310 in this case)

**Comment by Chris-Hibbert** [comment]
#7827 should fix this.
