### ISSUE TITLE
vaultFactory terms: auctioneerPublicFacet or auctioneer instance?

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7873]
## What is the Problem Being Solved?

The vaultFactory's terms include `auctioneerPublicFacet`; a party who wants to audit/verify the auctioneer is likely to have the instance (for example from agoricNames.instance). This puts the burden on such parties to call `E(zoe).getPublicFacet(instance)` in order to verify.

## Description of the Design

Perhaps the vaultFactory should take the instance and do the call to `E(zoe).getPublicFacet(instance)`

**Comment by turadg** [comment]
@iomekam in the course of #7954 please change it to take the instance instead of the PF.

**Comment by dckc** [comment]
I still see `auctioneerPublicFacet` in the terms
https://github.com/Agoric/agoric-sdk/blob/e9affc8406904f62bc50c407d0463b14b45c059f/packages/inter-protocol/src/vaultFactory/vaultDirector.js#L88

Should we close this as not planned, @Chris-Hibbert ?

**Comment by turadg** [comment]
> I still see `auctioneerPublicFacet` in the terms

That link is to the Director exo. The contract `start` gets that from the instance in terms:
https://github.com/Agoric/agoric-sdk/blob/24f7f32495a6eda13fd75d18620ab9f7989b5d2e/packages/inter-protocol/src/vaultFactory/vaultFactory.js#L106-L107

**Comment by Chris-Hibbert** [comment]
There isn't a way to remove objects from `terms` on upgrade or restart. As @turadg noted, the Director asks Zoe for the `publicFacet`, by providing the instance specified in `privateArgs`. It ignores the old publicFacet, which is still in the terms.

So we made the change proposed in the **Design** section, though legibility has been lost, since `terms` is now misleading.

**Comment by dckc** [comment]
ok. I misread. Thanks for clarifying.
