### ISSUE TITLE
Enable an equivalent of `no-floating-promises` to run as error in every lint run

### ISSUE THREAD

**Issue by ivanlei** [Agoric/Agoric#7888]
## What is the Problem Being Solved?
Today `no-floating-promises` is too slow to run in every lint run in CI or on developer's laptops. This leads to potential issues ala #6000 where manual effort is needed to fix floating promises and it's easy to ship code without fixing things.

Let's get an equivalent tool running all the time.

**Comment by turadg** [comment]
Sounds like https://github.com/Agoric/agoric-sdk/issues/5788   TMK there is no equivalent tool to the that linting rule. The problem is not the rule but running eslint with types metadata because of architectural constraints between TS/eslint. Another big perf factor is that we don't have isolation between packages so there's some n-squared extra work.

**Comment by turadg** [comment]
It's the type tracking that makes it slow. We could get an imperfect approximate version by handling only the cases that don't require inference. Eg E.when without an error handler and isn't bound to a value.

**Comment by turadg** [comment]
It's no longer too slow. It's now running in every CI. But to get it to "error" level we have to,
- https://github.com/Agoric/agoric-sdk/issues/6000
