### ISSUE TITLE
Cannot sync after the latest update.

### ISSUE THREAD

**Issue by fmira21** [Agoric/Agoric#7910]
Hi guys!
My mainnet node is down after the latest update:

```
panic: precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected DB0B961E8C7CCBC970D167240F6E539104BEA101FFBF373728C786C07810F072, got 4D7BD51725140A286533E625B89BB7FF3107DB762428C528E2E7652792FAD7B1
```

Do I need the latest version? In this case, where can I find the `35` tag?

Thank you in advance!

**Comment by mhofman** [comment]
Sorry for the late reply. This issue was caused by the patch that addressed the barberry vulnerability. While the patch did not affect most operations, it caused a difference in JS executions that contained errors raised my cosmos. Such a cosmos error occurred during block 10253149 of the agoric-3 chain and any node that hadn't applied the patch (or installed the pismoD software) computed a state that differed from the consensus majority that had applied the patch.

There is unfortunately currently no way to rollback the JS state, and as such the only way to restart a node that encountered this apphash error is to restore from a known good snapshot.

We have an issue open to address the cause of the divergence to ease future security hot patches: https://github.com/Agoric/agoric-sdk/issues/7929

We also plan on adding a limited rollback capability of the JS state to help restore nodes that encounter apphash errors like this in the future: https://github.com/Agoric/agoric-sdk/issues/7951

**Comment by mhofman** [comment]
For future reference, a node syncing from genesis must apply the Barberry "soft patch" ([`pismoD` release](https://github.com/Agoric/agoric-sdk/releases/tag/pismoD)) bumping `agoric-labs/cosmos-sdk` from `v0.45.11-alpha.agoric.1` to `v0.45.11-alpha.agoric.1.1` after block `10120971` and before `10253149` or it will experience this AppHash issue.

For example, block 10242424 is within that range, and roughly the height around when `pismoD` was distributed to validators at the time.

More details about this issue and syncing from genesis in [Discord](https://discord.com/channels/585576150827532298/1120385792280363088/1120385794926981161).
