### ISSUE TITLE
build-bundle does not work with "current" endo master

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#7947]
Using https://github.com/Agoric/agoric-sdk/pull/7937 to try out "current" agoric-sdk master against "current" endo master, I'm getting a bunch of CI failures in the same place:

At https://github.com/Agoric/agoric-sdk/actions/runs/5295500873/jobs/9585898031?pr=7937#step:3:2927
```
$ node scripts/build-bundle.js
Failed with (TypeError#1)
TypeError#1: consumer.destroy is not a function

  at async Promise.all (index 0)
  at async run (packages/swingset-xsnap-supervisor/scripts/build-bundle.js:21:18)
```

Not immediately urgent because agoric-sdk still only depends on an earlier endo without this problem.

**Comment by erights** [comment]
@michaelfig Did I understand correctly that you understand why we get this failure, but not why we did not get it until recently? Does that mean you also understand what we need to repair so we no longer get this failure?

**Comment by michaelfig** [comment]
> @michaelfig Did I understand correctly that you understand why we get this failure,

Yes!  There were two separate `source-map` package versions in the Agoric SDK.

> but not why we did not get it until recently?

It's a bug in my implementation of `#endo-branch: XXX` which plopped Endo packages into the agoric-sdk CI build without resolving the interdependencies correctly.  That's why we got it only recently.

> Does that mean you also understand what we need to repair so we no longer get this failure?

Yes!  I still need to figure out the details, but a picture is emerging.
