### ISSUE TITLE
Kread Security Review of New Transactions

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8197]
## What is the Problem Being Solved?
For Kread dapp as outlined in the [Partner Go Live checklist](https://docs.google.com/document/d/1UYq7hzSKBwZcRZnpIAUN5Lm78AOGILVaNPoPJxxLdLo/edit?usp=sharing)
Task: Collaborative review session where the purpose & shape of each new transaction is audited 
Purpose: Ensure user-controlled flows are resilient against unexpected or malicious inputs, look for lack of input validation, particularly in areas where it could propagate and lead to consensus failures.
Instructions: OpCo security team to schedule with partner via Slack

**Comment by raphdev** [comment]
I'm nearly done with the review. Going to leave some notes about learnings and formalizing the kinds of things I am spotting, updating them as I go.

----

# What are we looking for here?

Other reviews have been focused on behaviors, proper use of durability and virtualization, upgradeability, powers and permissions. This review narrowly focuses on the transactions and offers handled by the contract. These are generally the ways that the contract is interacted with and how data flows through a contract.

Usually we've written [Attacker's guides](https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/src/AttackersGuide.md) specific to a contract. I will aim at a bit more general guide for what to look in contract offer handling.

## Input validation

* Validating data in incoming proposals. Usually via type guards. A manual validation with no type guards means we don't apply out-of-the-box validation, which would be a red flag.
  * Type guard makes this more of an interrogation of: is the type sufficient? Should a `string` type be used when there's only a range of possible values (e.g. `.or('yes','no')`)? 
* Beyond type guards, whether the data types are restrictive enough for their use. Bounds checking, range and length restriction beyond what type allows when necessary.
  * What happens if you provide a very large string, or a very large number?

## Misc

* Are critical operations interleaved with asynchronous code? This can leave an opportunity for race conditions.

**Comment by raphdev** [comment]
## Observations

* All types are guarded, providing the basic input validation.

### Room for improvement

* There are several string types that could be more restrictive. I will note opportunities for SDK improvement as well that can facilitate these:
  * `names` are a string type, but ideally should be subject to size and character set limits. Do we want `.@#$%@#%^` to be an allowable character name?
  * If there is a specific format for `artistMetadata`, it might make sense to enforce it. Otherwise, next point applies.
  * Similarly, `title`, `description`, and others, while reasonably less restrictive, should not be arbitrarily large.

### Raised issues

* In addition to the string type note above, character names are used as key or part of the key for various chain storage (via vat data), meaning there is an implicit restriction mismatch: chain storage keys are limited to 100 alphanumeric characters. If you make certain character names, it will fail unexpectedly!
* Potential TOCTOU - https://github.com/Kryha/KREAd/issues/14

### Opportunities for SDK improvement

* Similar to other storage mechanisms, we should support a variety of string types with their own restrictions. We've explored allowing regex based patterns, but there are resource exhaustion risks involved.
  * In particular we should have a type for keys used as chain storage keys with the same restrictions, to be more explicit.

**Comment by raphdev** [comment]
I'm closing this for now; may take another peek as we get closer to release in case there's new functionality I didn't see before, but the bulk of the work is done.
