### ISSUE TITLE
RecorderKit types incorrect

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8444]
Types are wrong for RecorderKit ([discussion](https://agoricopco.slack.com/archives/C038WUK356Z/p1695311329208529))

Because we lacked a Remote type, we used a local type. That made the developer using it think it could make local calls but they all had to be remote.

**Comment by iomekam** [comment]
First draft of PR is ready [here](https://github.com/Agoric/agoric-sdk/pull/8481). I did my best doing the changes with a "blind" eye. Next steps are to see how tests are affected by the change and iterate from there

**Comment by iomekam** [comment]
I'm getting some failures [here](https://github.com/Agoric/agoric-sdk/actions/runs/6698522857/job/18200888134?pr=8481), so I'll need to spend time iterating and diagnosing what's going on

**Comment by iomekam** [comment]
I was able to figure out what was causing the functional tests to fail. After fixing that, it looks like the only problem is around linting, which I've been addressing iteratively.

One question that has arisen is what we should return for [makeChildNode](https://github.com/Agoric/agoric-sdk/blob/5263febc3eb667796dc659b150d1dcb4108453d9/packages/notifier/src/types-ambient.js#L324C6-L324C6). It's currently returning a `StorageNode` instead of an `ERef`, so the question is whether we should continue this pattern or move to `Awaited<FarRef<StorageNode>>`

**Comment by gibson042** [comment]
The StorageNode typedef looks correct to me... if you have a local instance, you can indeed invoke `makeChildNode` to synchronously receive an actual StorageNode. But if you have a possibly-remote reference to a StorageNode, then you must use eventual send and all results will be asynchronous—but that's because of `E`, rather than anything specific to StorageNode.

**Comment by iomekam** [comment]
I was able to arrive at a solution that localized the change to just `recorder.js` and without having the change the method signature of `makeChildNode`! I'll be opening the PR for review shortly
