### ISSUE TITLE
Crabble - Security Review of New Transactions

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8466]
## What is the Problem Being Solved?

Task: Collaborative review session where the purpose & shape of each new transaction is audited

Purpose: Ensure user-controlled flows are resilient against unexpected or malicious inputs, look for lack of input validation, particularly in areas where it could propagate and lead to consensus failures.

Instructions: OpCo security team to schedule with partner via Slack

**Comment by raphdev** [comment]
Referencing [previous notes](https://github.com/Agoric/agoric-sdk/issues/8197#issuecomment-1721747135):

> ## What are we looking for here?
> Other reviews have been focused on behaviors, proper use of durability and virtualization, upgradeability, powers and permissions. This review narrowly focuses on the transactions and offers handled by the contract. These are generally the ways that the contract is interacted with and how data flows through a contract.
> 
> Usually we've written [Attacker's guides](https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/src/AttackersGuide.md) specific to a contract. I will aim at a bit more general guide for what to look in contract offer handling.
> 
> ### Input validation
> Validating data in incoming proposals. Usually via type guards. A manual validation with no type guards means we don't apply out-of-the-box validation, which would be a red flag.
> Type guard makes this more of an interrogation of: is the type sufficient? Should a string type be used when there's only a range of possible values (e.g. .or('yes','no'))?
> Beyond type guards, whether the data types are restrictive enough for their use. Bounds checking, range and length restriction beyond what type allows when necessary.
> What happens if you provide a very large string, or a very large number?
> ### Misc
> Are critical operations interleaved with asynchronous code? This can leave an opportunity for race conditions.

**Comment by raphdev** [comment]
## Observations

* Validation was done through extensive use of patterns, with few minor exceptions. Raised issues were the few places where validation was missing or could be stricter.

## Raised issues

* Certain offer arguments could be validated more strictly. Most are strings with default limit which is likely excessive. Additionally the offer arguments raised weren't enforced by patterns. 
  * @0xpatrickdev pointed out how lacking pattern enforcement allowed arbitrary data in contract state.
  * https://github.com/CrabblePitch/crabbleProtocol/issues/135
* Similarly, timer related values should be bounded to amounts that reflect expected usage and don't create unnecessary work on the chain, such as placing a bid with a timer wake up that would execute in the next block (and would not allow any opportunity for user interaction).
  * https://github.com/CrabblePitch/crabbleProtocol/issues/148
* @0xpatrickdev also raised input validation issues related to offer safety
  * https://github.com/CrabblePitch/crabbleProtocol/issues/136
  * https://github.com/CrabblePitch/crabbleProtocol/issues/138
* Interleaving hazard -- operations relying on state being unchanged since last checked across a turn boundary.
  * https://github.com/CrabblePitch/crabbleProtocol/issues/139

**Comment by Chris-Hibbert** [comment]
The links above are all to a private repo. If you need access, request it through appropriate channels.
