### ISSUE TITLE
Test that Zoe support seats and offers through upgrade.

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#8502]
## What is the Problem Being Solved?

#8453 is ABD. The main thing that's missing at this point is a test that demonstrates that it works in the upgrade environment.

## Description of the Design

A test that starts from (a copy of) mainNet. It should ensure there's a contract with outstanding offers or seats. I think vaults would work, or it could use coveredCall, atomicSwap, or a purpose-built contract in order to have additional instrumentation. After upgrading, the outstanding offers & seats should still be alive, the contract should still be responsive, and the offers should be exercisable.

## Security Considerations

We're concerned about offer-safety.

## Scaling Considerations

Not a big issue here.

## Test Plan

See above.

## Upgrade Considerations

Ditto.

**Comment by turadg** [comment]
https://github.com/Agoric/agoric-3-proposals/pull/18 was just progress. (I neglected to remove the "closes:" before merging)

Still to do,
1. Incorporate more of @dckc 's feedback from https://github.com/Agoric/agoric-3-proposals/pull/18
2. add a test of restarting vat-admin

The SDK PR tests head against head. It shows that the bug with promise watchers is gone but can't test the "repair" because it doesn't have the earlier state to repair.

So this test needs to:

1. Make an open offer (e.g. bid)
2. Core-eval to restart vat-admin vat
3. Make sure the offer stays open (demonstrating repair)

**Comment by Chris-Hibbert** [comment]
Blocked on [A3P#74])https://github.com/Agoric/agoric-3-proposals/issues/74).

**Comment by Chris-Hibbert** [comment]
This is [sufficiently tested in A3P](https://github.com/Agoric/agoric-sdk/blob/master/a3p-integration/proposals/a%3Aupgrade-next/wallet-repairs.test.js).
