### ISSUE TITLE
old vow watch not woken up by fulfillment in new incarnation.

### ISSUE THREAD

**Issue by erights** [Agoric/Agoric#9126]
Bug isolated and demonstrated at https://github.com/Agoric/agoric-sdk/pull/9125 . 

Isolates the bug that #9097 is stuck on. As isolated, the problem does reproduce.

I'm following the general testing pattern used in #9097, especially in test-async-flow.js, which is where I'm having this problem. There, see https://github.com/Agoric/agoric-sdk/blob/9a00502ec871ee623b88b1781b74d80abd25fdc5/packages/zone/test/async-flow/test-async-flow.js#L181-L182
I shouldn't need the `asyncFlow.wake()` call. But if I remove it I get the same symptom isolated here:

If I `watch` with an unresolved durable vow and durable watcher in the first incarnation, and then I resolve that durable vow in the second incarnation, the durable watcher that was watching that vow should now wake up. It doesn't.

@michaelfig , is this a bug in watching durable vows across incarnations?

**Comment by michaelfig** [comment]
After studying the problem, I'm now convinced the only issue is that the `nextLife` implementation doesn't properly reject platform promises being watched by earlier incarnations the way they would be under SwingSet.  That's a kernel feature, and vows rely on those "vat upgraded" rejections to function correctly.

With `nextLife`, you only get a faked-out liveslots instance, which does no special handling of native promises from former incarnations, resulting in them never being resolved.

So, unless we invest the time to add more functionality to the `nextLife` implementation, I'd recommend switching to a more faithful upgradeTest framework.

**Comment by warner** [comment]
Yeah, maybe we could add a debug hook to liveslots that `nextLife` could call, to reject all locally-decided-and-watched promises, to replace what the kernel would do in a more-real environment. It would be a little bit like the old `dispatch.stopVat`, which we removed because we didn't want to rely upon the old incarnation doing anything (in case it was so broken that it couldn't participate in upgrade). The old `stop-vat.js` (in git) might be useful for inspiration, although I don't remember if we implemented reject-local-promises before or after we removed `stopVat`.

**Comment by mhofman** [comment]
> add a debug hook to liveslots that `nextLife` could call, to reject all locally-decided-and-watched promises

Do we actually need a hook to liveslots for this, or could this be done from the outside somehow? Can't we parse the baggage to get the watched promises, and simply inject the rejections like the kernel would do? The part that I'm unsure about is how we would know which promises were decided by the vat (we don't have a kernel or clist in these tests from what I understand).

**Comment by michaelfig** [comment]
> how we would know which promises were decided by the vat

Yeah, that's a trick.  The current tests don't have any clear boundary between "inside" and "outside" the vat, since both sides share the same compartment without designating what side each of them is on.

If you have anything to sketch out about how I might solve this, the right place to do it is in `packages/async-flow/test/prepare-test-ava.js` nextLife, where I tried putting a fakeStore dump (baggage is a branch of fakeStore that doesn't contain the watchedPromiseTable):

```js
const { fakeStore } = incarnation;
console.log('@@@ fakeStore.entries());
```

I don't know enough about liveslots to understand how to get ahold of the `watchedPromiseTable` contents (given the results of `fakeStore.get('watchedPromiseTableID')`), traverse them, and queue up rejections for the victims (assuming I can identify them somehow) before returning from `nextLife`.

**Comment by mhofman** [comment]
> both sides share the same compartment

Oh I just realized these tests don't create a full liveslots talking to the kernel over simulated syscalls, but instead instantiate the virtual data part of liveslots only. As such I am not even sure there is any support for "message sends" and "external promise resolution". I'm really confused now.

> the `watchedPromiseTable` contents (given the results of `fakeStore.get('watchedPromiseTableID')`), traverse them

If we looked from the outside, that'd require parsing the collection as encoded in vatStore. But since we're in a more custom environment, maybe we could get a hold of the collection more directly. Or we might could just hook into `maybeExportPromise` https://github.com/Agoric/agoric-sdk/blob/a48b2ce1140d152c48aaee59b21df95136445e37/packages/swingset-liveslots/tools/fakeVirtualSupport.js#L273
