### ISSUE TITLE
types for chain addresses

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9162]
## What is the Problem Being Solved?

With orchestration there will be "chain address" for many chains and functions that take an address may only work for addresses on a certain chain.

## Description of the Design

Use TS string templates to create a generic "Cosmos address" and then concrete types for some well known chains. Consider having special addresses for "validator" etc

**Comment by 0xpatrickdev** [comment]
#9312 contributed towards this. ~Two areas where I see remaining work -
  - `LocalChainAccount` should use a `ChainAddress` object instead of a string
  - finalize types in `orchestration/src/types.d.ts`: 
  https://github.com/Agoric/agoric-sdk/blob/8e94b2af44d002fbf1c6cd316ec309d24e82042e/packages/orchestration/src/types.d.ts#L85-L92
  
     - do we need `addressEncoding`? I'm not sure we will be doing any encoding/decoding of pubkeys, so maybe no?
     - "etherum" encoding should maybe be `hexadecimal` 
     - Tangential - we need to ensure `chainId` is readily available via `Chain` / `ChainInfo`

**Comment by 0xpatrickdev** [comment]
Discussion around renaming `ChainAddress.address` -> `ChainAddress.value` led me back here... More recent thoughts: 

- I think `addressEncoding` is helpful to preserve as it distinguishs accounts on cosmos-sdk chains that support hex and bech32. `encoding`, might be more concise 
- EVM `chainId`s are integers. We might want an additional human-readable field, `chainName` or `shortName`, to capture something like 'eth' or 'gno'. See [eip-3770](https://eips.ethereum.org/EIPS/eip-3770) which is unofficially adopted by many 
   
   
[This gist](https://gist.github.com/0xpatrickdev/8fdd882a232cbae3d4d65e1eb4403a81) attempts to spec out a universal blockchain address type. The pubKey types are largely irrelevant since we are only dealing with contract-controlled accounts.
