### ISSUE TITLE
ability to upgrade Lerna and Yarn in Endo without doing so in agoric-sdk

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9288]
## What is the Problem Being Solved?

Endo has a green PR to update to Yarn 4,
- https://github.com/endojs/endo/pull/2222

Its [agoric-sdk integration PR](https://github.com/Agoric/agoric-sdk/pull/9285) breaking on the getting-started integration and for good reason: its version of Lerna isn't compatible with workspace: protocol. That's since been fixed (https://github.com/lerna/lerna/issues/2564) but Endo and Agoric-SDK are on Lerna 5.6.2. 

Because of the way getting-started works, running specific build commands in an Endo checkout, we can't do it without making changes to agoric-sdk too.

## Description of the Design

To keep Endo unaware of how it's being integrated with agoric-sdk, we could teach agoric-sdk how to integrate with current Endo master and with the Yarn 4 / Lerna 5+.

Alternately, we could create a hook in Endo that agoric-sdk can use to do what it wants done. Then agoric-sdk doesn't have to know about the change in Endo, because that hook will do whatever's necessary.

**Comment by michaelfig** [comment]
Work has been done to make the Endo and Agoric SDK repos less dependent on one another's tooling, especially for the `getting-started` integration tests.

I'm closing this issue since the Agoric SDK nightly tests against Endo master now work fine with Endo using the `workspace:` protocol.  Upgrading only Endo's Lerna to a newer version supporting `workspace:` did the trick.
