### ISSUE TITLE
add support for Vows to smart-wallet

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9308]
## What is the Problem Being Solved?

Currently when an OfferResult is a promise, smartWallet awaits it with `watchPromise` to record the offer result. If, as in the case of an async-flow from orchestration, the result is a Vow for a primitive or for invitationMakers, the current smart wallet implementation will discard the Vow rather than handling what it fulfills to.

https://github.com/Agoric/agoric-sdk/blob/fbd8633ae9f8420a589dd9bc32925418f2dde060/packages/smart-wallet/src/offerWatcher.js#L30-L40

## Description of the Design

We could use `watch` in VowTools in place of the current watchPromises.

We might want to go further and use asyncFlow to refactor much of the smart wallet state handling.

**Comment by dckc** [comment]
> Currently when an OfferResult is a promise, smartWallet awaits it with watchPromise to record the offer result.

how is that a problem?

**Comment by mhofman** [comment]
> how is that a problem?

`watchPromise` is not sufficient to handle vows as result

**Comment by dckc** [comment]
"handle" in what sense? "sufficient" in what sense? In what cases do we have vows as offer results?

**Comment by mhofman** [comment]
> "handle" in what sense? "sufficient" in what sense? In what cases do we have vows as offer results?

An offer handler that wants to survive upgrade will likely return a vow. This will happen automatically if implementing the offer handler as an async-flow. Maybe the problem is wider than the smart wallet, I am not sufficiently familiar with offers and zoe, but a vow returned by the offer handler would not represent the final result. For that, the vow needs to be watched to get the final result (I believe it's already possible for an offer handler to return a value before the offer is considered "done" or whatever the terminology is there)

**Comment by dckc** [comment]
in particular, an async-flow that intends to result in invitationMakers needs support

**Comment by 0xpatrickdev** [comment]
This task blocks us on https://github.com/Agoric/agoric-sdk/pull/9591 (#9449, part of async-flow integration) without making some compromises (disabling boot tests where offer handler failures are tested).

**Comment by 0xpatrickdev** [comment]
#9620 was revised to only include changes in `@agoric/vow`. The previous revision was preserved at `pc/watch-utils-as-promise`, and the diff was pulled out to `9308-smart-wallet-vows`.
