### ISSUE TITLE
make vat-localchain resumable

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9484]
## What is the Problem Being Solved?

The localchain vat is upgradable, but when it does any outstanding promises will be severed.

## Description of the Design

- Change the type of every return to PromiseVow (`@returns {Promise<T>}` becomes `@returns {PromiseVow<T>}` to ensure that callers of that function use either `when` or `watch` to extract `T`)
- Use watch for the deposit method implementation (but I think we can still consider skipping that one)

**Comment by mhofman** [comment]
To clarify, the localchain vat seem to be resumable today given the following:
- We maintain the scheduling property where a vat is only upgraded after swingset is quiescent (assumptions about current scheduling and how upgrades are triggered)
- `deposit()` deals with a "local to the chain" `payment` object (assumption about origin of issuers / payments).

Since we'll likely need to stop making these assumptions in the future, consumer of the localchain API should be able to handle a vow return value. Changing the type now helps detect cases where consumers are not ready.
