### ISSUE TITLE
Vaults not being liquidated and therefore collateral not being sent to auctioneer for auction (Xnet)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/Agoric#9963]
## Describe the bug
While testing the auction and vaults core eval null upgrade fix - I discovered during liquidation testing that vaults I expected to get liquidated from a price change from 12.34 to 9.99 did not liquidated even though 9.99 price confirmed in system (confirmed via UI - vaults are 'at risk) - and I can see auction is using 9.99 as start price.

I can see auction start using 9.99 start price and tick down to completion but it never pulls in the liquidated collateral.

brendanotoole@brendans-MacBook-Pro agoric-sdk % inter auction status --book 0
{
  "schedule": {
    "activeStartTime": "2024-08-26T20:40:11.000Z",
    "nextStartTime": "2024-08-26T20:45:11.000Z",
    "nextDescendingStepTime": "2024-08-26T20:40:51.000Z"
  },
  "book0": {
    "startPrice": "9.99 IST/ATOM",
    "currentPriceLevel": "8.991 IST/ATOM",
    "startCollateral": "0 ATOM",
    "collateralAvailable": "0 ATOM"
  },
  "params": {
    "DiscountStep": "5.00%",
    "ClockStep": "00:00:10",
    "LowestRate": "65.00%"
  }
}
brendanotoole@brendans-MacBook-Pro agoric-sdk % 

## To Reproduce
1. See 'Vault Setup' and 'Liquidation happy path scenario' -> https://docs.google.com/document/d/1bXnQ_o3wwfnu-uhX2KSb6ZXB0dU6CsAsGBWm1DXgmE0/edit?usp=sharing 
2. Short version -> create vault at 12.34 price (15 ATOM and minting 100IST)
3. Change price to 9.99
4. From CLI monitor auction
5. See error

## Expected behavior
Those vaults should get liquidated and the liquidated collateral should be sent to the auctioneer.

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by otoole-brendan** [comment]
Update: Vaults finally changed from 'Vault at Risk' to 'Vaults at Risk: Liquidating in X mins' in Vaults UI. I watched it tick down but then it just resets to 'Liquidating in 5mins' and they never liquidate

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/ff85f51f-751f-4444-8814-2acc66d03252">

**Comment by dckc** [comment]
## Diagnosis: bids are going to the old auctioneer due to lack of agoricNames update

The bids specify the contract using `instancePath: [ 'auctioneer' ]`; that is: look up `auctioneer` under `agoricNames.instance`.

The vstorage viewer reports block 1 for [published.agoricNames.instance](https://p2p-org.github.io/p2p-agoric-vstorage-viewer/#https://xnet.rpc.agoric.net/|published,published.agoricNames|published.agoricNames.instance)
suggesting that it has not changed since then, suggesting the bid was placed with the old auctioneer.

Checking the code... we don't see updating agoricNames.instance in [add-auction.js](https://github.com/Agoric/agoric-sdk/blob/7296b4772c47c36a28c28e8e8f13c74c7b3fc697/packages/inter-protocol/src/proposals/add-auction.js).
