### ISSUE TITLE
Orchestration API product features covered by multichain-testing

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#9964]
Before we ship Orchestration API we want functional integration tests of its capabilities. This requires the multichain-testing environment.

**Comment by 0xpatrickdev** [comment]
First pass at describing coverage:

| Test Name | Description | Methods Used | Uses async-flow | Contract Used | Untested |
|-----------|-------------|--------------|-----------------|---------------|----------|
| [account-balance-queries](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/multichain-testing/test/account-balance-queries.test.ts) | Makes an account on local and remote chains and sends a balance query. Always returns an empty balance since the account creation and balance query occur in the same offer handler. | - `orchAccount.getBalance()`<br>- `orcAccount.getBalances()`<br>- `orch.getChain()`<br>- `orch.makeAccount()` | Yes | [query-flows.contract.js](https://github.com/Agoric/agoric-sdk/blob/9ced650db6b0983ae5d060a00b3752c3700c4f06/packages/orchestration/src/fixtures/query-flows.contract.js) | |
| [auto-stake-it](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/multichain-testing/test/auto-stake-it.test.ts) | Makes Local + Cosmos `orchAccounts` and sets up a transfer tap (vtransfer, ibc-hooks) to auto-delegate. Reads local `orchAccount` address from vstorage and sends IBC transfer from `HDWallet` to invoke autostake | - `orch.getChain()`<br>- `chain.makeAccount()`<br>- `localOrchAccount.monitorTransfers()`<br>- `cosmosOrchAccount.delegate()` | Yes | [auto-stake-it.contract.js](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/packages/orchestration/src/examples/auto-stake-it.contract.js) | |
| [basic-flows](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/multichain-testing/test/basic-flows.test.ts) | Makes an account on a remote chain and returns a continuing offer (with invitationMakers like Delegate, Undelegate, Transfer, Send) | - `orch.getChain()`<br>- `orch.makeAccount()` | Yes | [basic-flows.contract.js](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/packages/orchestration/src/examples/basic-flows.contract.js) | |
| [chain-queries](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/multichain-testing/test/chain-queries.test.ts) | Sends balance query from the chain object via ICQ and localchain queries. Queries pre-funded accounts that have balances. Ensures `icqEnabled: false` chains provide a helpful error message. | - `orch.getChain()`<br>- `Chain.query()` | Yes | [query-flows.contract.js](https://github.com/Agoric/agoric-sdk/blob/9ced650db6b0983ae5d060a00b3752c3700c4f06/packages/orchestration/src/fixtures/query-flows.contract.js) | |
| [ica-channel-close](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/multichain-testing/test/ica-channel-close.test.ts) | Ensures an ICA account holder can `deactivate` and `reactivate` their account, verifying the ICA channel closure process. Ensures external clients cannot initiate ChannelClose for ICA and Transfer channels (vibc) | - `orch.getChain()`<br>- `orch.makeAccount()`<br>- `orcAccount.deactive()`<br>- `orcAccount.reactivate()` | Yes | [basic-flows.contract.js](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/packages/orchestration/src/examples/basic-flows.contract.js) | |
| [send-anywhere](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/multichain-testing/test/send-anywhere.test.ts) | SendAnywhere takes a Payment from an offers and sends it over IBC to another chain. It involves making a contract-level LocalOrchAccount, depositing to it via `zoeTools.localTransfer`, and using `LOA.transfer()` to send the funds over IBC. | - `LOA.makeAccount()`<br>- `LOA.transfer()`<br>- `zoeTools.localTransfer()`<br>- `LOA.deposit()`<br>- `Chain.getVBankAssetInfo()`<br>- `Chain.makeAccount()`<br>- `Orch.getChain()` | Yes | [sendAnywhere.contract.js](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/packages/orchestration/src/examples/sendAnywhere.contract.js) | - Multi-hop (PFM) transfers (not implemented in contract) |
| [stake-ica](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/multichain-testing/test/stake-ica.test.ts) | Makes an account and performs/validates staking actions: `Delegate`, `WithdrawReward`, `Undelegate` | - `orch.getChain()`<br>- `orch.makeAccount()`<br>- `orcAccount.delegate()`<br>- `orcAccount.withdrawReward()`<br>- `orcAccount.undelegate()` | No, but we can point these tests to `basicFlows` or prioritize #9838 | [stakeIca.contract.js](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/packages/orchestration/src/examples/stakeIca.contract.js) | - `Redelegate`<br>- `WithdrawRewards` (plural) (not implemented)<br>- `StakingQueries` (not implemented)<br>- `StakingFromLocalOrchAccount` |
| swapExample | | | Yes | [swapExample.contract.js](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/packages/orchestration/src/examples/swapExample.contract.js) | - `Everything` - contract incomplete |
| unbondExample | | | Yes | [unbondExample.contract.js](https://github.com/Agoric/agoric-sdk/blob/bc8900d6cd2a51265533b9731437391f9194ec05/packages/orchestration/src/examples/unbondExample.contract.js) | - `Everything` - contract incomplete |


- `Send`, `SendAll` / `.send()`, `sendAll()` are not covered by E2E tests - only unit tests
- The `Transfer` invitations are not directly covered, nor `CosmosOrchAccount.transfer()`, but `LocalOrchAccount.transfer()` is tested via `auto-stake-it` and `send-anywhere`
- `Deposit` and `Withdraw` invitations for LOA are not tested because they don't exist (until #9193). `.deposit()` is indirectly tested via `zoeTools.localTransfer` in `send-anywhere`

**Comment by 0xpatrickdev** [comment]
Also, this resource exists, is up to date, and should provide a helpful point of reference:
https://github.com/Agoric/agoric-sdk/blob/master/packages/orchestration/src/exos/README.md

**Comment by turadg** [comment]
I put the above comment into https://github.com/Agoric/agoric-sdk/blob/9964-orch-usage/packages/orchestration/USAGE.md and revised it.
